Fix/error on install source
CoinAlpha/hummingbot pull request #103
Opened 2022-02-22 08:28 UTC by sparksun

**Before submitting this PR, please make sure**:

- [Yes] Your code builds clean without any errors or warnings
- [Yes] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

When following the installation documentation for source installation, two errors are encountered. One is a lack of necessary imports, and one is a C++ type error. I fixed it. This commit is related to[ issue #5107](https://github.com/hummingbot/hummingbot/issues/5107)

**Tests performed by the developer**:

**Tips for QA testing**:

2022-02-22 20:24 UTC, martinkou requested changes

2022-02-23 03:38 UTC, sparksun commented on hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx
> -                is_maker: Optional[bool] = None) -> AddedToCostTradeFee:
I suggest you try to see if your solution can pass compile, it doesn't work for me.

2022-02-23 12:20 UTC, aarmoa commented
@sparksun please make sure you are sending your changes to the correct repository. It seems to me that your intention is to send this to Hummingbot Foundation repository, but this PR is in CoinAlpha fork repository (we never merge code in this repository, it is only used for our internal work)

2022-02-24 07:06 UTC, sparksun commented
I'm very sorry that I got the wrong repository, then I will withdraw the relevant pull requests, and I will recheck that the correct repository is working correctly.

2022-02-24 07:06 UTC, closed without merging