Fix/Avellaneda - remove _latest_parameter_calculation_vol
CoinAlpha/hummingbot pull request #108
Opened 2022-02-23 21:50 UTC by mhrvth

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

_latest_parameter_calculation_vol parameter needs to be removed. It's a leftover of a previous implementation, it's use corrupts volatility measurement.

**Tests performed by the developer**:

- ran the strategy with ascend_ex paper
- ran unit test

2022-02-23 21:50 UTC, mhrvth commented
[sc-23664]

2022-02-24 00:22 UTC, aarmoa requested changes

2022-02-24 00:22 UTC, aarmoa commented on hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
> -        self._latest_parameter_calculation_vol = s_decimal_zero
If we remove this variable from the .pyx file we need to remove it also from the .pxd file

2022-02-24 02:10 UTC, RC-13 approved these changes
LGTM!

Test Summary:
    * Create and started an Avellaneda MM strategy using paper trade connector and live connector and confirmed that no issue occurred during the initialization of the order books.
    * Configure different parameters to make sure they did not break
    * Check the volatility in the status window and confirmed that it adjust from time to time
    * Confirmed that trades are recorded and confirmed that orders are adjusted and behaved according to the specified parameters.

2022-02-24 20:09 UTC, aarmoa approved these changes
All changes look good to me

2022-02-25 12:01 UTC, mhrvth commented
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5146

2022-02-25 12:01 UTC, closed without merging