Feature/sc 24554/update gatewayevmamm to handle fees properly
CoinAlpha/hummingbot pull request #146
Opened 2022-03-16 21:25 UTC by james-hummingbot

2022-03-16 21:55 UTC, vic-en commented on hummingbot/client/settings.py
> +
```suggestion
```

2022-03-16 21:55 UTC, vic-en commented on hummingbot/connector/gateway_EVM_AMM.py
> +from hummingbot.client.settings import (AllConnectorSettings)
```suggestion
from hummingbot.client.settings import AllConnectorSettings, ConnectorSetting
```

2022-03-16 21:55 UTC, vic-en commented on hummingbot/connector/gateway_EVM_AMM.py
> +    async def update_connector_flat_fees(self, token: str, gas_price: Decimal):
```suggestion
    async def _update_connector_flat_fees(self, token: str, gas_price: Decimal, is_maker: bool):
        connector_setting:   = AllConnectorSettings[self.name]
        if is_maker:
            connector_setting.trade_fee_schema.maker_fixed_fees = [TokenAmount(token, gas_price)]
        else:
            connector_setting.trade_fee_schema.taker_fixed_fees = [TokenAmount(token, gas_price)]
```

2022-03-16 21:55 UTC, vic-en commented on hummingbot/connector/gateway_EVM_AMM.py
> +        self._setting_name = f"{self.connector_name}_{self.chain}_{self.network}"
```suggestion
```

2022-03-16 21:55 UTC, vic-en commented on hummingbot/connector/gateway_EVM_AMM.py
> +
```suggestion
```

2022-03-21 23:05 UTC, martinkou commented on hummingbot/connector/gateway_EVM_AMM.py
> +            self._update_connector_fees(gas_price_token, Decimal(str(gas_price)), trade_type == TradeType.BUY)
All amm_arb trades are taker trades - they all take away liquidity. If you're a maker, then you'd be putting in your tokens into an AMM pool, which is currently no supported by our connector.

2022-03-21 23:14 UTC, martinkou commented on hummingbot/connector/gateway_EVM_AMM.py
> +            connector_setting.trade_fee_schema.taker_fixed_fees = [TokenAmount(token, gas_price)]
The fee you need to pay is not just `gas_price` - it's `gas_price` * `gas_cost`.

2022-03-21 23:40 UTC, martinkou commented on hummingbot/connector/gateway_EVM_AMM.py
> +            connector_setting.trade_fee_schema.taker_fixed_fees = [TokenAmount(token, gas_price)]
Let's use a real swap transaction as an example

https://ropsten.etherscan.io/tx/0xeaf6b51033b8060c527d58f71ec66226da8d98ec77290017ec7787ed7ab60ae6

The code that emitted the transaction specified a gas limit of 150688, which is not very precise but also not too far from the actual gas amount used (98662).

The gas price for each unit of gas was 30 Gwei. 1 wei is 1e-18 ETH.

So the actual transaction fee spent was `30e9 * 98662 * 1e18 = 0.00295986 ETH`.

Now, the actual gas use is only really known when the transaction is executed. Let's say you're just estimating and you're using the gas limit, or some bigger number that you got from the Uniswap libary. Then, you can estimate the transaction cost like this.

`${gas price in wei} * ${gas estimate} * 1e-18`

So if you're using the gas limit instead, then the cost estimate would be

`150688 * 30e9 * 1e-18 = 0.00452064 ETH`.

2022-03-22 00:29 UTC, martinkou commented on hummingbot/connector/gateway_EVM_AMM.py
> +            connector_setting.trade_fee_schema.taker_fixed_fees = [TokenAmount(token, gas_price)]
This also highlights a flaw with this design... there's actually no fixed fee for a `GatewayEVMAMM` connector - the gas limits for, say, Uniswap V2 and Uniswap V3 are different (with Uniswap v3 being much higher). So the fees for trading on Uniswap v3 are higher, even with the same connector.

2022-03-22 02:01 UTC, martinkou commented on hummingbot/connector/gateway_EVM_AMM.py
> +            connector_setting.trade_fee_schema.taker_fixed_fees = [TokenAmount(token, gas_price)]
Let's just make the gas fees calculation a special case for `GatewayEVMAMM` for now - without needing to following prior patterns for trading fees. The way it works for gateway exchanges is different.

2022-03-26 13:27 UTC, martinkou commented
This patch is taking way too long. I'm taking over and aiming to finish this within this weekend.

2022-03-28 07:15 UTC, martinkou commented
This is ready for testing and review.

There's still one small issue left: when an amm_arb strategy starts, there's a brief period where it calculates the arbitrage prices without including gas prices. I'll fix that later today.

2022-03-28 07:20 UTC, martinkou commented
Also... for QA. Because the arbitrage strategy now accounts for gas costs when judging whether there're arbitrage opportunities, you'll likely need to increase the order size and the price deltas a bit to get it to trade after this patch.

i.e. previous, you may be able to get it to trade with an other size of 0.001 WETH-DAI and a price delta of 40 DAI. Now you'll likely need to increase the order size to 0.1 WETH-DAI and price delta to 100 DAI to overcome the gas costs.

2022-03-28 07:48 UTC, CrimsonJacket requested changes
Some minor changes requested in `GatewayEVMAMM`. The rest LGTM.

2022-03-28 07:48 UTC, CrimsonJacket commented on hummingbot/connector/gateway_EVM_AMM.py
> +        self._native_currency = "ETH"  # default value only, will be updated in get_chain_info()
I think we should have `self._native_currency` first initialised as `None`. And only upon the successful assigning of a token in `get_chain_info()` would the connector be deems ready.

i.e. in `status_dict` property, we check that `self._native_currency` is assigned.

2022-03-28 07:48 UTC, CrimsonJacket commented on hummingbot/connector/gateway_EVM_AMM.py
> +
I believe we can simply use the `@property.setter` here.

```suggestion
    @network_transaction_fee.setter
    def network_transaction_fee(self, token_amount: TokenAmount):
        """
        Records the last known transaction fees for a trade on the DEX.
        """
        self._last_known_network_transaction_fee = token_amount

```

2022-03-28 07:48 UTC, CrimsonJacket commented on hummingbot/connector/gateway_EVM_AMM.py
> +                self.update_transaction_fees(gas_price_token, gas_cost)
As per the above suggestion wrt using property.setter, we will have to initialise the new `TokenAmount` here.

2022-03-28 07:48 UTC, CrimsonJacket commented on hummingbot/connector/gateway_EVM_AMM.py
> +            self.update_transaction_fees(gas_price_token, gas_cost)
As per the above suggestion wrt using property.setter, we will have to initialise the new `TokenAmount` here.

2022-03-28 15:19 UTC, martinkou commented
Fixed the incorrect gas cost issue at amm_arb start. Addressed review comments.

@james-hummingbot @CrimsonJacket ready for review.

2022-03-28 23:41 UTC, martinkou approved these changes

2022-03-28 23:41 UTC, merged