Better logging for trade failures due to allowed slippage
CoinAlpha/hummingbot pull request #189
Opened 2022-04-04 10:51 UTC by james-hummingbot

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Currently if a gateway connector trade fails because allowed slippage is violated, the user has to read the logs. The solution is to include a message in the console that either a buy or sell slippage limit was violated and suggest that either the market is volatile or their allowed slippage may be too restrictive.

**Tests performed by the developer**:

1. Set amm_arb uniswap kovan allowed slippage to zero.
2. Set gateway uniswap kovan allowed slippage to zero.
3. Set profitability to -100 to force trades
4. Run strategy and see messaging.
<img width="852" alt="Screenshot 2022-04-04 at 12 36 07" src="https://user-images.githubusercontent.com/83538970/161528508-d40c7822-7a35-4806-8bc4-ba716c31bb3f.png">
.

5. Set amm_arb uniswap kovan allowed slippage to 2.0.
6. See succesful trade.

**Tips for QA testing**:

1. Create an amm_arb strategy with a DEX, set allowedSlippage to 0.
2. `gateway config uniswap.versions.2.allowedSlippage 0` or `gateway config pangolin.allowedSlippage 0`.
3. Set profitability low to force trades.
4. You should see a message about the allowed slippage rate in the hummingbot console.

2022-04-04 19:20 UTC, martinkou requested changes

2022-04-04 19:20 UTC, martinkou commented on hummingbot/core/gateway/gateway_http_client.py
> +    swap_price_exceeds_limit_price = 1008
Enum member naming convention is CamelCase.

2022-04-06 02:25 UTC, RC-13 approved these changes
LGTM!
Test summary:
- Install the feature branch and created a gateway instance
- Create an amm_arbitrage strategy using uniswap and pangolin (separate strategy each)
- Set market buffers to 0
- Configure the allowedSlippage to 0 and start the strategies
- Confirmed that a logging message is given in the logs if the trade fails, or if swapping did not push through

2022-04-06 07:26 UTC, martinkou approved these changes

2022-04-06 07:26 UTC, merged