Refactor/Use the US spelling of 'canceled' and 'canceling'
CoinAlpha/hummingbot pull request #196
Opened 2022-04-07 11:09 UTC by mhrvth

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Change everywhere `cancell*` (UK) for `cancel*` (US)

**Tests performed by the developer**:

Ran unit tests

2022-04-07 11:09 UTC, mhrvth commented
[sc-24424]

2022-04-08 05:23 UTC, PtrckM commented
- getting an error while trying use `exit` or Ctrl + C twice or `exit -f` or `stop` command
  - happening on both live and paper

![image](https://user-images.githubusercontent.com/54516858/162368581-d3f09b9e-20a1-43df-beff-371d5e3a7fd0.png)

```
2022-04-08 13:07:16,489 - 19589 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: '_asyncio.Task' object has no attribute 'canceled'
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/cancelled_canceled/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/patrick/Documents/HB/cancelled_canceled/hummingbot/client/command/exit_command.py", line 18, in exit_loop
    if self.strategy_task is not None and not self.strategy_task.canceled():
AttributeError: '_asyncio.Task' object has no attribute 'canceled'

```
[logs_binance_paper.log](https://github.com/CoinAlpha/hummingbot/files/8448722/logs_binance_paper.log)

2022-04-08 07:24 UTC, gerald-hb reviewed
Test Summary

Run tests on Beaxy, Bitfinex, dydx_perpetual, Bitmart, Bittrex, Coinbase Pro, Coinzoom, Crypto.com, Kraken and Liquid

1. Created a simple strategy (Pure market making / Liquidity Mining)
2. Start strategy
3. Stopping the strategy - I can confirm that order were canceled and the canceled is on correct format (US) but I keep getting this error - `AttributeError: '_asyncio.Task' object has no attribute 'canceled'`
 4. Running exit --force and CTRL C+C - This does not cancel order nor stop the bot. The bot continues to create buy and sell order. It only gives same error as below (attaching a screenshot)
 
![image](https://user-images.githubusercontent.com/84826167/162383998-5a363661-0764-440c-9fe9-39a144c93fdc.png)
Attaching sample log
[logs_krakenpmm.log](https://github.com/CoinAlpha/hummingbot/files/8449498/logs_krakenpmm.log)

2022-04-13 06:51 UTC, PtrckM commented
confirmed issue has been fixed!! ✅ 
> * getting an error while trying use `exit` or Ctrl + C twice or `exit -f` or `stop` command
>   
>   * happening on both live and paper


Status: On going test...

2022-04-13 12:27 UTC, RC-13 approved these changes
LGTM

Test summary
- Install and start the feature branch without issue
- Create a perpetual market-making and pure market-making strategy using the connectors with modification.
- Started the strategy and monitor the log pane and confirm that `cancelled` is now in US spelling format.
- Stop the strategy after an order is created and confirm the right format for the cancel message.
- Force exit from the client while an open order or positions are created and restart the strategy. When dangling orders are canceled, the cancel message is showing the right format.
- Test the pause and resume feature and confirmed that when a dangling order is canceled, it shows the right format.

2022-04-13 23:26 UTC, gerald-hb commented
LGTM!

No other issue found related to spelling format.

Test summary

1. Install and start the feature branch without issue
2. Create a perpetual market-making and Spot perpetual strategy using DyDx_Perpetual
3. Stop the strategy after an order is created and confirm the right format for the cancel message.
4. Exit --f cancel open orders and verified that it is on the correct spelling format (from the logs)

2022-04-14 13:32 UTC, aarmoa requested changes

2022-04-14 13:32 UTC, aarmoa commented on hummingbot/connector/exchange/bittrex/bittrex_exchange.pyx
> +                # FILL_OR_KILL, POST_ONLY_GOOD_TIL_CANCELED]
This can't be changed. The correct value according to Bittrex API documentation is `GOOD_TIL_CANCELLED`

2022-04-14 13:32 UTC, aarmoa commented on hummingbot/connector/exchange/bittrex/bittrex_exchange.pyx
> +                "timeInForce": "POST_ONLY_GOOD_TIL_CANCELED"
This can't be changed. The correct value according to Bittrex API documentation is `POST_ONLY_GOOD_TIL_CANCELLED`

2022-04-14 13:32 UTC, aarmoa commented on test/connector/exchange/bittrex/fixture_bittrex.py
> +        "timeInForce": "GOOD_TIL_CANCELED", "fillQuantity": "0.06000000", "commission": "0.01333791",
The change has to be undone also in the tests

2022-04-14 13:32 UTC, aarmoa commented on test/hummingbot/connector/exchange/bittrex/test_bittrex_exchange.py
> +            "timeInForce": "POST_ONLY_GOOD_TIL_CANCELED",
Also please undo the change in this test

2022-04-15 23:00 UTC, gerald-hb commented
LGTM!

No other issue found related to spelling format.

Test summary

1. Clone, Install and start the feature branch without issue
2. Created pure market making and Liquidity mining strategy using Bittrex connector
3. Stop the strategy after an order is created and confirm the right format for the `canceled/canceling` message.
4. Exit --f cancel open orders and verified that it is on the correct spelling format (from the logs)
5. Test the pause and resume feature and confirmed that when order is canceled, it shows the right format.

2022-04-18 12:17 UTC, aarmoa approved these changes
Changes look good to me

2022-04-18 13:24 UTC, mhrvth commented
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5236

2022-04-18 13:24 UTC, closed without merging