Feat/gate io connector update
CoinAlpha/hummingbot pull request #198
Opened 2022-04-07 16:37 UTC by origliante

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2022-04-25 02:34 UTC, RC-13 commented
@origliante I started testing the PR and currently getting the following issues:
1. When running `integration_test_tool.py`, the following error comes up:
```python
(hummingbot) ubuntu@ip-172-31-29-21:~/gate-update$ PYTHONPATH=. python test/connector/integration_test_tool.py
Traceback (most recent call last):
  File "test/connector/integration_test_tool.py", line 18, in <module>
    from certs import creds
ModuleNotFoundError: No module named 'certs'
```
2. When starting a strategy using the Binance connector, the strategy fails to start with the following error in the logs:
```python
2022-04-25 08:16:57,199 - 6630 - hummingbot.connector.exchange_base_v2 - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/clintg/testing/gate/hummingbot/connector/exchange_base_v2.py", line 711, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
AttributeError: 'BinanceExchange' object has no attribute '_status_polling_loop_fetch_updates'
```
3. And if we check the status, it doesn't display the correct base asset balance
![image](https://user-images.githubusercontent.com/57189990/165010570-0b321b1d-7cc2-4108-a504-999be472eeca.png)
![image](https://user-images.githubusercontent.com/57189990/165010599-1febd22f-5af1-4c04-ab6d-e24290d9a4a8.png)
4. Gate_io currently accepts invalid API key
![image](https://user-images.githubusercontent.com/57189990/165010782-aa0a5fba-51d0-4313-8395-4e40b1f04b5a.png)
![image](https://user-images.githubusercontent.com/57189990/165010849-a65c5a85-ee47-46e3-8892-93cec2eb231a.png)
```python
2022-04-25 02:09:42,807 - 24347 - hummingbot.connector.exchange_base_v2 - WARNING - Could not fetch balance update from Gate_io
2022-04-25 02:10:24,792 - 24347 - hummingbot.connector.exchange_base_v2 - NETWORK - Unexpected error while fetching balance update - Error executing request GET spot/accounts. HTTP status is 401. Error: {"label":"INVALID_KEY","message":"Invalid key provided"}
Traceback (most recent call last):
  File "/home/ubuntu/gate-update/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 182, in _update_balances
    account_info = await self._api_get(
  File "/home/ubuntu/gate-update/hummingbot/connector/exchange_base_v2.py", line 766, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/ubuntu/gate-update/hummingbot/connector/exchange_base_v2.py", line 788, in _api_request
    return await self.web_utils.api_request(
  File "/home/ubuntu/gate-update/hummingbot/connector/exchange/gate_io/gate_io_web_utils.py", line 145, in api_request
    raise IOError(
OSError: Error executing request GET spot/accounts. HTTP status is 401. Error: {"label":"INVALID_KEY","message":"Invalid key provided"}
```
[binance-pmm.log](https://github.com/CoinAlpha/hummingbot/files/8551205/binance-pmm.log)

2022-04-25 06:51 UTC, Deepali6997 commented
**gate.io**

1. When pure market making strategy is created and started, it does not starts and says **"Market connectors are not ready yet."** Tried deploying strategy in master branch with same configs and it creates orders successfully without error. 

> PR198 branch


<img width="1728" alt="Screenshot 2022-04-25 at 12 01 23 PM" src="https://user-images.githubusercontent.com/100112937/165032772-d6bbd52d-d893-466c-a2b1-605b1770d747.png">

logs file : [logs_gateio_pmm_PR198.log](https://github.com/CoinAlpha/hummingbot/files/8552132/logs_gateio_pmm_PR198.log)

> MASTER branch


<img width="1728" alt="Screenshot 2022-04-25 at 12 05 44 PM" src="https://user-images.githubusercontent.com/100112937/165033329-59056f9f-e9de-4f53-b44f-a6de3892a8f0.png">

logs file : [logs_gateio_pmm_master.log](https://github.com/CoinAlpha/hummingbot/files/8552161/logs_gateio_pmm_master.log)

csv file : [trades_gateio_pmm_master.csv](https://github.com/CoinAlpha/hummingbot/files/8552158/trades_gateio_pmm_master.csv)



**KUCOIN**

1. When we run config rate_oracle_source_kucoin , the balance command then starts showing zero value for assets and gross balance as zero for KuCoin exchange. In master branch too it is showing same behaviour

>  PR 198 branch


Before running config rate_oracle_source_kucoin 

<img width="494" alt="Screenshot 2022-04-25 at 12 12 22 PM" src="https://user-images.githubusercontent.com/100112937/165034224-3db15379-e2fd-4299-8036-815fc8e32a5d.png">

After running config rate_oracle_source_kucoin ; it starts showing zero allocated and total %

<img width="1728" alt="Screenshot 2022-04-25 at 12 14 06 PM" src="https://user-images.githubusercontent.com/100112937/165034458-0da108d4-b4c0-4f5a-88b9-924ccc33fea6.png">

> MASTER branch

<img width="1728" alt="Screenshot 2022-04-25 at 12 18 23 PM" src="https://user-images.githubusercontent.com/100112937/165035057-e1dc7643-247e-48d8-8589-6401c4a6c4c0.png">

2022-04-25 15:22 UTC, aarmoa requested changes

2022-04-25 15:22 UTC, aarmoa commented on hummingbot/connector/exchange/gate_io/gate_io_utils.py
> +from .gate_io_constants import *  # noqa: F403 F401
This implementation is not clear and can confuse the community. We should keep the utils module as it was (no need to unify it with the constants)

2022-04-25 15:31 UTC, aarmoa commented on hummingbot/connector/exchange_base_v2.py
> +                await self._status_polling_loop_fetch_updates()
`_status_polling_loop_fetch_updates` should be implemented in this class as an abstract method

2022-04-26 11:44 UTC, origliante commented on hummingbot/connector/exchange/binance/binance_exchange.py
> +    DEFAULT_DOMAIN = CONSTANTS.DEFAULT_DOMAIN
If I redefine both _logger and def logger() in the implementation class,
by logging from supported_order_types() - which is in the Base V2, I still get:

INFO	[exchange_base_v2.py]	[supported_order_types] |	test

But all logging from methods that are redefined in the implementation class, log correctly even if I do not redefine anything:

DEBUG	[gate_io_exchange.py]	[_status_polling_loop_fetch_updates] |	Running _status_polling_loop_fetch_updates() at 1650973044.478204

2022-04-26 12:50 UTC, petioptrv commented
[ch22462]

2022-04-27 09:42 UTC, origliante commented
@CoinAlpha/qa-team hey guys pls give it another round, the reported issues should be resolved

2022-04-28 06:22 UTC, Deepali6997 commented
Test Update

- Can confirm that reported issues are all resolved
- There was one issue that was spotted and i.e. **when we're creating a PMM strategy, token trading pairs are not getting auto-populated when typing the trading pair or hitting the tab**

<img width="1728" alt="Screenshot 2022-04-28 at 11 29 12 AM" src="https://user-images.githubusercontent.com/100112937/165686800-626c07a6-f51a-4376-bc7c-2eb002ccd2d7.png">

2022-05-03 05:34 UTC, RC-13 commented
Confirm that the issue with the trading pair not getting displayed is fixed in the latest commit. Although another error comes up whenever a strategy is started  (same error is captured when running the integration_test_tool.py):
![image](https://user-images.githubusercontent.com/57189990/166407780-c08f5634-e3bb-4ddd-93e0-c4cfa106a54d.png)
```python
2022-05-03 05:22:02,763 - 18443 - hummingbot.connector.exchange.gate_io.gate_io_api_order_book_data_source - ERROR - Unexpected error while parsing ws trades message {'time': 1651555322, 'channel': 'spot.trades', 'event': 'subscribe', 'result': {'status': 'success'}}.
Traceback (most recent call last):
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_api_order_book_data_source.py", line 287, in listen_for_trades
    pair: str = await self.trading_pair_associated_to_exchange_symbol(trade_data.get("currency_pair", None))
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_api_order_book_data_source.py", line 172, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/gate/lib/python3.8/site-packages/bidict/_base.py", line 530, in __getitem__
    return self._fwdm[key]
KeyError: None
```
```python
2022-05-03 05:22:02,764 - 18443 - hummingbot.connector.exchange.gate_io.gate_io_api_order_book_data_source - ERROR - Unexpected error while parsing ws order book message {'time': 1651555322, 'channel': 'spot.order_book_update', 'event': 'subscribe', 'result': {'status': 'success'}}.
Traceback (most recent call last):
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_api_order_book_data_source.py", line 327, in listen_for_order_book_diffs
    timestamp: float = (order_book_data["t"]) * 1e-3
KeyError: 't'
```
```python
2022-05-03 05:22:03,054 - 18443 - hummingbot.connector.exchange_py_base - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 300, in _user_stream_event_listener
    self._process_order_message(order_msg)
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 352, in _process_order_message
    client_order_id = str(order_msg.get("text", ""))
AttributeError: 'str' object has no attribute 'get'
```
```python
2022-05-03 05:22:08,056 - 18443 - hummingbot.connector.exchange_py_base - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 297, in _user_stream_event_listener
    self._process_trade_message(trade_msg)
  File "/home/ubuntu/gate/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 377, in _process_trade_message
    client_order_id = client_order_id or str(trade["text"])
TypeError: string indices must be integers
```
Despite getting the error, the strategy continue to work as expected.
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/8608379/logs_conf_pure_mm_1.log)

2022-05-03 23:09 UTC, gerald-hb commented
Latest commit looks good to me. I can confirm that the previous error no longer occurs.

Test summary.
1. clone and install the featured branch :white_check_mark:
2. Add API keys and check out balance command :white_check_mark:
3. Create pure market making strategy, check status/--live :white_check_mark:
4. Buy and sell orders were created and canceled accordingly :white_check_mark:
5. Cross check trading fees in history, orderbook and .csv file (data folder).  :white_check_mark:

2022-05-05 16:17 UTC, aarmoa commented
Hello @CoinAlpha/qa-team. All refactorings have been applied to the PR. Could you perform a quick test again for the connectors (Binance, Kucoin, Gateio)?

2022-05-05 18:15 UTC, Deepali6997 commented
test update for Kucoin connector

1. Cloning and installation of feature branch and checking behaviour for API incorrect and correct credentials
2. Creation of strategy and checking status --live, ticker --live, orderbook --live, history and history --verbose commands
3. Checking the strategy for fully filled, partially filled orders and fee calculation
4. Checking filled orders in datadog under graph (hummingbot.filled_usdt_volume)
5. Checking slow and fast refresh rate 
6. Checking for multiple bots and checking the hangingorder behavior

Can confirm the above mentioned points are working fine.

will update soon for other two connectors Binance and gate.io

2022-05-06 00:54 UTC, gerald-hb commented
Run the remaining test for gate and Binance. Changes looks good to me. 

Test summary

1.clone and install the featured branch ✅
2.Add API keys and check out balance command ✅
3.Create pure market making strategy, check status/--live, ticker --live, orderbook --live, history and history --verbose commands ✅
4.Buy and sell orders were created and canceled accordingly ✅
5.Checking slow and fast refresh rate✅
5.Cross check trading fees in history, orderbook and .csv file (data folder). ✅

2022-05-08 22:52 UTC, RC-13 approved these changes
Tested and confirmed working, LGTM!

Test summary:
- Install and start the feature branch without any issue
- Connect Binance, Gate_io, and KuCoin API key. Gate_io did have an issue with accepting invalid API keys which had been fixed within the commits.
- Checked the balance and successfully returns and displays accurate balance in each exchange.
- Created different pure market-making strategies using Binance, Gate_io, and KuCoin as exchanges. A minor issue was seen during the strategy creation specific to Gate_io which has been sorted within the commits.
- Started the strategy, initially, errors occurred when starting any strategy which was confirmed fixed in the latest commit.
- Confirmed that the order creation and cancellation follow the specified parameter set in the strategy.
- Stopped and restarted the strategy multiple times to verify that orders are properly getting canceled.
- Tested on different refresh rates to confirm that there are no orders left out in the exchange.
- Filled orders are confirmed and recorded correctly and fees match the fee record in the exchange.
- Checked the orders and prices to make sure that they are synchronized with the exchange.
- Run multiple bots using the same exchange and market to confirm that there are no orderID conflicts.
- Add the API key by creating a python file and testing the integration_test_tool.py. Confirms that the tool is running and capturing issues if there are any.

2022-05-11 16:30 UTC, petioptrv requested changes
I like the changes. The new code is very clean, and it simplifies new implementations quite a bit. I've left some comments in the code.

One general comment that I have is that I don't see the need to make the interface abstract through private versions of the interface functions. I think the interface function itself should be marked as abstract. That way, it is immediately apparent to the implementer that this is something they should define, rather than having to follow the function calls to the private function that is finally abstract. Also, very very minor, but this removes the overhead of yet another function call.

Also, there are many methods that raise `NotImplementedError`, but are not marked as abstract. To be "pythonic", we should mark those with `@abstractmethod` decorator, and have them `pass` instead. Like:
```Python
class MyABCClass(ABC):
    @abstractmethod
    def my_abc_method(self):
        pass
```
Only if we inherit from `ABC` and decorate with`abstractmethod` will Python raise when the abstract methods are not implemented on class non-abstract class definition. Also, if both of those conditions are met, then the body of the function has no effect.

2022-05-11 18:12 UTC, aarmoa commented on hummingbot/client/command/start_command.py
> +from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional
I thought that isort was executed automatically now before any commit

2022-05-11 18:18 UTC, aarmoa commented on hummingbot/connector/exchange_py_base.py
> +class ExchangePyBase(ExchangeBase):
I tried this but is not possible. Everything breaks if you try to use multiple inheritance in a class that inherits from a Cython class.

2022-05-12 05:34 UTC, petioptrv commented on hummingbot/client/command/start_command.py
> +from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional
It does, and it currently fails on the pipeline. My guess is that those changes were pushed before isort was merged into dev. Or maybe pre-commit is not installed locally

2022-05-12 09:58 UTC, petioptrv commented on hummingbot/connector/exchange_py_base.py
> +class ExchangePyBase(ExchangeBase):
I may be missing something, but this minimal example works on my end:
```Python
    def test(self):
        pass


class TestImpl(Test):
    def test(self):
        print("test")


if __name__ == '__main__':
    try:
        t = Test()
    except TypeError as e:
        print(e)

    t = TestImpl()
    t.test()
```

2022-05-12 13:46 UTC, aarmoa commented on hummingbot/client/command/start_command.py
> +from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional
Applying the change in the next commit

2022-05-12 13:49 UTC, aarmoa commented on test/connector/integration_test_tool.py
> +        # ENABLE_CONNECTION_TRACING = True
Removing the comment in the next commit

2022-05-12 13:49 UTC, aarmoa commented on test/connector/integration_test_tool.py
> +                # await UserBalances.instance().add_exchange(self.exchange.name, **api_keys)
Removing the commented print in the next commit

2022-05-12 13:50 UTC, aarmoa commented on test/connector/integration_test_tool.py
> +        # self.exchange = get_binance(self)
Removing the comment in the next commit

2022-05-12 13:51 UTC, aarmoa commented on test/connector/integration_test_tool.py
> +    # }
Removing the comment in the next commit

2022-05-12 13:51 UTC, aarmoa commented on test/connector/integration_test_tool.py
> +    # }
Removing the comment in the next commit

2022-05-12 13:53 UTC, aarmoa commented on test/connector/integration_test_tool.py
> +# from hummingbot.user.user_balances import UserBalances
Removing the comment in the next commit

2022-05-12 13:55 UTC, aarmoa commented on hummingbot/connector/exchange/kucoin/kucoin_exchange.py
> +    web_utils = web_utils
I am planning on changing the web_utils reference in the OKX PR, when both changes are merged together. I don't think it is a good idea to work on reifying the utilities concept as part of this PR.

2022-05-12 13:58 UTC, aarmoa commented on hummingbot/connector/exchange/gate_io/gate_io_web_utils.py
> +class GateIoWebsocket:
Removing the class in the next commit

2022-05-13 06:38 UTC, petioptrv approved these changes
The changes LGTM!

2022-05-15 21:11 UTC, aarmoa commented
Closing this PR after creating its equal in the foundation repository (https://github.com/hummingbot/hummingbot/pull/5313)

2022-05-15 21:11 UTC, closed without merging