feat/update okx connector
CoinAlpha/hummingbot pull request #211
Opened 2022-04-19 03:56 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Refactoring of order book and user stream data source classes to move common code to the super class. The refactoring was applied to Binance, Kucoin and OKX connectors.

**Tests performed by the developer**:

**Tips for QA testing**:

2022-04-19 04:00 UTC, aarmoa commented
This PR applies a refactoring that impacts Binance spot and Kucoin connectors too. @CoinAlpha/qa-team you can start testing those connectors. For OKX please wait until all changes are done.

2022-04-19 11:02 UTC, Deepali6997 commented
KUCOIN CONNECTOR

1. When wrong api key and wrong api secret key is added; we get the following errors:-
<img width="1094" alt="Screenshot 2022-04-19 at 4 25 37 PM" src="https://user-images.githubusercontent.com/100112937/163988967-953b07c7-5373-4c51-8b0d-80821f76c4c5.png">

2. While creating the strategy, trading pairs do not get auto-populated when hitting TAB.

<img width="1085" alt="Screenshot 2022-04-19 at 4 26 08 PM" src="https://user-images.githubusercontent.com/100112937/163989031-320e0969-c893-4b8a-956d-6bef6c39fe8a.png">

3. When strategy is imported and START command is given; the strategy does not starts on its own
<img width="1086" alt="Screenshot 2022-04-19 at 4 26 33 PM" src="https://user-images.githubusercontent.com/100112937/163989096-84a5a90e-40ab-464d-94c7-1e2e6c21c1a0.png">

<img width="1093" alt="Screenshot 2022-04-19 at 4 27 24 PM" src="https://user-images.githubusercontent.com/100112937/163989216-c872c956-fc2f-446c-8333-093dbeb2d9e9.png">

[logs_pmm2.log](https://github.com/CoinAlpha/hummingbot/files/8512343/logs_pmm2.log)



OKEX 

1. Even after giving correct api key details, we see an error. 


<img width="1088" alt="Screenshot 2022-04-19 at 4 28 34 PM" src="https://user-images.githubusercontent.com/100112937/163989359-e78d93cc-dbb2-4225-8134-993d8473a321.png">

<img width="1092" alt="Screenshot 2022-04-19 at 4 28 52 PM" src="https://user-images.githubusercontent.com/100112937/163989409-4321f309-73c6-425b-9267-006640ff46d4.png">

2. When giving wrong api details, we see following errors

<img width="1068" alt="Screenshot 2022-04-19 at 4 29 38 PM" src="https://user-images.githubusercontent.com/100112937/163989498-84c82d68-c3c1-4431-a46d-15d2a82f9abd.png">
<img width="1728" alt="Screenshot 2022-04-19 at 4 29 45 PM" src="https://user-images.githubusercontent.com/100112937/163989511-c4f5d7e8-115d-423a-be26-3bdb052cf108.png">

2022-04-20 06:43 UTC, gerald-hb commented
Getting this error upon starting a strategy (happens 90% of the time)
![image](https://user-images.githubusercontent.com/84826167/164162677-62201240-2e61-4516-bbe4-055dc00f5556.png)
Tested with another pair
![image](https://user-images.githubusercontent.com/84826167/164166588-31ca1086-9f92-420a-aef4-73f64dac3406.png)


Steps to Reproduce
1. Clone and install this branch `feat/update_okx_connector` 
2. Create a regular PMM (config below)
![image](https://user-images.githubusercontent.com/84826167/164162980-a02eb6c6-0a72-4f80-b4ce-35414625a37f.png)
3. The error above is intermittent (happens 90% of the time) Sometimes if I will change bid/ask spread and order amount, it will suddenly work. 
Logs - 
[logs_binancepmm.log](https://github.com/CoinAlpha/hummingbot/files/8518843/logs_binancepmm.log)

There is another behavior I particularly notice on Liquidity Mining Strategy

Steps to reproduce
1. Clone and install this branch `feat/update_okx_connector` 
2. Create Liquidity Mining strategy.
![image](https://user-images.githubusercontent.com/84826167/164164745-5243aa60-433e-4077-b507-f3a2ad2b9e85.png)
3. This error appears randomly
`2022-04-20 14:02:52,830 - 5973 - hummingbot.connector.parrot - ERROR - Unexpected error while requesting data from Hummingbot API.
Traceback (most recent call last):
  File "/home/geraldhb/pr211/hummingbot/connector/parrot.py", line 35, in get_campaign_summary
    campaigns = await get_active_campaigns(exchange, trading_pairs)
  File "/home/geraldhb/pr211/hummingbot/connector/parrot.py", line 71, in get_active_campaigns
    resp_json = await resp.json()
  File "/home/geraldhb/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://papi.hummingbot.io/v1/mining_data/campaigns')
logs -`

[logs_binanceregtestlmst.log](https://github.com/CoinAlpha/hummingbot/files/8518872/logs_binanceregtestlmst.log)
 
Some of the functionality is also not working
1 Prompt which strategy to create and shows autocomplete list when the tab or space key is press or the initial letter of the strategy is entered. : not ok, nothing happens when you press space nor tab upon creating of strategy
2 List of the available connector should be listed when the tab or space key is press: not ok, nothing happens when you press space or tab on the connector prompt
3 List of the available markets should be listed when the tab or space key is press: not ok, nothing is listed when you press tab/space on the markets prompt

2022-04-20 09:52 UTC, Deepali6997 commented
In Kucoin 

1. When we're starting the strategy we can see that it just stays on the following screen "Market connectors are not ready" as a result the strategy does not starts. Attaching the log for the same. 
[logs_puremarketmaking_kucoin.log](https://github.com/CoinAlpha/hummingbot/files/8520302/logs_puremarketmaking_kucoin.log)

<img width="1728" alt="Screenshot 2022-04-20 at 3 07 15 PM" src="https://user-images.githubusercontent.com/100112937/164199098-27469758-d9b5-4a8b-9e09-58d5f4b5f63c.png">

Also, what is worth noting that the strategy with same configs is working fine in Dev branch and master branch

Dev branch
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/8520322/logs_conf_pure_mm_1.log)

[trades_conf_pure_mm_1.csv](https://github.com/CoinAlpha/hummingbot/files/8520318/trades_conf_pure_mm_1.csv)

<img width="1728" alt="Screenshot 2022-04-20 at 3 09 26 PM" src="https://user-images.githubusercontent.com/100112937/164199501-ce375bdd-22f6-46d5-aa41-f03a7bc14b74.png">

master branch
[logs_kucoin_master_pmm.log](https://github.com/CoinAlpha/hummingbot/files/8520371/logs_kucoin_master_pmm.log)

[trades_kucoin_master_pmm.csv](https://github.com/CoinAlpha/hummingbot/files/8520375/trades_kucoin_master_pmm.csv)


<img width="1728" alt="Screenshot 2022-04-20 at 3 12 54 PM" src="https://user-images.githubusercontent.com/100112937/164200194-d33a5b21-cc01-46c8-a626-b925de2c0d81.png">



<img width="1728" alt="Screenshot 2022-04-20 at 3 15 58 PM" src="https://user-images.githubusercontent.com/100112937/164200746-7a1a0d89-477d-43d2-bd57-47e3e438231c.png">

**Giving incorrect credentials in development branch**

1. When we're giving incorrect credentials in dev branch, we can see that error message is different from what we see in the Master branch and PR211 branch (feat/update_okx_connector)

Below image is showing the error message we see in dev branch
<img width="1566" alt="Screenshot 2022-04-20 at 3 19 01 PM" src="https://user-images.githubusercontent.com/100112937/164201331-2079902d-132d-4df9-b886-4bddf713616a.png">

Below image is showing the error message we see in feat/update_okx_connector branch
<img width="1575" alt="Screenshot 2022-04-20 at 3 19 19 PM" src="https://user-images.githubusercontent.com/100112937/164201393-b2b68a66-9a30-468a-8248-fb5afa2ec6e2.png">


Below image is showing the error message we see in MASTER branch
<img width="1577" alt="Screenshot 2022-04-20 at 3 19 41 PM" src="https://user-images.githubusercontent.com/100112937/164201456-d9d4b10e-672c-47e9-977b-47bd98f92f49.png">

2022-04-20 11:43 UTC, RC-13 commented
Issue summary:
KuCoin fails to start and stuck in `the market connector are not ready` state, no additional info given in the logs:
![image](https://user-images.githubusercontent.com/57189990/164221433-aa6f4366-93e4-4e44-8462-bd30dfd9bba1.png)

the rest of the issues mentioned are not bugs, some are expected results and some are results of an incorrect configuration or an existing issue within the strategy.

2022-04-21 05:53 UTC, gerald-hb commented
No major error found for Binance and Kucoin

Test performed
1. Cloned and installed featured branch : ok
2. Create simple pure market making strategy using Binance and Kucoin connector
3. Performed the following test runs
  a. Confirmed that Balance output is working
  b. Confirmed that bot is placing and cancelling orders accordingly
  c. Confirmed that filled trades are recorded and in sync with the exchange
  d. Trading fees are correct

2022-04-21 12:05 UTC, aarmoa commented
Thank you all @CoinAlpha/qa-team. I will post a comment again as soon as it is possible to start testing OKX connector.

2022-04-27 18:53 UTC, aarmoa commented
Hi @CoinAlpha/qa-team. I have made some new refactorings. If possible please check again Binance and Kucoin connectors. Also verify if Binance Paper Trade is working correctly

2022-04-28 00:01 UTC, gerald-hb commented
Found some issues particularly in Kucoin

1. No confirmation of API keys being connected/invalid. Only stay like this
![image](https://user-images.githubusercontent.com/84826167/165648938-2f662308-555d-4575-9dd5-f7d74e041411.png)

2. Balance and Connect command never loads. I also test this in master branch and it worked fine.
![image](https://user-images.githubusercontent.com/84826167/165649061-5aaeaab3-548d-44c2-a554-68ebbe558a18.png)
![image](https://user-images.githubusercontent.com/84826167/165649106-94feb4ff-a53c-45e0-994e-14f54b58b828.png)

3. Tried to start PMM on Kucoin paper trade and got this error (logs)
```2022-04-27 23:48:45,194 - 7141 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/ubuntu/pr211/hummingbot/connector/exchange/paper_trade/__init__.py", line 12, in get_order_book_tracker
    connector_instance = conn_setting.non_trading_connector_instance_with_default_configuration(
  File "/home/ubuntu/pr211/hummingbot/client/settings.py", line 196, in non_trading_connector_instance_with_default_configuration
    connector = connector_class(**args)
  File "/home/ubuntu/pr211/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 91, in __init__
    data_source=KucoinAPIUserStreamDataSource(
TypeError: __init__() got an unexpected keyword argument 'auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/pr211/hummingbot/strategy/pure_market_making/start.py", line 89, in start
    self._initialize_markets(market_names)
  File "/home/ubuntu/pr211/hummingbot/client/hummingbot_application.py", line 266, in _initialize_markets
    connector = create_paper_trade_market(conn_setting.parent_name, trading_pairs)
  File "/home/ubuntu/pr211/hummingbot/connector/exchange/paper_trade/__init__.py", line 20, in create_paper_trade_market
    tracker = get_order_book_tracker(connector_name=exchange_name, trading_pairs=trading_pairs)
  File "/home/ubuntu/pr211/hummingbot/connector/exchange/paper_trade/__init__.py", line 16, in get_order_book_tracker
    raise Exception(f"Connector {connector_name} OrderBookTracker class not found ({exception})")
Exception: Connector kucoin OrderBookTracker class not found (__init__() got an unexpected keyword argument 'auth')
2022-04-27 23:48:45,196 - 7141 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-04-27 23:48:46,907 - 7141 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
```
4. Creating strategy using Kucoin doesn't complete preliminary checks. No error message.
![image](https://user-images.githubusercontent.com/84826167/165649652-6e0939f9-f873-45e8-a08b-80d3e4061b82.png)

For Binance, everything looks fine except for the `Balance` and `Connect` output, it doesn't load either.
Test Summary for Binance
1. Installed featured branch
2. Connect Binance API keys and created a strategy
3. Confirmed that bot is placing and cancelling orders accordingly
4. Confirmed that filled trades are recorded and in sync with the exchange
5. Trading fees are correct
6. Run the same test on Binance_Paper_trade - bot is placing and cancelling orders accordingly

2022-04-28 13:54 UTC, aarmoa commented
Hi @gerald-hb. Thank you for the details. The issue should be fixed now.

2022-04-29 00:49 UTC, gerald-hb commented
Changes looks good to me.

Test Summary for Binance and Kucoin

1. Installed featured branch :white_check_mark:
2. Confirmed that API were able to connect and gives an error message for invalid inputs. :white_check_mark:
3. Connect and Balance command shows result :white_check_mark:
4. Confirmed that bot is placing and cancelling orders accordingly :white_check_mark:
5. Confirmed that filled trades are recorded and in sync with the exchange :white_check_mark:
6. Trading fees are correct :white_check_mark:
7. Paper trade works as expected. :white_check_mark:

2022-05-14 06:56 UTC, gerald-hb commented
Latest changes looks good to me.

Test Summary for Binance and Kucoin (including paper trade)

-Installed featured branch ✅
-Confirmed that API were able to connect and gives an error message for invalid inputs. ✅
-Connect and Balance command shows result ✅
-run status --live, ticker --live and order_book --live ✅
-Confirmed that bot is placing and cancelling orders accordingly ✅
-Tested with low and high refresh rate✅
-Confirmed that filled trades are recorded and in sync with the exchange ✅
-Trading fees are correct ✅
-Hanging orders working as expected✅
-Paper trade works as expected. ✅

2022-05-15 20:57 UTC, aarmoa commented
Hello @CoinAlpha/qa-team. This PR can be tested again. The logic on the following connectors was affected and should be checked:
- Binance spot
- Kucoin
- GateIO
- OKX

2022-05-16 04:51 UTC, RC-13 commented
Re-tested the PR and got the following issues:
- OKX API connection always fail even if you provide a correct OKX API key
![okx-connect](https://user-images.githubusercontent.com/57189990/168521825-3147eef1-d5d7-4454-8814-9db0408b8b62.png)

- Fail to track orders when using gate_io connector, in the client, it was mentioned that the order failed however it is submitted in the exchange.
```python
2022-05-16 12:36:23,096 - 17946 - hummingbot.connector.exchange.gate_io.gate_io_exchange.GateIoExchange - NETWORK - Error submitting buy LIMIT order to Gate_io for 0.0055 ETH-USDT 2051.47.
Traceback (most recent call last):
  File "/Users/clintg/testing/okx/hummingbot/connector/exchange_py_base.py", line 449, in _create_order
    exchange_order_id, update_timestamp = await self._place_order(
  File "/Users/clintg/testing/okx/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 185, in _place_order
    order_result = await self._api_post(
  File "/Users/clintg/testing/okx/hummingbot/connector/exchange_py_base.py", line 786, in _api_post
    return await self._api_request(*args, **kwargs)
  File "/Users/clintg/testing/okx/hummingbot/connector/exchange_py_base.py", line 810, in _api_request
    return await rest_assistant.execute_request(
  File "/Users/clintg/testing/okx/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.gateio.ws/api/v4/spot/orders. HTTP status is 201. Error: {"id":"156961975499","text":"t-HBOTBEHUT180cb27295d65b2ac0a","create_time":"1652675783","update_time":"1652675783","create_time_ms":1652675783159,"update_time_ms":1652675783159,"status":"open","currency_pair":"ETH_USDT","type":"limit","account":"spot","side":"buy","amount":"0.0055","price":"2051.47","time_in_force":"gtc","iceberg":"0","left":"0.0055","fill_price":"0","filled_total":"0","fee":"0","fee_currency":"ETH","point_fee":"0","gt_fee":"0","gt_discount":true,"rebated_fee":"0","rebated_fee_currency":"USDT"}
```

https://user-images.githubusercontent.com/57189990/168521601-2a79746f-2d20-4933-b6b9-6f60974687d0.mov


[logs_gate.log](https://github.com/CoinAlpha/hummingbot/files/8697226/logs_gate.log)

2022-05-16 11:27 UTC, Deepali6997 commented
Re-tested the following connectors

BINANCE and KUCOIN

- Installed feature branch successfully
- Confirmed the behaviour when correct and incorrect API keys are given
- Created, imported and started the strategy
- Can confirm status --live, orderbook --live, ticker --live, history --verbose and history command working as expected
- Can confirm .csv file giving results accurately (Broker ID, fees calculation and other details. Cross verified with running history --verbose command)
- Can confirm Datadog is able to get correct data from the client (order filled events)
- Fast/slow refresh rate is handled smoothly
- Can confirm same behaviour on testing over other trading pairs and multiple bots trading
- Can confirm hanging orders creation is working fine
- Can confirm when hanging order is interrupted, the hanging order gets cancelled
- Can confirm hanging order cancel pct is also working as expected

2022-05-17 01:25 UTC, RC-13 commented
- Confirming that the issue reported with OKX API key has been addressed in the latest commit.
- OKX randomly gets the following message, despite getting the message, the orders are canceled properly.
![okx-status-update](https://user-images.githubusercontent.com/57189990/168707854-4c3d8a3d-d4fe-426f-a951-20e3545c3639.png)
```python
2022-05-17 09:18:00,396 - 17044 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error fetching order fills for the order 93027a12dac34fBCBEHUT180cf97839b: Error executing request GET https://www.okx.com/api/v5/trade/fills. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}.
2022-05-17 09:18:00,397 - 17044 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch status update for the order 93027a12dac34fBCBEHUT180cf97839b.
```
[logs_okx.log](https://github.com/CoinAlpha/hummingbot/files/8704381/logs_okx.log)

2022-05-17 11:42 UTC, Deepali6997 commented
Gate_io connector update

Re-run the test on latest commit, still getting the same error in gate_io as flagged by Clinton yesterday.

2022-05-17 11:44 UTC, RC-13 commented
> Gate_io connector update
> 
> Re-run the test on latest commit, still getting the same error in gate_io as flagged by Clinton yesterday.

@Deepali6997 https://hummingbot-io.slack.com/archives/C02PTF8S8UC/p1652745442711799

2022-05-19 09:23 UTC, Deepali6997 commented
Tested Gate_io connector. LGTM!

- Installed feature branch successfully
- Confirmed the behaviour when correct and incorrect API keys are given
- Created, imported and started the strategy
- Can confirm status --live, orderbook --live, ticker --live, history --verbose and history command working as expected
- Can confirm .csv file giving results accurately (Broker ID, fees calculation and other details. Cross verified with running history --verbose command and checking it on exchange as well)
- Can confirm Datadog is able to get correct data from the client (order filled events)
- Fast/slow refresh rate is handled smoothly
- Can confirm same behaviour on testing over other trading pairs and multiple bots trading
- Can confirm hanging orders creation, hanging order is interruption and hanging order cancel pc is working fine

2022-05-19 10:15 UTC, Deepali6997 approved these changes
Tested and confirmed working by QA.

All the four connectors under testing namely : Binance, gate_io, KuCoin, OkEx are working fine. 

Test Summary:
- Installed feature branch 
- Confirming that connection is successful when right credentials are given and throws error when wrong credentials are given
- Created, imported and started the PMM strategy, 
- Can confirm status --live, orderbook --live, ticker --live, history --verbose and history command working as expected
- Can confirm .csv file giving results accurately (Broker ID, fees calculation and other details. Cross verified with running history --verbose command)
- Can confirm Datadog is able to get correct data from the client (order filled events)
- Fast/slow refresh rate is handled smoothly
- Can confirm same behaviour on testing over other trading pairs and multiple bots trading
- Can confirm hanging orders creation, hanging order is interruption and hanging order cancel pc is working fine

2022-05-20 12:22 UTC, Deepali6997 commented
still LGTM!

2022-05-30 11:12 UTC, mhrvth requested changes

2022-05-31 03:59 UTC, aarmoa commented on hummingbot/connector/exchange/binance/binance_auth.py
> +            request.data = self.add_auth_to_params(params=json.loads(request.data))
No need to do that: the request was created by the connector and the data was serialied to JSON string just before this method is executed.

2022-05-31 04:01 UTC, aarmoa commented on hummingbot/connector/exchange/gate_io/gate_io_api_order_book_data_source.py
> +            "trade_type": (float(TradeType.SELL.value)
Just for consistency: in every other place where this is done float is used (and it is the expected type in the message class)

2022-05-31 04:02 UTC, aarmoa commented on hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py
> +        timestamp: float = int(trade_data["time"]) * 1e-9
`trade_data` provides an int in "time". It becomes a float when dividing it by 1000000000

2022-05-31 04:03 UTC, aarmoa commented on hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py
> +            "trade_type": float(TradeType.BUY.value) if trade_data["side"] == "buy" else float(
I used float for consistency: in all other places where the same logic is used, a float number is passed.

2022-05-31 04:06 UTC, aarmoa commented on hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py
> +        self._ping_interval = int(int(connection_info["data"]["instanceServers"][0]["pingInterval"]) * 0.8 * 1e-3)
Applying the change in the next commit

2022-05-31 04:06 UTC, aarmoa commented on hummingbot/connector/exchange/kucoin/kucoin_api_user_stream_data_source.py
> +        self._ping_interval = int(int(connection_info["data"]["instanceServers"][0]["pingInterval"]) * 0.8 * 1e-3)
Applying the change in the next commit

2022-05-31 04:07 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_api_order_book_data_source.py
> +        snapshot_timestamp: float = int(snapshot_data["ts"]) * 1e-3
But the field "ts" in snapshot_data does include an int according to the documentation. It then becomes a float for us when dividing by 1000

2022-05-31 04:11 UTC, aarmoa commented on hummingbot/client/command/__init__.py
> +    PreviousCommand
Changing the order in the next commit

2022-05-31 04:13 UTC, aarmoa commented on hummingbot/client/command/previous_strategy_command.py
> +        file_name,
Adding the type hint in the next commit

2022-05-31 04:15 UTC, aarmoa commented on hummingbot/client/command/previous_strategy_command.py
> +        input_value=None,
Adding the type hint in the next commit

2022-05-31 04:16 UTC, aarmoa commented on hummingbot/connector/exchange/binance/binance_auth.py
> +            request.data = self.add_auth_to_params(params=json.loads(request.data))
If the string can't be parsed the `load` method will rise an exception

2022-05-31 04:16 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_api_order_book_data_source.py
> +                "trade_type": float(TradeType.BUY.value) if trade_data["side"] == "buy" else float(
Also done this way for consistency

2022-05-31 04:17 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_api_order_book_data_source.py
> +                timestamp=(int(trade_data["ts"]) * 1e-3))
"ts" field has an int according to the documentation.

2022-05-31 04:17 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_api_order_book_data_source.py
> +            timestamp: float = int(diff_data["ts"]) * 1e-3
"ts" field has an int according to the documentation.

2022-05-31 04:18 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_auth.py
> +        :param request: the request to be configured for authenticated interaction
Adding the missing documentation in the next commit

2022-05-31 04:19 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_exchange.py
> +                                    fill_timestamp=int(data["uTime"]) * 1e-3,
The "uTime" field has an int according to the documentation

2022-05-31 04:19 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_exchange.py
> +                                update_timestamp=int(data["uTime"]) * 1e-3,
The "uTime" field has an int according to the documentation

2022-05-31 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_web_utils.py
> +    server_time = int(response["data"][0]["ts"])
Changing the type cast in the next commit

2022-05-31 04:23 UTC, aarmoa commented on hummingbot/core/data_type/order_book_tracker_data_source.py
> +        Creates an instance of WSAssistant connected to the exchange
Adding the missing return in the next commit

2022-05-31 04:23 UTC, aarmoa commented on hummingbot/core/data_type/order_book_tracker_data_source.py
> +
Adding it in the next commit

2022-05-31 04:24 UTC, aarmoa commented on hummingbot/core/data_type/order_book_tracker_data_source.py
>          """
It is not missing. Since the method is private it has no docstring.

2022-05-31 04:25 UTC, aarmoa commented on hummingbot/core/data_type/order_book_tracker_data_source.py
>      async def _sleep(self, delay):
Adding it in the next commit

2022-05-31 04:26 UTC, aarmoa commented on hummingbot/core/data_type/user_stream_tracker_data_source.py
> +        Creates an instance of WSAssistant connected to the exchange
Adding it in the next commit

2022-05-31 04:28 UTC, aarmoa commented on hummingbot/core/data_type/user_stream_tracker_data_source.py
>      async def _sleep(self, delay):
Adding the type hint in the next commit

2022-05-31 04:29 UTC, aarmoa commented on hummingbot/core/gateway/status_monitor.py
> +    async def wait_for_online_status(self, max_tries=30):
Adding it in the next commit

2022-05-31 04:31 UTC, aarmoa commented on hummingbot/core/web_assistant/connections/data_types.py
>  import aiohttp
isort is forcing the sort

2022-05-31 04:31 UTC, aarmoa commented on test/hummingbot/connector/exchange/binance/test_binance_exchange.py
>  from aioresponses import aioresponses
Fixing it in the next commit

2022-05-31 04:32 UTC, aarmoa commented on test/hummingbot/connector/exchange/bitmart/test_bitmart_exchange.py
>  from aioresponses import aioresponses
Fixing the order in the next commit

2022-05-31 08:06 UTC, Deepali6997 commented
Had a quick re-test for following connectors (Binance, KuCoin, Gate_io and OkEx)

- Trading pairs are not getting auto-populated when TAB button is hit

PFB image for Binance connector. 
The issue is spotted in KuCoin, Gate_io and Okex as well

<img width="838" alt="Screenshot 2022-05-31 at 1 34 07 PM" src="https://user-images.githubusercontent.com/100112937/171123841-2c0edfad-f4d3-4862-a53f-e5d0d9e0609a.png">

2022-05-31 10:49 UTC, mhrvth commented on hummingbot/core/web_assistant/connections/data_types.py
>  import aiohttp
For me `isort -m=3 -l=120 test.py` is putting constants like `TYPE_CHECKING` first

2022-05-31 16:43 UTC, mhrvth approved these changes

2022-06-01 03:48 UTC, RC-13 commented
Confirming that the last reported issue has been addressed and re-tested the three connectors with no issue found. However, there seems to be an issue with creating a docker instance, after building the image and creating the instance. The following error is  given:
```python
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 143, in <module>
    fork_and_start(main)
  File "/home/hummingbot/bin/docker_connection.py", line 137, in fork_and_start
    main_function()
  File "bin/hummingbot_quickstart.py", line 136, in main
    if not login_prompt():
TypeError: login_prompt() missing 1 required positional argument: 'style'
```

2022-06-01 04:22 UTC, aarmoa commented
@RC-13 please check if that last error is not happening in the development branch too. @Petio has already prepared a fix for an issue that seem identical to this, but is not related with this PR at all (https://github.com/CoinAlpha/hummingbot/pull/247)

2022-06-01 05:20 UTC, RC-13 commented
Sorry about that @aarmoa we just confirmed that the docker error is related to the issue found by Petio and was able to create the image after applying his fix.

2022-06-01 05:23 UTC, RC-13 approved these changes
LGTM! Confirming the last reported issue has been addressed.

Test summary:
- Connect Binance, Gate_io, and OKX ( use valid and invalid API keys) and confirm correct response is shown in the client.
- Check the connector table and confirmed that the right status is displayed, also run the balance command and successfully show each exchange's current balance.
- Create a PMM strategy - Tested on Binance, Gate_io, and OKX
        * Market auto complete - Binance: Ok
        * Market auto complete - Gate_io:
        * Market auto-complete - OKX: Ok
- Start the strategy and run status —live
- Order cancelation and creation: OK
          * Cancel one of the orders created by the bot in the exchange: Ok
          * Manually create an order in the exchange and cancel: Did not affect the bot, Ok
- Data integrity ( best price, order book, and last price)
        * Binance: Ok
        * Gate_io: Ok
        * OKX: Ok
-  Filled event: Ok
-  Check history: OK
- Verify fees paid: Ok
- Test fast and long refresh rate: Ok
-  Test multiple levels: OK
-  Build a docker image and create a docker instance
- Connect Binance, Gate_io, and OKX API keys
- Run a basic PMM for each of the connectors (Binance, Gate_io, and OKX)

2022-06-02 15:13 UTC, aarmoa commented
Closing this PR after creating an equivalent one in the foundation repo https://github.com/hummingbot/hummingbot/pull/5368

2022-06-02 15:13 UTC, closed without merging