Feat/Update CoinAlpha connectors fees schema
CoinAlpha/hummingbot pull request #214
Opened 2022-04-20 09:51 UTC by mhrvth

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Replacement of a legacy definition of trade fee schemas with `TradeFeeSchema` in connectors maintained by CoinAlpha

**Tests performed by the developer**:

Ran unit tests

2022-04-20 09:51 UTC, mhrvth commented
[sc-23435]

2022-04-20 12:33 UTC, petioptrv requested changes

2022-04-20 12:33 UTC, petioptrv commented on hummingbot/connector/exchange/okex/okex_utils.py
> +    taker_percent_fee_decimal=Decimal("0.0015"),
Looks like these have changed too: https://www.okx.com/fees.html

2022-04-21 11:19 UTC, petioptrv approved these changes
LGTM

2022-04-21 16:33 UTC, Deepali6997 commented
ASCENDEX

For some reason when we’re trying to run pure-market strategy in the PR214 branch, the strategy is not starting. Although the crypto assets are enough for a trade to take place. Also, didn't spot any error messages too. 

<img width="1728" alt="Screenshot 2022-04-21 at 8 29 46 PM" src="https://user-images.githubusercontent.com/100112937/164487043-b64b6ffc-2318-4431-bf3c-662ab7a71992.png">
<img width="1728" alt="Screenshot 2022-04-21 at 8 30 45 PM" src="https://user-images.githubusercontent.com/100112937/164487421-c592fb7f-59d1-48a5-920f-c15d21b7ab38.png">
<img width="1728" alt="Screenshot 2022-04-21 at 8 30 03 PM" src="https://user-images.githubusercontent.com/100112937/164487450-1e4341df-7629-4151-9719-31c12a6fe911.png">

[logs_ascendex.log](https://github.com/CoinAlpha/hummingbot/files/8532150/logs_ascendex.log)


Same is happening in MASTER branch. 

<img width="1728" alt="Screenshot 2022-04-21 at 8 49 40 PM" src="https://user-images.githubusercontent.com/100112937/164491056-be2ba4b5-db3d-4c75-ab16-e314f7c826ed.png">
<img width="1728" alt="Screenshot 2022-04-21 at 8 50 32 PM" src="https://user-images.githubusercontent.com/100112937/164491253-07282147-101a-44c9-b72f-9fff8d6aa840.png">

[logs_ascendex_master.log](https://github.com/CoinAlpha/hummingbot/files/8532286/logs_ascendex_master.log)

BYBIT PERPETUAL

for bybit perpetual market, we can see that in the logs file the fees calculated is having a high precision. Hence, the value is not matching the fee deduction value shown on the exchange.

Also, the price is showing the same behaviour. 

<img width="1728" alt="Screenshot 2022-04-21 at 8 54 55 PM" src="https://user-images.githubusercontent.com/100112937/164492282-e4ee8a57-73b8-4265-bc60-44e41fac2148.png">

<img width="1728" alt="Screenshot 2022-04-21 at 8 54 37 PM" src="https://user-images.githubusercontent.com/100112937/164492310-018e7893-33b0-46c5-b033-488f5e8b35a5.png">

<img width="1728" alt="Screenshot 2022-04-21 at 8 56 26 PM" src="https://user-images.githubusercontent.com/100112937/164492959-1c30d7e0-d4cc-4686-8f27-596fbd412cfa.png">

[trades_perpetual_mm.csv](https://github.com/CoinAlpha/hummingbot/files/8532775/trades_perpetual_mm.csv)


OkEx

The maker fee is not shown in the .csv file . PFB the attached snaps from csv and exchange 

<img width="1728" alt="Screenshot 2022-04-21 at 10 00 12 PM" src="https://user-images.githubusercontent.com/100112937/164507696-58cd3a7f-62be-4dc6-9588-71a61a063171.png">

<img width="1728" alt="Screenshot 2022-04-21 at 10 00 45 PM" src="https://user-images.githubusercontent.com/100112937/164507790-6ee4aa8b-721e-420b-9c75-97f2a3531f92.png">



[trades_okEx.csv](https://github.com/CoinAlpha/hummingbot/files/8532773/trades_okEx.csv)

2022-04-22 11:23 UTC, Deepali6997 commented
LGTM 

- Created Ppm/perpetual strategy 
- Set a tight bid spread and wide ask spread
- Post fill, run history verbose and compared fees between exchange and .csv file
- Re-checking balance and confirming that fee is deducted from order size
- Set a tight bid spread and wide ask spread
- Post fill, run history verbose and compared fees between exchange and .csv file

All exchanges are behaving as expected

2022-04-22 11:42 UTC, Deepali6997 approved these changes
Test Summary:-

- Created Ppm/perpetual strategy
- Set a tight bid spread and wide ask spread 
- Post fill, ran history verbose and compared fees between exchange and .csv file
- Re-checking balance and confirming that fee is deducted from order size
- Set a tight ask spread and wide bid spread
- Post fill, ran history verbose and compared fees between exchange and .csv file
- Can confirm that following connectors are behaving as expected
( Binance spot , Binance_perpetual, ascendex, bybit perpetual , gate_io , huobi, kucoin, okex, probit)

2022-04-22 12:19 UTC, mhrvth commented
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5247

2022-04-22 12:19 UTC, closed without merging