Fix / inconsistent symbols and pairs across hummingbot
CoinAlpha/hummingbot pull request #2212
Opened 2020-08-13 13:37 UTC by vic-en

**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #1922 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

2020-08-17 02:15 UTC, Nullably commented
@dennisocana Can you please test this PR? Generally, looks for trading pair format consistency in logs, status and history for all the connectors if you can, thanks.

2020-08-17 09:37 UTC, rxlxrxsx commented
## Binance - Warning
[logs_binance_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5083233/logs_binance_eth-usdt.log)

Looks OK from status, logs and history output.

![image](https://user-images.githubusercontent.com/64377055/90377408-8b0a6d80-e0aa-11ea-9407-d169032df2eb.png)
![image](https://user-images.githubusercontent.com/64377055/90377485-a07f9780-e0aa-11ea-9c98-c76ae94ccbf8.png)
![image](https://user-images.githubusercontent.com/64377055/90377528-ad03f000-e0aa-11ea-904d-9652284b158c.png)

This message below does not follow the trading pair format of ``BASE-QUOTE``.

``
2020-08-17 04:24:53,669 - 8912 - hummingbot.market.binance.binance_order_book_tracker - INFO - Initialized order book for ETHUSDT. 1/1 completed.
``

Ran into this error  64 times in an hour.
![image](https://user-images.githubusercontent.com/64377055/90377758-0704b580-e0ab-11ea-83f4-4b54fa4754e0.png)
![image](https://user-images.githubusercontent.com/64377055/90377796-14ba3b00-e0ab-11ea-81ab-b6d604f43062.png)

## Bittrex - OK
[logs_bittrex_xzc-btc.log](https://github.com/CoinAlpha/hummingbot/files/5083245/logs_bittrex_xzc-btc.log)

![image](https://user-images.githubusercontent.com/64377055/90378306-c3f71200-e0ab-11ea-83a5-6eb355e2671a.png)
![image](https://user-images.githubusercontent.com/64377055/90378362-d83b0f00-e0ab-11ea-8ff7-33c04a694358.png)
![image](https://user-images.githubusercontent.com/64377055/90378410-e6892b00-e0ab-11ea-8d09-a8fe03ae6fd9.png)

Minor from logs, this message shows original trading pair format.

``
2020-08-17 05:34:37,884 - 9687 - hummingbot.market.bittrex.bittrex_api_order_book_data_source - INFO - Query BTC-XZC snapshot.
``

## Liquid - OK
[logs_liquid_qash-eth.log](https://github.com/CoinAlpha/hummingbot/files/5083271/logs_liquid_qash-eth.log)

![image](https://user-images.githubusercontent.com/64377055/90378828-75964300-e0ac-11ea-8c50-9a24ac324ca9.png)
![image](https://user-images.githubusercontent.com/64377055/90378875-847cf580-e0ac-11ea-867f-f5a99436ccfa.png)
![image](https://user-images.githubusercontent.com/64377055/90378906-9068b780-e0ac-11ea-9b67-f4333fb78cfb.png)

## Eterbase - Failing
[logs_eterbase_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5083285/logs_eterbase_eth-usdt.log)

![image](https://user-images.githubusercontent.com/64377055/90379028-c148ec80-e0ac-11ea-819a-e3851a5c8204.png)
![image](https://user-images.githubusercontent.com/64377055/90379633-8b583800-e0ad-11ea-9320-d667810d05f7.png)

Naming convention looks okay, however, the bot fails to submit the orders because of ``KeyError: 'ETH-USDT'``.

![image](https://user-images.githubusercontent.com/64377055/90379324-2d2b5500-e0ad-11ea-8279-c316fc2834a3.png)
![image](https://user-images.githubusercontent.com/64377055/90379577-7aa7c200-e0ad-11ea-825d-2c66f8f850a4.png)

This message below does not follow the trading pair format of BASE-QUOTE
``
2020-08-17 06:02:00,722 - 10173 - hummingbot.market.eterbase.eterbase_order_book_tracker - INFO - Initialized order book for ETHUSDT. 1/1 completed.
``

## Huobi - Failing
[logs_test_huobi.log](https://github.com/CoinAlpha/hummingbot/files/5083338/logs_test_huobi.log)

Cannot run tests on Huobi due to a problem with Hummingbot getting the balance from the exchange. This is not happening in the current development branch where the testing bot is running.

![image](https://user-images.githubusercontent.com/64377055/90379996-176a5f80-e0ae-11ea-8ff9-fc935be82af0.png)

```
"branch": "development",
"commit": "6a87ca400331d9530059f2eab8a889240719bead",
"date": "2020-08-11T03:48:33Z",
"maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

## KuCoin - Failing
[logs_test_kucoin.log](https://github.com/CoinAlpha/hummingbot/files/5083352/logs_test_kucoin.log)

Pair in ``history`` output looks fine as expected.

![image](https://user-images.githubusercontent.com/64377055/90380254-6912ea00-e0ae-11ea-91d3-b2e961fe9e11.png)

Ran into errors, could not check ``status`` output.

![image](https://user-images.githubusercontent.com/64377055/90380337-85168b80-e0ae-11ea-9410-8635f73c9ebc.png)
![image](https://user-images.githubusercontent.com/64377055/90380426-9c557900-e0ae-11ea-9ad2-7f48d4b04e42.png)

## Kraken
[logs_test_kraken.log](https://github.com/CoinAlpha/hummingbot/files/5083377/logs_test_kraken.log)

Cannot start a strategy, cannot run ``status`` and ``history`` command.

![image](https://user-images.githubusercontent.com/64377055/90380591-d6bf1600-e0ae-11ea-8d59-6e3d583605b7.png)
![image](https://user-images.githubusercontent.com/64377055/90380713-fe15e300-e0ae-11ea-996f-3091d310351e.png)

## Coinbase Pro - Warning
[logs_test_coinbase_pro.log](https://github.com/CoinAlpha/hummingbot/files/5083391/logs_test_coinbase_pro.log)

Pair in ``history`` output looks fine as expected.

![image](https://user-images.githubusercontent.com/64377055/90380856-32899f00-e0af-11ea-977e-8bda96742cfe.png)
![image](https://user-images.githubusercontent.com/64377055/90380969-50ef9a80-e0af-11ea-9b38-bb7dea8c1bd1.png)

Unsure if this is related but posting this error here.

![image](https://user-images.githubusercontent.com/64377055/90381039-68c71e80-e0af-11ea-8fb5-f0c6a0ac0b79.png)

NOTE : I also noticed when the order amount has a decimal value e.g. 2.5 it adjusts and rounds down the size?

2020-08-20 10:00 UTC, Nullably requested changes

2020-08-25 12:44 UTC, Nullably approved these changes
Very clean approach. 
Pending testing by testers, we can then merge this. @dennisocana Can you please retest this?

2020-08-26 00:55 UTC, merged