feat / Make more params configurable on the fly
CoinAlpha/hummingbot pull request #2254
Opened 2020-08-25 17:58 UTC by vic-en

**Before submitting this PR, please make sure**:
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/", etc)

**Optional**:
- Related Github issue: #1716 
- Related Clubhouse Story:

**A description of the changes proposed in the pull request**:

2020-08-26 00:41 UTC, Nullably requested changes

2020-08-26 00:41 UTC, Nullably commented on hummingbot/strategy/pure_market_making/pure_market_making.pyx
> +        # It is necessary to point buy and sell levels to order_levels in order to make the configurable on the fly
You can do this in the order_levels property setter. Resetting the buy and sell levels here will be a problem for scripts.

2020-08-31 01:17 UTC, Nullably submitted a review, later dismissed
LGTM

2020-08-31 20:51 UTC, RC-13 commented
Test the following parameters:
- `order_amount` OK
![param-order-amount](https://user-images.githubusercontent.com/57189990/91764906-b0e75480-ec0a-11ea-8bb0-d215acddddc7.PNG)
![param-order-amount1](https://user-images.githubusercontent.com/57189990/91764918-b349ae80-ec0a-11ea-9ede-03491f4a0736.PNG)
- `order_levels` OK
![param-order-level](https://user-images.githubusercontent.com/57189990/91764935-bba1e980-ec0a-11ea-9216-1205a61ac3e3.PNG)
- `order_level_spread` OK
![param-order-spread](https://user-images.githubusercontent.com/57189990/91764942-bf357080-ec0a-11ea-9e1b-b5b451056474.PNG)
- `inventory_skew_enabled` OK
![param-order-skew](https://user-images.githubusercontent.com/57189990/91765296-4be02e80-ec0b-11ea-81de-e9dbd44ff118.PNG)
- `inventory_target_base_pct` works with one line only
- Doing `config inventory_target_base_pct` then pressing enter doesn't give this question: `In [exchange], you have [base_asset_balance] and [quote_asset_balance]. By market value, your current inventory split is [base_%_ratio] and [quote_%_ratio]. Would you like to keep this ratio?` Instead, it automatically pull the current value of inventory_target_base_pct.
![skew-base-pct](https://user-images.githubusercontent.com/57189990/91763546-51884500-ec08-11ea-8e92-b9508e49868b.gif)
- `inventory_range_multiplier` OK
![param-order-skew-multiplier](https://user-images.githubusercontent.com/57189990/91766350-04f33880-ec0d-11ea-972c-197feb1aba29.PNG)
- `filled_order_delay` OK
confirmed working and changes applies after getting a filled order

2020-09-01 07:12 UTC, dennisocana requested changes
QA found a bug when trying to configure `inventory_target_base_pct` on the fly except in KuCoin, Coinbase Pro, Liquid and Bittrex.

2020-09-14 03:10 UTC, dennisocana commented
@RC-13 please re-test this PR. As @vic-en mentioned, please note that only `inventory_target_base_pct` isn't configurable on the fly when using DEXs for now.

2020-09-14 18:11 UTC, RC-13 commented
Confirm `inventory_target_base_pct` on the fly is now working properly
![image](https://user-images.githubusercontent.com/57189990/93121307-35e86880-f6f7-11ea-8fb5-4c4183f77bfa.png)

2020-09-15 02:32 UTC, dennisocana approved these changes
QA tested and confirmed working.

2020-09-15 14:42 UTC, dennisocana approved these changes
LGTM

2020-09-15 14:43 UTC, merged