Fix/Align initial screen style with the rest of the client
CoinAlpha/hummingbot pull request #232
Opened 2022-05-05 15:10 UTC by mhrvth

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Initial screens apply the selected color configuration.

**Tests performed by the developer**:

Ran the client.

**Tips for QA testing**:

Please test on Windows specifically because I couldn't.

2022-05-05 15:11 UTC, mhrvth commented
[sc-22050]

2022-05-06 00:07 UTC, gerald-hb commented
Interface on Initial setup on Windows looks fine but still got a line on the hummingbot image above the output pane.

![image](https://user-images.githubusercontent.com/84826167/167046085-62ce394b-4a87-413c-972d-505ea72ceb33.png)

2022-05-06 02:58 UTC, aarmoa requested changes

2022-05-06 02:58 UTC, aarmoa commented on hummingbot/client/ui/__init__.py
> +def login_prompt(style):
We should add type hinting to the new parameter

2022-05-06 04:27 UTC, mhrvth commented
> Interface on Initial setup on Windows looks fine but still got a line on the hummingbot image above the output pane.
> 
> ![image](https://user-images.githubusercontent.com/84826167/167046085-62ce394b-4a87-413c-972d-505ea72ceb33.png)

Hi, how does it look like in the development branch?

2022-05-06 05:08 UTC, gerald-hb commented
Hi @mhrvth Apologies for the confusion. The test earlier was on a Linux terminal. I can confirm that it is fixed now
![image](https://user-images.githubusercontent.com/84826167/167070499-a141c390-a5d5-441b-b102-a2820f4f2594.png)

I am unable to run a test on Windows (gitbash) due to another issue.
![image](https://user-images.githubusercontent.com/84826167/167070576-26dc51cd-d643-4dc6-9b61-b89f9c89daa9.png)

2022-05-06 06:11 UTC, gerald-hb commented
Since there is an outstanding with Git bash (Windows) I have run another test using WSL (Ubuntu 18.04). No issue on UI
![image](https://user-images.githubusercontent.com/84826167/167076515-dd6575de-6a54-4539-88c7-a9b485d11d07.png)

Test Summary
-Install the feature branch and start the client: :white_check_mark: 
-Check the Hummingbot style: :white_check_mark: 		
-Check the text style in the terms of use: :white_check_mark: 			
-Check the style on the password setup: :white_check_mark:  			
-Verify Hummingbot in the client: :white_check_mark: 
-Restart the client and verify the style in the password section: :white_check_mark:

2022-05-06 06:13 UTC, mhrvth commented
> Hi @mhrvth Apologies for the confusion. The test earlier was on a Linux terminal. I can confirm that it is fixed now ![image](https://user-images.githubusercontent.com/84826167/167070499-a141c390-a5d5-441b-b102-a2820f4f2594.png)
> 
> I am unable to run a test on Windows (gitbash) due to another issue. ![image](https://user-images.githubusercontent.com/84826167/167070576-26dc51cd-d643-4dc6-9b61-b89f9c89daa9.png)

This looks like an unrelated error coming from the gateway / docker. Does it also happen on the development branch or just here?

2022-05-06 13:13 UTC, RC-13 approved these changes
LGTM!

Test summary:
- Check the styling for the Hummingbot startup logo for both Mac and Linux
- Check the styling of the dialog box for the terms of use for both Mac and Linux
- Check the styling of the password dialog box for both Mac and Linux

2022-05-10 21:13 UTC, aarmoa approved these changes
Changes look good to me

2022-05-11 12:06 UTC, mhrvth commented
Created a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5303

2022-05-11 12:06 UTC, closed without merging