Improve network logs for data coming from gateway
CoinAlpha/hummingbot pull request #244
Opened 2022-05-25 12:28 UTC by james-hummingbot

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Fix error code for `/amm/price`.
- Regex for the word `timeout` in gateway api calls from hummingbot. Do not log these.
- Change use of `logger().info()` to `logger().network()` in `gateway_http_client.py`. This will create less noise for the user.

**Tests performed by the developer**:

**Tips for QA testing**:

Try running hummingbot and gateway for a while. It should have less error logs in the console compared to previously.

2022-05-31 03:08 UTC, PtrckM commented
- getting `balances` during preliminary checks 
  - `balance` command working though

https://user-images.githubusercontent.com/54516858/171084007-648fd407-744b-41ce-90d1-e8f4ce92b61b.mov

- similar with traderjoe, uniswap (kovan, mainnet)

https://user-images.githubusercontent.com/54516858/171084056-89a40f1c-80e5-42bc-a50b-39a8f6c59b80.mov

- flooded with markets not ready using uniswap (kovan, mainnet), pangolin (avalanche), traderjoe (avalanche)

![uniswap_main](https://user-images.githubusercontent.com/54516858/171084316-d1527170-5eeb-48bb-a25b-c431de1cf6ca.png)

![traderjoe](https://user-images.githubusercontent.com/54516858/171084940-46e387e9-010c-4636-b123-cde0a04938cd.png)

2022-06-01 18:55 UTC, vic-en requested changes

2022-06-01 18:55 UTC, vic-en commented on hummingbot/core/gateway/gateway_http_client.py
> +                self.logger().network("An unknown error has occurred on gateway. Please send your logs to dev@hummingbot.io")
@james-hummingbot 
These messages will no longer show on the log panel.
Is that your intention?

2022-06-01 18:55 UTC, vic-en commented on hummingbot/core/gateway/gateway_http_client.py
> +                )
previous comment applies here too

2022-06-01 22:38 UTC, vic-en approved these changes
Changes LGTM

2022-06-02 00:35 UTC, RC-13 commented
Still running a long-term test bot under this PR, and didn't seem to get the issue mentioned above except for traderjoe and avalanche which is caused by another issue.

2022-06-06 00:38 UTC, RC-13 approved these changes
LGTM! We will monitor the reported issue in the development branch, once the PR is merged and will create a separate ticket if still persisting.

Test summary:
- Run a long term test bot for a week and confirmed that the error shown in the status is more readable.
- Error seen in the status is more of a network issue

2022-06-07 08:46 UTC, closed without merging