(fix) revised kucoin connector from exchange_data_fetcher
CoinAlpha/hummingbot pull request #2507
Opened 2020-10-23 10:16 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [ ] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:
This is the kucoin connector from the exchange_data_fetcher. It will need some extra work to be compatible with the current structure of hummingbot

2020-10-26 15:01 UTC, vic-en reviewed
LGTM

2020-10-26 16:36 UTC, Nullably approved these changes
LGTM
One minor thing on line 374 to 376, should you use the new `sec_until_next_oclock` function for this?
https://github.com/CoinAlpha/hummingbot/pull/2507/files#diff-93769022a39687aca6c9a05e6b52de552dc82c1b4306a9761438c5103896d22cR374

2020-10-26 22:11 UTC, martinkou requested changes

2020-10-26 22:11 UTC, martinkou commented on hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py
> +                    ping_task: asyncio.Task = \
`ping_task` is used in `finally`, but its definition here depends on a successful `websockets.connect()`.

This is not good, and could lead to `_outer_messages()` exiting silently if `websockets.connect()` happens to fail.

What you should do instead, is to define `ping_task` as optional and initialize as None before the try statement. And in the finally block, check if `ping_task` is defined and cancel it there.

2020-10-26 22:13 UTC, martinkou commented on hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py
> +                                     "task": asyncio.ensure_future(self._outer_messages(stream_type,
All background tasks in hummingbot must use `safe_ensure_future()`, to properly log any background tasks that failed silently.

2020-10-26 22:13 UTC, martinkou commented on hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py
> +                        asyncio.ensure_future(self._send_ping(KucoinAPIOrderBookDataSource.PING_INTERVAL, ws))
Same here, use `safe_ensure_future()`

2020-10-27 18:02 UTC, martinkou approved these changes

2020-10-27 18:02 UTC, merged