(feat) update client UI as proposed
CoinAlpha/hummingbot pull request #2508
Opened 2020-10-23 17:23 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [ ] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:

2020-10-26 07:03 UTC, rxlxrxsx commented
After producing 2 trades, it still displays 0 on trades and performance.

![trades](https://user-images.githubusercontent.com/64377055/97142836-68788d00-179c-11eb-8b9f-70937cb94117.PNG)

2020-10-26 07:09 UTC, dennisocana commented
Actually I just realized the feature request says "duration of the bot". In this branch, the duration in navbar is different than the duration in the `history` output.

The duration in navbar shows how long the instance is running while the duration in the `history` output shows how long the strategy is running. We can either:

1. Decide which duration we want to display (instance or strategy) and use the same for both
2. We can keep them separate but we need to explicitly indicate what each of them represent i.e. renaming to bot duration and strategy duration

2020-10-26 08:43 UTC, vic-en commented
> After producing 2 trades, it still displays 0 on trades and performance on the bottom bar.
> 
> ![trades](https://user-images.githubusercontent.com/64377055/97142836-68788d00-179c-11eb-8b9f-70937cb94117.PNG)

@rxlxrxsx Can you restart the bot or strategy and confirm it it still doesn't update?

2020-10-26 08:46 UTC, vic-en commented
> Actually I just realized the feature request says "duration of the bot". In this branch, the duration in navbar is different than the duration in the `history` output.
> 
> The duration in navbar shows how long the instance is running while the duration in the `history` output shows how long the strategy is running. We can either:
> 
>     1. Decide which duration we want to display (instance or strategy) and use the same for both
> 
>     2. We can keep them separate but we need to explicitly indicate what each of them represent i.e. renaming to bot duration and strategy duration

@dennisocana  I think option 2 is better. In my opinion, I think it's better for the duration at the bottom nav bar to show duration of instance. So I'll adjust that of the history command to "Strategy Duration" to make it less confusing.

2020-10-26 09:07 UTC, dennisocana commented
@vic-en @rxlxrxsx the trade count works fine on my end.

![image](https://user-images.githubusercontent.com/50150287/97153563-acc05900-17ad-11eb-950c-65fb6212c2c4.png)

2020-10-26 09:08 UTC, dennisocana approved these changes
LGTM

2020-10-26 14:55 UTC, dennisocana commented
Will also test on other platforms like Windows to make sure the navbars are working correctly.

2020-10-26 15:32 UTC, vic-en commented
@dennisocana  I resolved conficts. Thanks.

2020-10-27 08:07 UTC, dennisocana commented
@vic-en we're unable to test this on Windows because of this issue https://github.com/CoinAlpha/hummingbot/issues/2518

2020-10-27 22:05 UTC, mifeng requested changes
This feature is a big improvement over what we had before!

I'd like to request 2 changes:

1. Replace **Markets** and **Script_file** in the top bar with **Strategy file**. This should be more informative than Market because many users use different configs depending on market state. Also, I think Script file may not be future-proof we will allow users to load multiple scripts and we're going to steer people to write custom strategies rather than scripts.

2. In bottom bar, add **Total P&L** and change **Performance** to **Return %**. This uses the same wording as the new `history` command: 
<img width="519" alt="Screen Shot 2020-10-27 at 12 58 13 PM" src="https://user-images.githubusercontent.com/1795030/97367163-df2d8d00-1865-11eb-842f-a89c633317cb.png">

2020-10-29 02:46 UTC, Nullably commented on hummingbot/client/performance_analysis.py
> +    trade_performance_stats["no_of_trades"] = len(raw_queried_trades)
In the #/2512 PR, I created a new module for performance calculation, it's `performance.py` and we'll not be using `performance_analysis` anymore. Though I believe you can get the same information from there.

2020-10-29 09:30 UTC, rxlxrxsx commented
Trades are not showing after successfully getting a trade from the session. I tried restarting the session but got the same result. This happened both on cloud and binary. 

Test on cloud
![trades not showing 2](https://user-images.githubusercontent.com/64377055/97549270-2a34d500-1a0b-11eb-9211-f21fef91de38.PNG)

Test on Windows binary
![trades not showing binary](https://user-images.githubusercontent.com/64377055/97549300-328d1000-1a0b-11eb-8871-977b0ff69580.PNG)

Also found this on the logs after starting the strategy that's possibly related as to why trades are not logged on the ``Trades`` and ``Perfomance`` bottom navigation. 

![image](https://user-images.githubusercontent.com/64377055/97550126-38cfbc00-1a0c-11eb-8fdf-15be135700a0.png)

```
04:57:27,426 - 32589 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: 'HummingbotApplication' object has no attribute '_calculate_trade_performance'
NoneType: None
```

[logs_binance-test.log](https://github.com/CoinAlpha/hummingbot/files/5457330/logs_binance-test.log)

2020-10-29 10:39 UTC, vic-en commented
@rxlxrxsx It is due to the merged history redesign PR. I'm yet to push new commit.

2020-10-29 15:39 UTC, vic-en commented
@rxlxrxsx I pushed all commits. Test can be done now. Thank you.

2020-10-29 17:23 UTC, mifeng approved these changes
LGTM

2020-10-29 17:24 UTC, merged