fix/ local DigiFinex order book not in sync
CoinAlpha/hummingbot pull request #261
Opened 2022-06-16 03:26 UTC by CrimsonJacket

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The issue is the result of not including the right resolution for `timestamp` values for both `SNAPSHOT` and `DIFF` order book messages. This results in some diffs being dropped by the `OrderBookTracker` 

Resolves [sc-28591]

**Tests performed by the developer**:
No unit tests have been added since the Digifinex connector uses an old architecture and that this isnt a connector we supposedly maintained.

**Tips for QA testing**:
Ensure that the orderbook for liquid markets are now in sync.

2022-06-16 12:43 UTC, gerald-hb commented
Getting Websocket error. One incident, running the bot for 2 1/2 hours. I will continue to run this overnight and check if there are other WS disconnection will occur.
![image](https://user-images.githubusercontent.com/84826167/174071438-4d303888-ee74-4100-9b45-edb4d775d6d7.png)
```2022-06-16 12:00:02,511 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 191, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 172, in _subscribe_channels
    await websocket.subscribe("depth", list(map(
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 152, in subscribe
    id = await self.request(category + ".subscribe", channels)
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 148, in request
    return await self._emit(method, data)
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 142, in _emit
    await self._client.send(req)
AttributeError: 'NoneType' object has no attribute 'send'
2022-06-16 12:00:02,511 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
Traceback (most recent call last):
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 50, in connect
    self._client = await websockets.connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 388, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_websocket - NETWORK - {"id":1655380802514410,"method":"depth.subscribe","params":["DOGE_USDT"]}
2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error occured subscribing to Digifinex public channels. ('NoneType' object has no attribute 'send')
2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 191, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 172, in _subscribe_channels
    await websocket.subscribe("depth", list(map(
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 152, in subscribe
    id = await self.request(category + ".subscribe", channels)
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 148, in request
    return await self._emit(method, data)
  File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 142, in _emit
    await self._client.send(req)
AttributeError: 'NoneType' object has no attribute 'send'
```
Config used 
(Test is performed using source build on AWS cloud)
![image](https://user-images.githubusercontent.com/84826167/174071696-8ff562b6-a8c8-473d-be6a-5071f475f1ae.png)

2022-06-16 14:31 UTC, rxlxrxsx commented
There are still instances that the order book is not in sync with the exchange. See clip attached running on MDT-USDT pair:

https://user-images.githubusercontent.com/64377055/174092952-3e682502-043e-4984-9a5d-53110f3ca95a.mov

2022-06-17 00:54 UTC, gerald-hb commented
> Getting Websocket error. One incident, running the bot for 2 1/2 hours. I will continue to run this overnight and check if there are other WS disconnection will occur. ![image](https://user-images.githubusercontent.com/84826167/174071438-4d303888-ee74-4100-9b45-edb4d775d6d7.png)
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 191, in listen_for_subscriptions
>     await self._subscribe_channels(ws)
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 172, in _subscribe_channels
>     await websocket.subscribe("depth", list(map(
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 152, in subscribe
>     id = await self.request(category + ".subscribe", channels)
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 148, in request
>     return await self._emit(method, data)
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 142, in _emit
>     await self._client.send(req)
> AttributeError: 'NoneType' object has no attribute 'send'
> 2022-06-16 12:00:02,511 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
> 2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
> Traceback (most recent call last):
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 50, in connect
>     self._client = await websockets.connect(self._WS_URL)
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in __await_impl__
>     await protocol.handshake(
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 388, in handshake
>     raise InvalidStatusCode(status_code)
> websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
> 2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_websocket - NETWORK - {"id":1655380802514410,"method":"depth.subscribe","params":["DOGE_USDT"]}
> 2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error occured subscribing to Digifinex public channels. ('NoneType' object has no attribute 'send')
> 2022-06-16 12:00:02,514 - 22219 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
> Traceback (most recent call last):
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 191, in listen_for_subscriptions
>     await self._subscribe_channels(ws)
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 172, in _subscribe_channels
>     await websocket.subscribe("depth", list(map(
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 152, in subscribe
>     id = await self.request(category + ".subscribe", channels)
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 148, in request
>     return await self._emit(method, data)
>   File "/home/ubuntu/pr261/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 142, in _emit
>     await self._client.send(req)
> AttributeError: 'NoneType' object has no attribute 'send'
> ```
> 
> Config used (Test is performed using source build on AWS cloud) ![image](https://user-images.githubusercontent.com/84826167/174071696-8ff562b6-a8c8-473d-be6a-5071f475f1ae.png)

After the overnight run, we are still seeing multiple Websocket disconnection. Attaching the logs for reference
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/8923622/logs_conf_pure_mm_1.log)

2022-06-17 07:34 UTC, rxlxrxsx commented
- Setup a bot running for 4 hours already and no websocket connection errors so far, will continue to run the bot and update here if any websocket disconnection are encountered.

- On the latest commit the order book is no longer updating after starting the bot. See attached clip running on ETH-USDT pair:

https://user-images.githubusercontent.com/64377055/174244211-4e338957-0124-46eb-9a7a-ea14912c96be.mov

2022-06-17 10:29 UTC, Deepali6997 commented
getting the following error immediately after running the bot : Attached logs for reference.

<img width="834" alt="Screenshot 2022-06-17 at 3 54 39 PM" src="https://user-images.githubusercontent.com/100112937/174280195-f5047949-d98f-4633-a002-d4fbb025d57c.png">

[logs_pmm2.log](https://github.com/CoinAlpha/hummingbot/files/8926724/logs_pmm2.log)

2022-06-17 12:08 UTC, rxlxrxsx commented
Still having issues with order book synchronization as well on the latest commit:

https://user-images.githubusercontent.com/64377055/174295255-a165e1ad-f29c-41de-8a96-e5a2a67dbf11.mov

2022-06-20 05:11 UTC, CrimsonJacket commented
> Still having an issue with order book synchronization as well on the latest commit:
After some discussions with @aarmoa, it is evident that there are some underlying issues with DigiFinex's WS API. Even on the web application we are noticing frequent disconnects. As such, we opted for simply handling those disconnects and reconnecting to the WS API. This, without a doubt, would introduce certain inconsistencies.

Also I'd like to add that at this stage, with an unreliable WS connection and absence of API Rate Limits that are not present the connector should **not** be considered reliable.

2022-06-20 05:59 UTC, rxlxrxsx commented
- Getting flooded by websocket connection errors immediately after starting the bot:

<img width="1423" alt="Screen Shot 2022-06-20 at 1 43 41 PM" src="https://user-images.githubusercontent.com/64377055/174534749-334fff8d-0c28-4477-9d80-369ef52601e9.png">

```python
2022-06-20 12:29:30,025 - 3506 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Concurrent call to receive() is not allowed
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 186, in listen_for_subscriptions
    await self._ws.subscribe("depth", trading_pairs)
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 101, in subscribe
    raw_msg: bytes = await self._websocket.receive_bytes()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_ws.py", line 280, in receive_bytes
    msg = await self.receive(timeout)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_ws.py", line 216, in receive
    raise RuntimeError("Concurrent call to receive() is not allowed")
RuntimeError: Concurrent call to receive() is not allowed
```

```python
2022-06-20 12:29:30,032 - 3506 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Received message 256:None is not bytes
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 186, in listen_for_subscriptions
    await self._ws.subscribe("depth", trading_pairs)
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 101, in subscribe
    raw_msg: bytes = await self._websocket.receive_bytes()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_ws.py", line 282, in receive_bytes
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not bytes")
TypeError: Received message 256:None is not bytes
```

```python
2022-06-20 12:29:30,716 - 3506 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. local variable 'parse_msg' referenced before assignment
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 189, in listen_for_subscriptions
    async for msg in self._ws.iter_messages():
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 134, in iter_messages
    yield parse_msg
UnboundLocalError: local variable 'parse_msg' referenced before assignment
```

```python
2022-06-20 12:29:31,007 - 3506 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. 'NoneType' object has no attribute 'send_str'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 186, in listen_for_subscriptions
    await self._ws.subscribe("depth", trading_pairs)
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 100, in subscribe
    request_id = await self.request(category + ".subscribe", channels)
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 94, in request
    await self._websocket.send_str(ujson.dumps(payload))
AttributeError: 'NoneType' object has no attribute 'send_str'
```

```python
2022-06-20 12:29:32,276 - 3506 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: '401, message='Invalid response status', url=URL('wss://openapi.digifinex.com/ws/v1/')'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot1/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 47, in connect
    self._websocket = await aiohttp.ClientSession().ws_connect(self._WS_URL)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 401, message='Invalid response status', url=URL('wss://openapi.digifinex.com/ws/v1/')
```

Log file: [logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/8937920/logs_conf_pure_mm_1.log)

2022-06-20 08:48 UTC, CrimsonJacket commented
@rxlxrxsx Thanks for testing it again.
The 401 error response seems to suggest that the API key is "Not Authorised". Could you try with a new set of API keys?
The next few errors should not keep happen indefinitely and should be handled accordingly. I will look into this and make more changes.

2022-06-20 09:04 UTC, Deepali6997 commented
Would like to add one more observation. When adding digifinex, we were getting the following error message. {'code': 10008}. When trying once again, the API key got accepted. 

<img width="851" alt="Screenshot 2022-06-20 at 2 32 41 PM" src="https://user-images.githubusercontent.com/100112937/174566076-4b2a7584-f157-4fdd-99c0-b1ee1712ee7b.png">
 
Also, this error message is different from the error message that comes when we give wrong API keys
<img width="848" alt="Screenshot 2022-06-20 at 2 34 01 PM" src="https://user-images.githubusercontent.com/100112937/174566355-9674afd2-085c-4f10-b33e-96a3892261f4.png">

P.S. : Used the existing API keys

2022-06-20 10:56 UTC, Deepali6997 commented
Getting same errors with new set of API keys 

<img width="1728" alt="Screenshot 2022-06-20 at 4 19 37 PM" src="https://user-images.githubusercontent.com/100112937/174586025-e6dfdf20-4f0e-43b0-b742-971637fdd5ec.png">

log file : [logs_PMM.log](https://github.com/CoinAlpha/hummingbot/files/8939992/logs_PMM.log)

2022-06-21 04:29 UTC, rxlxrxsx commented
Checking the long term bot running for 14 hours the websocket errors previously reported were no longer appearing. Here are the websocket errors that the bot was able to encounter while currently running on the latest commit:

32 instances of this error

```python
2022-06-20 16:00:03,036 - 24188 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: '502, message='Invalid response status', url=URL('wss://openapi.digifinex.com/ws/v1/')'
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 43, in connect
    self._connection = await self._client.ws_connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 502, message='Invalid response status', url=URL('wss://openapi.digifinex.com/ws/v1/')
```

5 instances of this error
```python
2022-06-20 16:05:23,887 - 24188 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'Websocket server closed the connection'
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 45, in connect
    await self.login()
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 52, in login
    response: aiohttp.WSMessage = await self.receive()
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 107, in receive
    raise aiohttp.ClientConnectionError("Websocket server closed the connection")
aiohttp.client_exceptions.ClientConnectionError: Websocket server closed the connection
```

And occassionally getting this in the logs as well
<img width="1424" alt="Screen Shot 2022-06-21 at 12 06 08 PM" src="https://user-images.githubusercontent.com/64377055/174715820-de0b1669-177d-49e1-a097-a2511f7a2bae.png">

Log file: [logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/8945796/logs_conf_pure_mm_1.log)

2022-06-21 04:43 UTC, rxlxrxsx commented
> After some discussions with @aarmoa, it is evident that there are some underlying issues with DigiFinex's WS API. Even on the web application we are noticing frequent disconnects. As such, we opted for simply handling those disconnects and reconnecting to the WS API. This, without a doubt, would introduce certain inconsistencies.

> Also I'd like to add that at this stage, with an unreliable WS connection and absence of API Rate Limits that are not present the connector should not be considered reliable.

After some discussions with @CrimsonJacket, due to the underlying issue with DigiFinex API we should label the connector as **RED**.

2022-06-21 04:43 UTC, CrimsonJacket commented
@rxlxrxsx Yea the above errors above are expected. As per discussed with @aarmoa, the underlying issues are attributed to DigiFinex WS API prematurely disconnecting the websocket connection, thus the errors you have observed. The changes I've made revolves around handling the frequent disconnects and ensuring that the bot resumes.

As for now, it is critical the bot is still able to update the orderbook(relatively in sync), placing orders and tracking orders.
At this stage, I would lean towards labelling the DigiFinex connector as `RED`, what do you think?

2022-06-21 05:46 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA

- Connected API keys (valid and invalid key) and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a pure_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is relatively in sync with the exchange
- Trade information are correct (price, size and maker/taker fees) based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed hanging order/cancellation and multiple order levels works as expected

2022-06-21 15:52 UTC, aarmoa requested changes

2022-06-21 15:52 UTC, aarmoa commented on hummingbot/connector/exchange/digifinex/digifinex_api_user_stream_data_source.py
> +                await self._ws.disconnect()
Here we should add the same check that self._ws is not None, as in the order book data source

2022-06-22 15:36 UTC, aarmoa approved these changes
The changes look good to me

2022-06-23 12:01 UTC, CrimsonJacket commented
Closed and recreated [PR #5430](https://github.com/hummingbot/hummingbot/pull/5430) created on Foundation repo.
Snapshot Link: https://snapshot.org/#/hbot-prp.eth/proposal/0xd49b9ba5c2c34aa33592732d7f59e6da45f41ec519774e78e0dc1c4ef25d5d2a

2022-06-23 12:01 UTC, closed without merging