Feat / Uniswap connector
CoinAlpha/hummingbot pull request #2648
Opened 2020-11-18 19:04 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**After creating this PR, please make sure:**

- [ ] You link the related GitHub issue or ticket

**A description of the changes proposed in the pull request**:

2020-11-23 07:30 UTC, Nullably requested changes
Can you please supply unit testing for the new Uniswap connector?

2020-11-23 07:33 UTC, Nullably commented on hummingbot/connector/connector/uniswap/uniswap_connector.py
> +                                        "connector": self.name})
Since the approve API now requires connector name, can you please update `BalancerConnector` as well?

2020-11-24 12:51 UTC, PtrckM commented
- Upon starting the bot the throws error 
![image](https://user-images.githubusercontent.com/54516858/100092654-6421bb80-2e91-11eb-801f-6bd9249c06fc.png)

```
2020-11-24 20:11:28,848 - 6052 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-11-24 20:11:29,133 - 6052 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\connector\connector_base.pyx", line 207, in hummingbot.connector.connector_base.ConnectorBase.c_tick
    self.tick(timestamp)
  File "C:\Users\rewt\hummingbot\hummingbot\connector\connector\uniswap\uniswap_connector.py", line 390, in tick
    if not self._poll_notifier.is_set():
AttributeError: 'UniswapConnector' object has no attribute '_poll_notifier'
```

- shows connector status: UNKNOWN
![image](https://user-images.githubusercontent.com/54516858/100092981-ddb9a980-2e91-11eb-9bc5-c557211c4da3.png)

- after awhile bot throws an error `Unhandled error in background task` after every `Error fetching data`
![image](https://user-images.githubusercontent.com/54516858/100093582-b2838a00-2e92-11eb-9899-0f1f4e49b0e7.png)
```
2020-11-24 20:21:47,299 - 17396 - hummingbot.connector.connector.uniswap.uniswap_connector - NETWORK - Error getting quote price for WETH-DAI  buy order for 0.02 amount.
Traceback (most recent call last):
  File "C:\Users\rewt\hummingbot\hummingbot\core\utils\__init__.py", line 13, in memoize
    return cache[key]
  File "C:\Users\rewt\miniconda3\envs\hummingbot\lib\site-packages\cachetools\ttl.py", line 82, in __getitem__
    return self.__missing__(key)
  File "C:\Users\rewt\miniconda3\envs\hummingbot\lib\site-packages\cachetools\cache.py", line 68, in __missing__
    raise KeyError(key)
KeyError: "((<hummingbot.connector.connector.uniswap.uniswap_connector.UniswapConnector object at 0x0000021B88E74940>, 'WETH-DAI', True, Decimal('0.02')), {})"
```
[logs_uniswap_binance.log](https://github.com/CoinAlpha/hummingbot/files/5589852/logs_uniswap_binance.log)


- balance = OK
- constantly checking for arbitrage opportunity = OK
- every 2 mins check - eth_gas_station_lookup 120 sec = OK
- history = OK
- delay after starting strategy
- delay when doing `status` command

- doesn't notify when there is a filled order = left and right pane
- create csv file for filled trade = OK
- sqlite data logged filled trade = OK
log
[logs_conf_amm_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/5589899/logs_conf_amm_arb_1.log)
csv
[trades_conf_amm_arb_1_csv.txt](https://github.com/CoinAlpha/hummingbot/files/5589904/trades_conf_amm_arb_1_csv.txt)
sqlite
[conf_amm_arb_1_sqlite.txt](https://github.com/CoinAlpha/hummingbot/files/5589905/conf_amm_arb_1_sqlite.txt)

2020-11-24 16:39 UTC, vic-en commented
@PtrckM 
Can you test against `refactor/refactor_uniswap_price_routes` branch on gateway?
I don't have any errors testing with that branch which fixed some issues.

2020-11-25 13:06 UTC, PtrckM commented
amm_arb uniswap -> binance/balancer using refactor/refactor_uniswap_price_routes
  - connect etherem = OK
  - `config ethereum_rpc_url` = OK
  - `config ethereum_rpc_ws_url` = OK
  - `config ethereum_chain_name MAIN_NET` = OK
    - 'MAIN_NET' - main net = OK
    - 'KOVAN' - ethereum testnet = OK
  - config ethgasstation_gas_enabled yes = OK
  - `config ethgasstation_api_key` = OK
  - `config ethgasstation_gas_level fast` = OK
  - `config ethgasstation_refresh_time 30` = OK
  - generate_certs = OK
  - history = OK
  - csv fille trades = OK
  - sqlite data = OK
  - no more error during startup = OK
---
- getting random `Error fetching data` = `async_utils - Unhandled error in background task: unsupported operand type(s) for /: 'decimal.Decimal' and 'NoneType' (See log file for stack trace dump)`

- on gateway
```
Pools Retrieved. undefined
Warning: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not checksummed.
Warning: 0x6b175474e89094c44da98b954eedeac495271d0f is not checksummed.
Warning: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not checksummed.
Pools Retrieved. undefined
Warning: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not checksummed.
Warning: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not checksummed.
Warning: 0x6b175474e89094c44da98b954eedeac495271d0f is not checksummed.
Pools Retrieved. undefined
```
- on logs
```
2020-11-25 14:32:29,344 - 9556 - hummingbot.connector.connector.uniswap.uniswap_connector - NETWORK - Error submitting BUY order to Uniswap for 0.020000000000000 WETH-DAI 592.512020000000000.
Traceback (most recent call last):
  File "C:\Users\rewt\hummingbot\hummingbot\connector\connector\uniswap\uniswap_connector.py", line 244, in _create_order
    order_result = await self._api_request("post", f"uniswap/{trade_type.name.lower()}", api_params)
  File "C:\Users\rewt\hummingbot\hummingbot\connector\connector\uniswap\uniswap_connector.py", line 473, in _api_request
    response = await client.post(url, data=params)
  File "C:\Users\rewt\miniconda3\envs\hummingbot\lib\site-packages\aiohttp\client.py", line 504, in _request
    await resp.start(conn)
  File "C:\Users\rewt\miniconda3\envs\hummingbot\lib\site-packages\aiohttp\client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "C:\Users\rewt\miniconda3\envs\hummingbot\lib\site-packages\aiohttp\streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

- As discussed with @vic-en  it happens if there are no reserves/liquidity for that pair on mainnet, but most of the time bot recovers and continue. It never occurs on kovan during testing, reserves/liquidity isn't a problem on kovan.

2020-11-25 19:50 UTC, mifeng requested changes
I think the estimated gas cost may be off by a decimal place - here's what it says in the logs:
<img width="602" alt="Screen Shot 2020-11-25 at 11 48 04 AM" src="https://user-images.githubusercontent.com/1795030/100275098-4ba6b500-2f14-11eb-8936-4ec16cf55c97.png">

However, the [Kovan transaction](https://kovan.etherscan.io/tx/0x8810779eb9751acd462ee0b340f81f6d8075df3bb18b8066adf7996317a9efcb) shows 0.0025 ETH gas used

Can you double check the calculation?

EDIT: In this log message, can you include the **gasPrice** (number) and **gasLimit** used to estimate the gas price?

2020-11-25 21:21 UTC, mifeng commented
> I think the estimated gas cost may be off by a decimal place - here's what it says in the logs:
> <img alt="Screen Shot 2020-11-25 at 11 48 04 AM" width="602" src="https://user-images.githubusercontent.com/1795030/100275098-4ba6b500-2f14-11eb-8936-4ec16cf55c97.png">
> 
> However, the [Kovan transaction](https://kovan.etherscan.io/tx/0x8810779eb9751acd462ee0b340f81f6d8075df3bb18b8066adf7996317a9efcb) shows 0.0025 ETH gas used
> 
> Can you double check the calculation?
> 
> EDIT: In this log message, can you include the **gasPrice** (number) and **gasLimit** used to estimate the gas price?

After some more testing, the ETH gas calculation in `eth_gas_station_lookup.py` looks correct. Does `con_setting.gas_limit` == 150688 (the Uniswap transaction gas limit)?

2020-12-01 14:42 UTC, Nullably approved these changes
LGTM

2020-12-01 14:45 UTC, merged