Feat/huobi refactor
CoinAlpha/hummingbot pull request #274
Opened 2022-07-12 13:16 UTC by 737Baron

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2022-07-13 00:55 UTC, rxlxrxsx commented
Also getting this error upon client startup:

<img width="1423" alt="Screen Shot 2022-07-13 at 8 51 16 AM" src="https://user-images.githubusercontent.com/64377055/178625465-17ce4fb3-b060-4425-bd00-06e0a50eebf5.png">

```python
2022-07-13 08:50:53,245 - 4169 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot4/hummingbot/connector/exchange_py_base.py", line 889, in _initialize_trading_pair_symbol_map
    self._initialize_trading_pair_symbols_from_exchange_info(exchange_info=exchange_info)
  File "/Users/reiniersalazar/hummingbot4/hummingbot/connector/exchange/huobi/huobi_exchange.py", line 470, in _initialize_trading_pair_symbols_from_exchange_info
    mapping[symbol_data["sc"]] = combine_to_hb_trading_pair(base=symbol_data["bc"], quote=symbol_data["qc"])
KeyError: 'sc'
```

Logs: [logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/9097940/logs_hummingbot.log)

2022-07-14 10:46 UTC, Deepali6997 commented
When giving correct credentials
<img width="748" alt="Screenshot 2022-07-14 at 4 15 38 PM" src="https://user-images.githubusercontent.com/100112937/178965301-debc6ef6-d15b-485f-8b15-82b821c80ca9.png">

When giving incorrect credentials
<img width="850" alt="Screenshot 2022-07-14 at 4 16 02 PM" src="https://user-images.githubusercontent.com/100112937/178965381-9681227e-0de1-4892-8236-7c510a4e3097.png">

2022-07-14 14:18 UTC, Deepali6997 commented
thanks @737Baron for the fix. The huobi key is getting accepted now. 
For the error message that is too technical when we give incorrect credentials. Are we planning to keep it that way?
<img width="840" alt="Screenshot 2022-07-14 at 7 47 47 PM" src="https://user-images.githubusercontent.com/100112937/179004106-315feb25-cdbb-41ab-8ca7-6780ead9cec4.png">

2022-07-14 14:49 UTC, 737Baron commented
I have pushed another change to display a better error message. Please
check.

On Thu, Jul 14, 2022 at 7:48 PM DGxx ***@***.***> wrote:

> thanks @737Baron <https://github.com/737Baron> for the fix. The huobi key
> is getting accepted now.
> For the error message that is too technical when we give incorrect
> credentials. Are we planning to keep it that way?
> [image: Screenshot 2022-07-14 at 7 47 47 PM]
> <https://user-images.githubusercontent.com/100112937/179004106-315feb25-cdbb-41ab-8ca7-6780ead9cec4.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CoinAlpha/hummingbot/pull/274#issuecomment-1184505503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZOAOZ46KZFB2L7RTWPQ44TVUAOS7ANCNFSM53K77YSA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-14 15:07 UTC, Deepali6997 commented
thanks, we can see an updated error message which is more clear. 
<img width="811" alt="Screenshot 2022-07-14 at 8 33 00 PM" src="https://user-images.githubusercontent.com/100112937/179014103-f315fb18-a8cf-4c0f-8a6a-4715429e2db3.png">

Right now when we are running a strategy, an error in log pane is seen

```
2022-07-14 20:31:25,785 - 64494 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-07-14 20:31:26,517 - 64494 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-07-14 20:31:26,517 - 64494 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: listen_for_order_book_diffs() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/Users/deepaligautam/huobi/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/core/network_iterator.pyx", line 112, in _check_network_loop
    await self.start_network()
  File "/Users/deepaligautam/huobi/hummingbot/connector/exchange_py_base.py", line 633, in start_network
    self.order_book_tracker.start()
  File "/Users/deepaligautam/huobi/hummingbot/connector/exchange/huobi/huobi_order_book_tracker.py", line 60, in start
    super().start()
  File "/Users/deepaligautam/huobi/hummingbot/core/data_type/order_book_tracker.py", line 87, in start
    self._data_source.listen_for_order_book_diffs(self._ev_loop, self._order_book_diff_stream)
TypeError: listen_for_order_book_diffs() takes 2 positional arguments but 3 were given
2022-07-14 20:31:26,958 - 64494 - hummingbot.connector.exchange.huobi.huobi_order_book_tracker - INFO - Initialized order book for firo-usdt. 1/1 completed.
```
<img width="1728" alt="Screenshot 2022-07-14 at 8 34 08 PM" src="https://user-images.githubusercontent.com/100112937/179014413-07f720bd-e03e-40db-8f75-616eb1a3a451.png">


attached are files for refrence:
[logs_pmm.log](https://github.com/CoinAlpha/hummingbot/files/9112938/logs_pmm.log)
[pmm.txt](https://github.com/CoinAlpha/hummingbot/files/9112945/pmm.txt)

2022-07-15 17:33 UTC, gerald-hb commented
Seeing some errors after starting a strategy
![image](https://user-images.githubusercontent.com/84826167/179277158-af8e66b7-3718-45f8-9520-c871b604730f.png)
```
2022-07-16 01:26:31,041 - 19363 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 752, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal = self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 781, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    buy_reference_price = sell_reference_price = self.get_price()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 428, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
  File "/home/geraldhb/pr274/hummingbot/strategy/market_trading_pair_tuple.py", line 40, in get_price_by_type
    return self.market.get_price_by_type(self.trading_pair, price_type)
  File "hummingbot/connector/exchange_base.pyx", line 344, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
    return (self.c_get_price(trading_pair, True) + self.c_get_price(trading_pair, False)) / Decimal("2")
  File "hummingbot/connector/exchange_base.pyx", line 162, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
    return self.c_quantize_order_price(trading_pair, top_price)
  File "hummingbot/connector/connector_base.pyx", line 391, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
    price_quantum = self.c_get_order_price_quantum(trading_pair, price)
  File "hummingbot/connector/connector_base.pyx", line 371, in hummingbot.connector.connector_base.ConnectorBase.c_get_order_price_quantum
    return self.get_order_price_quantum(trading_pair, price)
  File "/home/geraldhb/pr274/hummingbot/connector/exchange_py_base.py", line 208, in get_order_price_quantum
    trading_rule = self._trading_rules[trading_pair]
KeyError: 'eth-usdt'
```
[support packets.zip](https://github.com/CoinAlpha/hummingbot/files/9122848/support.packets.zip)

2022-07-17 23:23 UTC, RC-13 commented
I'm not sure if this is causing some issue however, can we show the markets in uppercases? So that it would be the same to all exchanges.
Current behavior:
![huobi-market](https://user-images.githubusercontent.com/57189990/179428893-a505b785-f196-48dc-9daf-e0f1315cc2ff.png)
![image](https://user-images.githubusercontent.com/57189990/179428937-9b8eda6d-cbb6-4dce-8342-5d66ca9010bc.png)

Expected:
![image](https://user-images.githubusercontent.com/57189990/179428905-4964a27a-f350-4938-9e44-71f34fbaa527.png)

2022-07-21 04:01 UTC, rxlxrxsx commented
Checking the long term test bot running there are instances that this error/warning is being thrown. There were no stuck orders upon checking the exchange.

Sample 1:

```python
2022-07-21 02:50:00,003 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.008 ETH, 1494.21 USDT']
2022-07-21 02:50:00,003 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.0079 ETH, 1506.21 USDT']
2022-07-21 02:50:00,389 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547 for 0.0080 ETH-USDT.
2022-07-21 02:50:00,421 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658371800.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1494.21", "order_id": "AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547", "creation_timestamp": 1658371800.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}

## Error message
2022-07-21 02:50:00,422 - 1566306 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - NETWORK - Error fetching status update for the order AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547: Invalid variable type: value should be str or int, got None of type <class 'NoneType'>.
2022-07-21 02:50:00,422 - 1566306 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Failed to fetch status update for the order AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547.


2022-07-21 02:50:00,641 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT1821ea97bc4bd4bd48d3257ff364489feb2d4376547 for 0.0079 ETH-USDT.
2022-07-21 02:50:00,648 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658371800.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0079", "price": "1506.21", "order_id": "AAc484720aSEHUT1821ea97bc4bd4bd48d3257ff364489feb2d4376547", "creation_timestamp": 1658371800.0, "exchange_order_id": "589719591955198", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}
2022-07-21 02:50:20,004 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547. [clock=2022-07-21 02:50:20+00:00]
2022-07-21 02:50:20,005 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1821ea97bc4bd4bd48d3257ff364489feb2d4376547. [clock=2022-07-21 02:50:20+00:00]
2022-07-21 02:50:20,141 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658371820.0, "order_id": "AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547", "exchange_order_id": "589719566167727", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-07-21 02:50:20,141 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT1821ea97bc3bd4bd48d3257ff364489feb2d4376547.
2022-07-21 02:50:20,216 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658371820.0, "order_id": "AAc484720aSEHUT1821ea97bc4bd4bd48d3257ff364489feb2d4376547", "exchange_order_id": "589719591955198", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-07-21 02:50:20,216 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aSEHUT1821ea97bc4bd4bd48d3257ff364489feb2d4376547.
```

Sample 2:

```python
2022-07-20 18:14:22,009 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.008 ETH, 1550.64 USDT']
2022-07-20 18:14:22,009 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.008 ETH, 1563.1 USDT']
2022-07-20 18:14:22,120 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT1821cd16839bd4bd48d3257ff364489feb2d4376547 for 0.0080 ETH-USDT.
2022-07-20 18:14:22,131 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658340862.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1550.64", "order_id": "AAc484720aBEHUT1821cd16839bd4bd48d3257ff364489feb2d4376547", "creation_timestamp": 1658340862.0, "exchange_order_id": "589715162481323", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
2022-07-20 18:14:22,379 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547 for 0.0080 ETH-USDT.
2022-07-20 18:14:22,387 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658340862.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0080", "price": "1563.10", "order_id": "AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547", "creation_timestamp": 1658340862.0, "exchange_order_id": "None", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}
2022-07-20 18:14:42,020 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT1821cd16839bd4bd48d3257ff364489feb2d4376547. [clock=2022-07-20 18:14:42+00:00]
2022-07-20 18:14:42,020 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547. [clock=2022-07-20 18:14:42+00:00]
2022-07-20 18:14:42,149 - 1566306 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658340882.0, "order_id": "AAc484720aBEHUT1821cd16839bd4bd48d3257ff364489feb2d4376547", "exchange_order_id": "589715162481323", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-07-20 18:14:42,150 - 1566306 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT1821cd16839bd4bd48d3257ff364489feb2d4376547.


## Error message
2022-07-20 18:15:43,003 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547. [clock=2022-07-20 18:15:43+00:00]
2022-07-20 18:16:00,569 - 1566306 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - NETWORK - Error fetching status update for the order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547: {'status': 'error', 'err-code': 'validation-format-error', 'err-msg': 'Format Error: order-id.', 'data': None}.
2022-07-20 18:16:00,569 - 1566306 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Failed to fetch status update for the order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547.
2022-07-20 18:16:44,002 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547. [clock=2022-07-20 18:16:44+00:00]
2022-07-20 18:17:45,001 - 1566306 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547. [clock=2022-07-20 18:17:45+00:00]
2022-07-20 18:18:00,589 - 1566306 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - NETWORK - Error fetching status update for the order AAc484720aSEHUT1821cd1683abd4bd48d3257ff364489feb2d4376547: {'status': 'error', 'err-code': 'validation-format-error', 'err-msg': 'Format Error: order- [...]

2022-07-21 19:36 UTC, gerald-hb commented
I will update our long term with the latest commit and will report back if there are further issue found.

2022-07-22 07:47 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

Tested and confirmed working by QA.

- Connected API keys (valid and invalid key) and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a pure_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is in sync with the exchange
- Trade information are correct based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed hanging order/cancellation and multiple order levels works as expected
- Tested on other supported strategies as well and confirmed working
- Successfully built a docker image and create a docker instance

2022-07-22 11:53 UTC, Deepali6997 commented
still LGTM!

2022-07-25 04:12 UTC, aarmoa requested changes
I have started reviewing the PR. So far I have been able only to review the order book data source class. I publish my comments already to allow Sambaran to work on them

2022-07-25 04:12 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
>          try:
I don't think we should use the trading pair as id of the message (lines 72 and 76). Also according to the documentation each message id should be unique, and we are using the same id for two different subscribe messages.

2022-07-25 04:12 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
> +            "asks": msg["tick"]["asks"]
We should prepare the code for cases when the exchange sends an update with only bids or only asks.
```suggestion
            "bids": msg["tick"]get("bids", []),
            "asks": msg["tick"].get("asks", [])
```

2022-07-25 04:12 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
> +                self._message_queue[channel].put_nowait(data)
This should be replaced with a call to `tracked_order = self._order_tracker.all_updatable_orders.get(client_order_id)`.

2022-07-26 04:20 UTC, aarmoa requested changes

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +            if order_state not in ["submitted", "filled", "canceled", "partial-filled", "created", "partial-canceled", "canceling"]:
```suggestion
            if order_state not in CONSTANTS.ORDER_STATE:
```

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +                update_timestamp=self.current_timestamp * 1e-3,
`self.current_timestamp` returns seconds. It should not be multiplied by 1e-3

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +                exchange_order_id=str(tracked_order.exchange_order_id),
The exchange order id has to be taken from the status request result, not from the tracked order.

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +                    continue
The subscription confirmations should be filtered out in the UserStreamDataSource class, not here.

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +            self.logger().debug(f"Unrecognized order update response - {msg}")
No need to do this, since the code will raise an exception later anyways

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +                update_timestamp=self.current_timestamp * 1e-3,
`self.current_timestamp` is already in seconds

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +        tracked_order = self.in_flight_orders.get(client_order_id, None)
To process order trades we have to consider live orders and recently finished orders
```suggestion
        tracked_order = self._order_tracker.fetch_order(client_order_id=client_order_id)
```

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +        pass
According to the documentation the client-order-id max length is 64 characters. Please complete the method correctly and add the value as a global (https://huobiapi.github.io/docs/spot/v1/en/#place-a-new-order)

2022-07-26 04:20 UTC, aarmoa commented on hummingbot/connector/exchange/huobi/huobi_exchange.py
> +        path_url = CONSTANTS.CANCEL_ORDER_URL.format(tracked_order.exchange_order_id)
We should use the endpoint that cancels orders based on their client order id, and not the one for exchange order id.

2022-07-27 21:13 UTC, aarmoa commented
@737Baron please remember to solve the merge issues (do not merge the PR, just solve the conflicts)

2022-07-29 11:41 UTC, Deepali6997 commented
while checking the PR with @PtrckM we found that following error when giving the Huobi API key.
It gives the prompts for other connector though.  (e.g Binance)

<img width="1728" alt="Screenshot 2022-07-29 at 5 08 03 PM" src="https://user-images.githubusercontent.com/100112937/181751250-a112d940-5af5-4d92-9ca1-a5c2e2ded30c.png">

```
2022-07-29 17:03:05,869 - 7038 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dict' object has no attribute 'connector'
Traceback (most recent call last):
  File "/Users/deepaligautam/PR274/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/deepaligautam/PR274/hummingbot/client/command/connect_command.py", line 72, in connect_exchange
    await self._perform_connect(connector_config)
  File "/Users/deepaligautam/PR274/hummingbot/client/command/connect_command.py", line 174, in _perform_connect
    connector_name = connector_config.connector
  File "/Users/deepaligautam/PR274/hummingbot/client/config/config_helpers.py", line 119, in __getattr__
    value = getattr(self._hb_config, item)
AttributeError: 'dict' object has no attribute 'connector'
```

2022-07-29 12:17 UTC, aarmoa commented
@Deepali6997 please do not continue testing the PR. We are working on merging it on top of the latest development branch version. We will post a comment once you can resume the testing.

2022-07-29 16:16 UTC, aarmoa commented
@CoinAlpha/qa-team please QA consider this PR ready to be tested again. We would need you to validate that everything is working properly after the last update. What changed is mainly the order update logic, to include getting the order fills through HTTP (as the backup plan for the websocket communication)

2022-07-29 17:30 UTC, gerald-hb commented
Seeing this behavior upon starting the strategy. It is not placing orders. Tested on ETH-USDT and DOGE-USDT.
![image](https://user-images.githubusercontent.com/84826167/181812294-349347c3-2293-40d4-ab42-ac70ebe531e4.png)
```
2022-07-30 01:25:34,563 - 4639 - hummingbot.connector.exchange.huobi.huobi_api_user_stream_data_source.HuobiAPIUserStreamDataSource - ERROR - Unexpected error occurred subscribing to private user streams...
Traceback (most recent call last):
  File "/home/geraldhb/pr274/hummingbot/connector/exchange/huobi/huobi_api_user_stream_data_source.py", line 94, in _subscribe_channels
    await self._subscribe_topic(CONSTANTS.HUOBI_TRADE_DETAILS_TOPIC.format(exchange_symbol),
  File "/home/geraldhb/pr274/hummingbot/connector/exchange/huobi/huobi_api_user_stream_data_source.py", line 75, in _subscribe_topic
    raise ValueError(f"Error subscribing to topic: {topic}")
ValueError: Error subscribing to topic: trade.clearing#dogeusdt#0
```
[doge-usdt.zip](https://github.com/CoinAlpha/hummingbot/files/9222128/doge-usdt.zip)
[eth-usdt.zip](https://github.com/CoinAlpha/hummingbot/files/9222129/eth-usdt.zip)

2022-07-30 14:14 UTC, aarmoa commented
@gerald-hb Thank you for finding that issue. I pushed a fix that solves the problem and adds more details in the error log in case there are other issues

2022-08-01 02:15 UTC, rxlxrxsx commented
Tested on the latest commit. Although I don't see any error upon starting the strategy the bot is still not placing orders:

<img width="1423" alt="Screen Shot 2022-08-01 at 10 11 56 AM" src="https://user-images.githubusercontent.com/64377055/182059220-b56e99d3-5dca-40a1-97b5-5c3ba2d96d7b.png">

Logs and config: [huobi.zip](https://github.com/CoinAlpha/hummingbot/files/9230386/huobi.zip)

2022-08-01 04:18 UTC, aarmoa commented
@rxlxrxsx thank you for finding that issue. I think I was able to solve it. But unfortunately the account I have access to does not have enough balances to trade. Could you please give it a new try?

2022-08-01 05:12 UTC, rxlxrxsx commented
Upon checking the bot is still not placing orders on the latest commit:

<img width="1422" alt="Screen Shot 2022-08-01 at 1 09 25 PM" src="https://user-images.githubusercontent.com/64377055/182076559-be4c1eb7-e3d1-48ce-a7c4-721ff936a682.png">

Logs and config: [huobi_pmm.zip](https://github.com/CoinAlpha/hummingbot/files/9231066/huobi_pmm.zip)

2022-08-01 15:04 UTC, aarmoa commented
@rxlxrxsx I have fixed an issue in the trading rules parsing logic

2022-08-02 03:03 UTC, rxlxrxsx commented
Thanks @aarmoa I can confirm the bot is now placing orders properly. Ongoing testing..

2022-08-02 05:47 UTC, rxlxrxsx commented
Some observations found on the latest commit:

- After this error appeared it seems that it wasn't able to recover which leaves the orders open for several minutes. For this scenario I have the order_refresh_time set to 30 and order_refresh_tolerance_pct set to -1, with these setting normally these orders should be cancelled after 30 seconds. I noticed on the logs that the bot also encountered this error a few seconds earlier but it was able to recover after 5 seconds and was also able to successfully cancel the orders. See timestamp `2022-08-02 05:06:29,383` and `2022-08-02 05:07:50,308` in the log file attached for both scenarios of the error.

<img width="1424" alt="Screen Shot 2022-08-02 at 1 28 07 PM" src="https://user-images.githubusercontent.com/64377055/182300745-e1fd1da7-4fc3-4d2e-91e4-635307cf6214.png">

```python
2022-08-02 05:07:50,308 - 1694891 - hummingbot.connector.exchange.huobi.huobi_api_user_stream_data_source.HuobiAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/pr274/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 48, in listen_for_user_stream
    await self._process_websocket_messages(websocket_assistant=self._ws_assistant, queue=output)
  File "/home/ubuntu/pr274/hummingbot/connector/exchange/huobi/huobi_api_user_stream_data_source.py", line 101, in _process_websocket_messages
    async for ws_response in websocket_assistant.iter_messages():
  File "/home/ubuntu/pr274/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/pr274/hummingbot/core/web_assistant/connections/ws_connection.py", line 62, in receive
    msg = await self._process_message(msg)
  File "/home/ubuntu/pr274/hummingbot/core/web_assistant/connections/ws_connection.py", line 84, in _process_message
    msg = await self._check_msg_types(msg)
  File "/home/ubuntu/pr274/hummingbot/core/web_assistant/connections/ws_connection.py", line 89, in _check_msg_types
    msg = await self._check_msg_closed_type(msg)
  File "/home/ubuntu/pr274/hummingbot/core/web_assistant/connections/ws_connection.py", line 99, in _check_msg_closed_type
    raise ConnectionError(
ConnectionError: The WS connection was closed unexpectedly. Close code = 1000 msg data: None
```

- There was also one instance of this error but I didn't see any impact on the affected order

```python
2022-08-02 04:38:01,813 - 1694891 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - NETWORK - Error fetching status update for the order AAc484720aBEHUT1825cd8b02924b0e3f8b1e40f732130773677be7b11: 'NoneType' object is not subscriptable.
Traceback (most recent call last):
  File "/home/ubuntu/pr274/hummingbot/connector/exchange_py_base.py", line 918, in _update_orders
    order_update = await self._request_order_status(tracked_order=order)
  File "/home/ubuntu/pr274/hummingbot/connector/exchange/huobi/huobi_exchange.py", line 240, in _request_order_status
    new_state = CONSTANTS.ORDER_STATE[updated_order_data["data"]["state"]]
TypeError: 'NoneType' object is not subscriptable
```

Logs and config: [huobi_pmm.zip](https://github.com/CoinAlpha/hummingbot/files/9239342/huobi_pmm.zip)

2022-08-02 18:36 UTC, aarmoa commented
Hello @rxlxrxsx. I pushed a fix to avoid the error `'NoneType' object is not subscriptable` in the future.
Regarding the orders that were not cancelled until the bot was stopped, I could not find anything in the connector that could cause that behavior. But since the component in charge of deciding when to cancel orders is the strategy and not the connector, I think this should be an issue we should open for the strategy you were using during the test, if it happens regularly.

2022-08-02 20:12 UTC, gerald-hb commented
I will update our long term bots to the latest commit. We will monitor it for a few hours and will provide approval if no further issue found.

2022-08-03 07:55 UTC, rxlxrxsx commented
- Getting flooded by errors due to a lost order. Looking into the logs, it seems that it started after the bot tries to cancel the order, there were no `OrderCancelledEvent` that took place on the affected order upon further checking. We have 2 instances running at the same time and both instances were able to encounter the issue.

```python
## Order id in question 

AAc484720aSEHUT18261dbc4ee971b27370b685f2b68c670b2fd8e5a29

## Orders created

2022-08-03 03:59:29,346 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT18261dbc4ed971b27370b685f2b68c670b2fd8e5a29 for 0.0070 ETH-USDT.
2022-08-03 03:59:29,369 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0070", "price": "1620.63", "order_id": "AAc484720aSEHUT18261dbc4ed971b27370b685f2b68c670b2fd8e5a29", "creation_timestamp": 1659499169.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 03:59:29,370 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT18261dbc4eb971b27370b685f2b68c670b2fd8e5a29 for 0.0070 ETH-USDT.
2022-08-03 03:59:29,385 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0070", "price": "1613.36", "order_id": "AAc484720aBEHUT18261dbc4eb971b27370b685f2b68c670b2fd8e5a29", "creation_timestamp": 1659499169.0, "exchange_order_id": "599734170072780", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 03:59:29,386 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT18261dbc4ec971b27370b685f2b68c670b2fd8e5a29 for 0.0070 ETH-USDT.
2022-08-03 03:59:29,413 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0070", "price": "1612.55", "order_id": "AAc484720aBEHUT18261dbc4ec971b27370b685f2b68c670b2fd8e5a29", "creation_timestamp": 1659499169.0, "exchange_order_id": "599734170236997", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 03:59:29,621 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT18261dbc4ea971b27370b685f2b68c670b2fd8e5a29 for 0.0070 ETH-USDT.
2022-08-03 03:59:29,629 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0070", "price": "1614.17", "order_id": "AAc484720aBEHUT18261dbc4ea971b27370b685f2b68c670b2fd8e5a29", "creation_timestamp": 1659499169.0, "exchange_order_id": "599734127264745", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 03:59:29,687 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT18261dbc4ee971b27370b685f2b68c670b2fd8e5a29 for 0.0070 ETH-USDT.
2022-08-03 03:59:29,702 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0070", "price": "1621.44", "order_id": "AAc484720aSEHUT18261dbc4ee971b27370b685f2b68c670b2fd8e5a29", "creation_timestamp": 1659499169.0, "exchange_order_id": "None", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}

## Orders being canceled

2022-08-03 03:59:59,001 - 1701933 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT18261dbc4ea971b27370b685f2b68c670b2fd8e5a29. [clock=2022-08-03 03:59:59+00:00]
2022-08-03 03:59:59,002 - 1701933 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT18261dbc4eb971b27370b685f2b68c670b2fd8e5a29. [clock=2022-08-03 03:59:59+00:00]
2022-08-03 03:59:59,002 - 1701933 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT18261dbc4ec971b27370b685f2b68c670b2fd8e5a29. [clock=2022-08-03 03:59:59+00:00]
2022-08-03 03:59:59,002 - 1701933 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT18261dbc4ed971b27370b685f2b68c670b2fd8e5a29. [clock=2022-08-03 03:59:59+00:00]
2022-08-03 03:59:59,002 - 1701933 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT18261dbc4ee971b27370b685f2b68c670b2fd8e5a29. [clock=2022-08-03 03:59:59+00:00]

## Successfully canceled orders, notice that the order in question is not included

2022-08-03 03:59:59,527 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499199.0, "order_id": "AAc484720aBEHUT18261dbc4ea971b27370b685f2b68c670b2fd8e5a29", "exchange_order_id": "599734127264745", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 03:59:59,527 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT18261dbc4ea971b27370b685f2b68c670b2fd8e5a29.
2022-08-03 03:59:59,539 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499199.0, "order_id": "AAc484720aBEHUT18261dbc4eb971b27370b685f2b68c670b2fd8e5a29", "exchange_order_id": "599734170072780", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 03:59:59,540 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT18261dbc4eb971b27370b685f2b68c670b2fd8e5a29.
2022-08-03 03:59:59,550 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499199.0, "order_id": "AAc484720aSEHUT18261dbc4ed971b27370b685f2b68c670b2fd8e5a29", "exchange_order_id": "599734161376190", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 03:59:59,550 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aSEHUT18261dbc4ed971b27370b685f2b68c670b2fd8e5a29.
2022-08-03 03:59:59,858 - 1701933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659499199.0, "order_id": "AAc484720aBEHUT18261dbc4ec971b27370b685f2b68c670b2fd8e5a29", "exchange_order_id": "599734170236997", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 03:59:59,859 - 1701933 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT18261dbc4ec971b27370b685f2b68c670b2fd8e5a29.

## Errors that were being flooded

2022-08-03 04:00:00,453 - 1701933 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Failed to fetch trade updates for order AAc484720aSEHUT18261dbc4ee971b27370b685f2b68c670b2fd8e5a29. Error: invalid literal for int() with base 10: 'None'
2022-08-03 04:00:02,305 - 1701933 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Error fetching status update for the order AAc484720aSEHUT18261dbc4ee971b27370b685f2b68c670b2fd8e5a29: Erroneous order status response {'status': 'error', 'err-code': 'validation-format-error', 'err-msg': 'Format Error: order-id.', 'data': None}.
```

<img width="1423" alt="Screen Shot 2022-08-03 at 2 51 26 PM" src="https://user-images.githubusercontent.com/64377055/182553327-0a06e89b-aed7-4936-b0f3-0cb809238c9c.png">
<img width="1423" alt="Screen Shot 2022-08-03 at 2 50 59 PM" src="https://user-images.githubusercontent.com/64377055/182553333-bb5d9d88-4afc-4027-bc8c-af373612382d.png">

Logs and config: [huobi.zip](https://github.com/CoinAlpha/hummingbot/files/9249152/huobi.zip)

2022-08-03 13:55 UTC, aarmoa commented
@rxlxrxsx good catch. I found out an undocumented behavior of the connector. It is possible for them to reply to the order creation message without sending the exchange order id back. In those cases we have to consider that the order failed. I have updated the code to correctly consider this scenario.

2022-08-03 16:46 UTC, Deepali6997 commented
Can see that reported issue is now handled correctly by the bot.

Orders are created, cancelled properly and Successfully canceled orders message is shown correctly without leaving behind any order 

Order creation
```
2022-08-03 16:19:11,202 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT1826480fc19a190bdd5125f278496ce218abad86fa7 for 0.0060 ETH-USDT.
2022-08-03 16:19:11,214 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543551.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0060", "price": "1641.01", "order_id": "AAc484720aBEHUT1826480fc19a190bdd5125f278496ce218abad86fa7", "creation_timestamp": 1659543551.0, "exchange_order_id": "599740947174001", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 16:19:11,215 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT1826480fc1da190bdd5125f278496ce218abad86fa7 for 0.0060 ETH-USDT.
2022-08-03 16:19:11,226 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543551.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0060", "price": "1670.70", "order_id": "AAc484720aSEHUT1826480fc1da190bdd5125f278496ce218abad86fa7", "creation_timestamp": 1659543551.0, "exchange_order_id": "599741031583387", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 16:19:11,226 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT1826480fc1ca190bdd5125f278496ce218abad86fa7 for 0.0060 ETH-USDT.
2022-08-03 16:19:11,241 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543551.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0060", "price": "1654.21", "order_id": "AAc484720aSEHUT1826480fc1ca190bdd5125f278496ce218abad86fa7", "creation_timestamp": 1659543551.0, "exchange_order_id": "599741031583389", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 16:19:11,469 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order AAc484720aSEHUT1826480fc1ea190bdd5125f278496ce218abad86fa7 for 0.0060 ETH-USDT.
2022-08-03 16:19:11,479 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543551.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0060", "price": "1687.19", "order_id": "AAc484720aSEHUT1826480fc1ea190bdd5125f278496ce218abad86fa7", "creation_timestamp": 1659543551.0, "exchange_order_id": "599741014969262", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 16:19:11,481 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT1826480fc1aa190bdd5125f278496ce218abad86fa7 for 0.0060 ETH-USDT.
2022-08-03 16:19:11,497 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543551.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0060", "price": "1624.52", "order_id": "AAc484720aBEHUT1826480fc1aa190bdd5125f278496ce218abad86fa7", "creation_timestamp": 1659543551.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
2022-08-03 16:19:11,560 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order AAc484720aBEHUT1826480fc1ba190bdd5125f278496ce218abad86fa7 for 0.0060 ETH-USDT.
2022-08-03 16:19:11,571 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543551.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.0060", "price": "1608.03", "order_id": "AAc484720aBEHUT1826480fc1ba190bdd5125f278496ce218abad86fa7", "creation_timestamp": 1659543551.0, "exchange_order_id": "599741023325095", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi"}
```

cancelation

```
2022-08-03 16:20:01,001 - 1707818 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT1826480fc19a190bdd5125f278496ce218abad86fa7. [clock=2022-08-03 16:20:01+00:00]
2022-08-03 16:20:01,001 - 1707818 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT1826480fc1aa190bdd5125f278496ce218abad86fa7. [clock=2022-08-03 16:20:01+00:00]
2022-08-03 16:20:01,001 - 1707818 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aBEHUT1826480fc1ba190bdd5125f278496ce218abad86fa7. [clock=2022-08-03 16:20:01+00:00]
2022-08-03 16:20:01,001 - 1707818 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1826480fc1ca190bdd5125f278496ce218abad86fa7. [clock=2022-08-03 16:20:01+00:00]
2022-08-03 16:20:01,002 - 1707818 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1826480fc1da190bdd5125f278496ce218abad86fa7. [clock=2022-08-03 16:20:01+00:00]
2022-08-03 16:20:01,002 - 1707818 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order AAc484720aSEHUT1826480fc1ea190bdd5125f278496ce218abad86fa7. [clock=2022-08-03 16:20:01+00:00]
```

successful cancelation

```
2022-08-03 16:20:01,187 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543601.0, "order_id": "AAc484720aBEHUT1826480fc19a190bdd5125f278496ce218abad86fa7", "exchange_order_id": "599740947174001", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 16:20:01,187 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT1826480fc19a190bdd5125f278496ce218abad86fa7.
2022-08-03 16:20:01,244 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543601.0, "order_id": "AAc484720aBEHUT1826480fc1ba190bdd5125f278496ce218abad86fa7", "exchange_order_id": "599741023325095", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 16:20:01,245 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT1826480fc1ba190bdd5125f278496ce218abad86fa7.
2022-08-03 16:20:01,251 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543601.0, "order_id": "AAc484720aSEHUT1826480fc1ca190bdd5125f278496ce218abad86fa7", "exchange_order_id": "599741031583389", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 16:20:01,252 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aSEHUT1826480fc1ca190bdd5125f278496ce218abad86fa7.
2022-08-03 16:20:01,259 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543601.0, "order_id": "AAc484720aBEHUT1826480fc1aa190bdd5125f278496ce218abad86fa7", "exchange_order_id": "599741048721156", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 16:20:01,260 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aBEHUT1826480fc1aa190bdd5125f278496ce218abad86fa7.
2022-08-03 16:20:01,586 - 1707818 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659543601.0, "order_id": "AAc484720aSEHUT1826480fc1ea190bdd5125f278496ce218abad86fa7", "exchange_order_id": "599741014969262", "event_name": "OrderCancelledEvent", "event_source": "huobi"}
2022-08-03 16:20:01,586 - 1707818 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order AAc484720aSEHUT1826480fc1ea190bdd5125f278496ce218abad86fa7.
2022-08-03 16:20:01,596 - 1707818 - hum [...]

2022-08-03 16:47 UTC, Deepali6997 commented
Will let run the bot for few hours to capture the Warnings (if any)

2022-08-04 11:19 UTC, Deepali6997 commented
@aarmoa Have been running two bots and it can be seen that no scenario is detected where an order has been lost. 

However, both the bots showed Warning. This Warning was already reported by Rein previously. The good thing is that there is very less occurrence of it.

**bot 1 (only one time occurrence)**
`2022-08-04 04:20:01,532 - 1713259 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Error fetching status update for the order AAc484720aBEHUT1826714ed86747df232786bdbe7fe220983339107ef: Erroneous order status response {'status': 'error', 'err-code': 'validation-format-error', 'err-msg': 'Format Error: order-id.', 'data': None}.`

Although even after this behaviour, the order is successfully cancelled
<img width="1659" alt="Screenshot 2022-08-04 at 4 43 49 PM" src="https://user-images.githubusercontent.com/100112937/182833679-10d63048-ed34-460a-89dc-e2fd55ad5b7f.png">

**bot 2 (two times occurrence)**

`2022-08-03 23:04:01,820 - 1713275 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Error fetching status update for the order AAc484720aBEHUT18265f39ee96418008ddbcff978b569bcb665d4c20d: Erroneous order status response {'status': 'error', 'err-code': 'validation-format-error', 'err-msg': 'Format Error: order-id.', 'data': None}.`
<img width="1551" alt="Screenshot 2022-08-04 at 4 46 28 PM" src="https://user-images.githubusercontent.com/100112937/182834197-1d5266c6-47ba-4f6d-b59a-5ca0d59bff90.png">

`2022-08-04 08:14:02,868 - 1713275 - hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange - WARNING - Error fetching status update for the order AAc484720aBEHUT18267eb2d116418008ddbcff978b569bcb665d4c20d: Erroneous order status response {'status': 'error', 'err-code': 'validation-format-error', 'err-msg': 'Format Error: order-id.', 'data': None}.`
<img width="1641" alt="Screenshot 2022-08-04 at 4 47 06 PM" src="https://user-images.githubusercontent.com/100112937/182834293-8d3602e3-e4a3-4652-9f19-f65e65d18694.png">

2022-08-04 12:12 UTC, aarmoa commented
Hello @Deepali6997. Thank you for raising that issue. Would it be possible for you to share the database files (.sqlite that are inside of ./data) of those instances? There is always one DB file per each configuration, you will need to look for the one names as the configuration that was loaded when the bot was running

2022-08-04 12:17 UTC, Deepali6997 commented
@aarmoa here. Added all the necessary things in this support packet.

[PR274-support_packets.zip](https://github.com/CoinAlpha/hummingbot/files/9259538/PR274-support_packets.zip)

2022-08-04 19:04 UTC, gerald-hb commented
I will update our monitoring bots to the latest commit. We'll update here if we found more/any issues.

2022-08-05 07:39 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

- Connected API keys (valid and invalid key) and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a pure_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is in sync with the exchange
- Trade information are correct based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed hanging order/cancellation and multiple order levels works as expected
- Tested on other supported strategies as well and confirmed working
- Successfully built a docker image and create a docker instance
- Ran multiple bots using a single api key and confirmed working properly
- Ran multiple bots long term and confirmed no errors were found during it's run time

2022-08-05 17:20 UTC, closed without merging