Fix/time synchronizer and abandoned orders issue
CoinAlpha/hummingbot pull request #276
Opened 2022-07-13 20:29 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Change in the TimeSynchronizer logic to estimate timestamps giving more value to resent samples than older samples.
- Refactor in ExchangePyBase to move the TimeSynchronizer update logic into a separate loop that is executed more frequently than the status update loop for orders.
- Refactor in ExchangePyBase to include in the abstract class the common logic about order HTTP status update loop. By default it always tries now to not only get updates for the orders, but also check if there have been any order fills (trades) impacting them. All subclasses of ExchangePyBase have been updated to implement the required logic to get the order fills and order updates.
- Added logic in ClientOrderTracker to keep track of all the orders that are marked as failed because they have not been found in the exchange or there were errors retrieving updates from the exchange for them more times than the specified limit. These orders are called "lost orders".
- Added new loop task in ExchangePyBase class to regularly try to cancel all lost orders. The loop also tries to get updates for the orders (to find out when they are no longer alive in the server) and also requests order fill updates for them. This is a fall back functionality to avoid leaving stale orders alive in the exchange.

**Tests performed by the developer**:
Added unit tests for all new functionalities.
Tested the changes manually by running a PMM strategy connected with Binance and operating with ETH-DAI

**Tips for QA testing**:
Test that new client instances started with the new version do not leave orders alive in the server after removing them in the bot list of active orders. Initially please test these with Binance.
We should also see less issues in Binance strategies execution related to request being rejected due to an invalid timestamp.
Please also run a quick validation that all connectors implemented as subclasses of ExchangePyBase still can be used without problems:
- Kucoin
- OKX
- GateIO
- Bitmart

[sc-29025]

2022-07-14 04:16 UTC, RC-13 commented
Currently running a long term test bot for all the connectors mentioned above.

2022-07-14 07:59 UTC, rxlxrxsx commented
- Intermittently getting this warning while running a bot on OKX, despite the message there were no stuck orders upon checking on the exchange website.

<img width="1421" alt="Screen Shot 2022-07-14 at 2 52 49 PM" src="https://user-images.githubusercontent.com/64377055/178932095-6355cc06-f156-46aa-b377-c799ca21f0a3.png">

```python
2022-07-14 14:52:00,038 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch trade updates for order 93027a12dac34fBCBEHUT181fb7a7aca. Error: Error executing request GET https://www.okx.com/api/v5/trade/fills. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}
2022-07-14 14:52:00,109 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch trade updates for order 93027a12dac34fBCSEHUT181fb7a7acb. Error: Error executing request GET https://www.okx.com/api/v5/trade/fills. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}
2022-07-14 14:52:00,197 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch trade updates for order 93027a12dac34fBCBEHUT181fb7a01b2. Error: Error executing request GET https://www.okx.com/api/v5/trade/fills. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}
2022-07-14 14:52:00,266 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch trade updates for order 93027a12dac34fBCSEHUT181fb7a01b3. Error: Error executing request GET https://www.okx.com/api/v5/trade/fills. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}
2022-07-14 14:52:00,357 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error fetching status update for the order 93027a12dac34fBCBEHUT181fb7a7aca: Error executing request GET https://www.okx.com/api/v5/trade/order. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}.
2022-07-14 14:52:00,357 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch status update for the order 93027a12dac34fBCBEHUT181fb7a7aca.
2022-07-14 14:52:00,438 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error fetching status update for the order 93027a12dac34fBCSEHUT181fb7a7acb: Error executing request GET https://www.okx.com/api/v5/trade/order. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}.
2022-07-14 14:52:00,438 - 23332 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch status update for the order 93027a12dac34fBCSEHUT181fb7a7acb.
```

Logs and config: [okx_files.zip](https://github.com/CoinAlpha/hummingbot/files/9109778/okx_files.zip)

2022-07-14 11:31 UTC, petioptrv requested changes
I've left some mostly clean up suggestions

2022-07-14 11:31 UTC, petioptrv commented on hummingbot/connector/test_support/exchange_connector_test.py
> +                order_id="OID1",
```suggestion
                order_id=self.expected_exchange_order_id,
```

2022-07-14 11:31 UTC, petioptrv commented on hummingbot/connector/test_support/exchange_connector_test.py
> +            order = self.exchange.in_flight_orders["OID1"]
```suggestion
            order = self.exchange.in_flight_orders[self.expected_exchange_order_id]
```

2022-07-14 11:31 UTC, petioptrv commented on hummingbot/connector/test_support/exchange_connector_test.py
> +                order_id="OID1",
```suggestion
                order_id=self.expected_exchange_order_id,
```

2022-07-14 11:31 UTC, petioptrv commented on hummingbot/connector/test_support/exchange_connector_test.py
> +            order = self.exchange.in_flight_orders["OID1"]
```suggestion
            order = self.exchange.in_flight_orders[self.expected_exchange_order_id]
```

2022-07-14 13:58 UTC, aarmoa commented on hummingbot/connector/exchange/okx/okx_exchange.py
> +                    flat_fees=[TokenAmount(amount=Decimal(fill_data["fee"]), token=fill_data["feeCcy"])]
I don't see "fillFee" and "fillFeeCcy" as fields in the documented response message https://www.okx.com/docs-v5/en/#rest-api-trade-get-transaction-details-last-3-days

2022-07-14 13:59 UTC, aarmoa commented on hummingbot/connector/test_support/exchange_connector_test.py
> +                order_id="OID1",
`expected_exchange_order_id` should only be used for exchange_order_id field, not for the client_order_id

2022-07-14 14:00 UTC, aarmoa commented on hummingbot/connector/test_support/exchange_connector_test.py
> +            order: InFlightOrder = self.exchange.in_flight_orders["OID1"]
Same comment as before, we should not use the expected_exchange_order_id as client_order_id

2022-07-14 15:02 UTC, aarmoa commented on hummingbot/connector/test_support/exchange_connector_test.py
> +                order_id="OID1",
Same comment here

2022-07-14 21:20 UTC, RC-13 commented
Randomly seeing the following error in some of the bots we setup (binance, kucoin, and oks). Despite this error, there are not stuck orders. We will continue to monitor if this will persist in the new commits.
```
2022-07-14 17:34:01,472 - 1422641 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error fetching status update for the order 93027a12dac34fBCBEHUT181fdc564cc: Error executing request GET https://www.okx.com/api/v5/trade/order. HTTP status is 401. Error: {"msg":"Invalid Sign","code":"50113"}.
2022-07-14 17:34:01,472 - 1422641 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to fetch status update for the order 93027a12dac34fBCBEHUT181fdc564cc.
2022-07-14 17:34:01,472 - 1422641 - hummingbot.connector.client_order_tracker - DEBUG - Order is not/no longer being tracked (93027a12dac34fBCBEHUT181fdc564cc)
2022-07-14 17:34:01,473 - 1422641 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/okx/hummingbot/connector/exchange_py_base.py", line 760, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/ubuntu/okx/hummingbot/connector/exchange_py_base.py", line 892, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/ubuntu/okx/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/okx/hummingbot/connector/exchange_py_base.py", line 951, in _update_order_status
    await self._update_orders()
  File "/home/ubuntu/okx/hummingbot/connector/exchange_py_base.py", line 917, in _update_orders
    for client_order_id, order in self.in_flight_orders.items():
RuntimeError: dictionary changed size during iteration
2022-07-14 17:34:01,474 - 1422641 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Could not fetch account updates from Okx. Check API key and network connection.
```
[runtime-error.zip](https://github.com/CoinAlpha/hummingbot/files/9115540/runtime-error.zip)

2022-07-15 01:06 UTC, RC-13 commented
In the latest commit, I'm seeing random instances wherein an order in Binance is canceled with delay. My test bot has been running for 1 hr 30 min and this occurred 16 times. For example, order_ID: `XEKWYICXSAOUT181ff472eaeafb09a`is expected to cancel after 9s but remain active for a minute.
![image](https://user-images.githubusercontent.com/57189990/179123976-6ca99c85-11e2-44e9-b28f-f3eacbc05c61.png)
![image](https://user-images.githubusercontent.com/57189990/179124019-fdf66aa1-6d58-40fe-b5e6-d536ec11605c.png)
```python
2022-07-15 08:35:01,012 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXBAOUT181ff472ea5afb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXBAOUT181ff472ea6afb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXBAOUT181ff472ea7afb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXBAOUT181ff472ea8afb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXBAOUT181ff472ea9afb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXSAOUT181ff472eaaafb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXSAOUT181ff472eabafb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXSAOUT181ff472eacafb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXSAOUT181ff472eadafb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,014 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXSAOUT181ff472eaeafb09a. [clock=2022-07-15 00:35:01+00:00]
2022-07-15 08:35:01,176 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXBAOUT181ff472ea5afb09a", "exchange_order_id": "1239041844", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,180 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAOUT181ff472ea5afb09a.
2022-07-15 08:35:01,446 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXSAOUT181ff472eabafb09a", "exchange_order_id": "1239041841", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,451 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXSAOUT181ff472eabafb09a.
2022-07-15 08:35:01,451 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXSAOUT181ff472eaaafb09a", "exchange_order_id": "1239041837", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,454 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXSAOUT181ff472eaaafb09a.
2022-07-15 08:35:01,454 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXBAOUT181ff472ea9afb09a", "exchange_order_id": "1239041839", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,456 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAOUT181ff472ea9afb09a.
2022-07-15 08:35:01,457 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXBAOUT181ff472ea8afb09a", "exchange_order_id": "1239041836", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,459 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAOUT181ff472ea8afb09a.
2022-07-15 08:35:01,459 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXBAOUT181ff472ea6afb09a", "exchange_order_id": "1239041840", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,462 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAOUT181ff472ea6afb09a.
2022-07-15 08:35:01,462 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXSAOUT181ff472eadafb09a", "exchange_order_id": "1239041842", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,464 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXSAOUT181ff472eadafb09a.
2022-07-15 08:35:01,464 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXBAOUT181ff472ea7afb09a", "exchange_order_id": "1239041838", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,466 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAOUT181ff472ea7afb09a.
2022-07-15 08:35:01,503 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845301.0, "order_id": "x-XEKWYICXSAOUT181ff472eacafb09a", "exchange_order_id": "1239041846", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-15 08:35:01,524 - 9579 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXSAOUT181ff472eacafb09a.
2022-07-15 08:35:25,916 - 9579 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - Failed to cancel order x-XEKWYICXSAOUT181ff472eaeafb09a
Traceback (most recent call last):
  File "/Users/clintg/testing/time-sync/hummingbot/connector/exchange_py_base.py", line 508, in _execute_order_cancel
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/Users/clintg/testing/time-sync/hummingbot/connector/exchange/binance/binance_exchange.py", line 191, in _place_cancel
    cancel_result = await self._api_delete(
  File "/Users/clintg/testing/time-sync/hummingbot/connector/exchange_py_base.py", line 861, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/Users/clintg/testing/time-sync/hummingbot/connector/exchange_py_base.py", line 878, in _api_request
    return await rest_assistant.execute_request(
  File "/Users/clintg/testing/time-sync/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request DELETE https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2022-07-15 08:36:02,008 - 9579 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ALGO-USDT) Canceling the limit order x-XEKWYICXSAOUT181ff472eaeafb09a. [clock=2022-07-15 00:36:02+00:00]
2022-07-15 08:36:02,172 - 9579 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657845362.0, "order_id": "x-XEKWYICXSAOUT181ff472eaeafb09a", "exchange_order_id": "1239041843", "event_name": "OrderCancelledEvent", "event_source": "binance"}

# it took 1 min [...]

2022-07-15 15:54 UTC, aarmoa commented
Thank you for the details @RC-13. I have pushed a change in the code to try a different approach to keep the time synchronizer updated. Would it be possible to QA to verify if with this new code there are less rejected requests in Binance due to wrong timestamps?

2022-07-16 06:10 UTC, gerald-hb commented
Test bots are running 10 hours. So far, no stuck orders, duplicate orders or cancellation issue observed. We will to continue to monitor this and will report back if we find any issue related to this PR.

2022-07-18 03:22 UTC, RC-13 commented
Testing update: For 2 days, our binance test bot encounter 16 instance of `Timestamp for this request was 1000ms ahead of the server's time.` (lesser compared before). During this event, server disconnect took place causing some orders to get cancel with delay. Example order_ID `x- XEKWYICXSAXUT1820905b04cbf8b5b` 
```python
2022-07-16 21:59:07,611 - 1466831 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order x-XEKWYICXSAXUT1820905b04cbf8b5b for 62.00000000 ADX-USDT.
2022-07-16 21:59:07,630 - 1466831 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658008745.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ADX-USDT", "amount": "62.00000000", "price": "0.18330000", "order_id": "x-XEKWYICXSAXUT1820905b04cbf8b5b", "creation_timestamp": 1658008744.0, "exchange_order_id": "46762057", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2022-07-16 21:59:07,630 - 1466831 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order x-XEKWYICXSAXUT1820905b04bbf8b5b for 62.00000000 ADX-USDT.
2022-07-16 21:59:07,639 - 1466831 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658008745.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ADX-USDT", "amount": "62.00000000", "price": "0.18310000", "order_id": "x-XEKWYICXSAXUT1820905b04bbf8b5b", "creation_timestamp": 1658008744.0, "exchange_order_id": "46762058", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2022-07-16 21:59:07,639 - 1466831 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order x-XEKWYICXSAXUT1820905b04ebf8b5b for 62.00000000 ADX-USDT.
2022-07-16 21:59:07,646 - 1466831 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658008745.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ADX-USDT", "amount": "62.00000000", "price": "0.18360000", "order_id": "x-XEKWYICXSAXUT1820905b04ebf8b5b", "creation_timestamp": 1658008744.0, "exchange_order_id": "46762059", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2022-07-16 21:59:07,646 - 1466831 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order x-XEKWYICXSAXUT1820905b04dbf8b5b for 62.00000000 ADX-USDT.
2022-07-16 21:59:07,665 - 1466831 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658008745.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ADX-USDT", "amount": "62.00000000", "price": "0.18350000", "order_id": "x-XEKWYICXSAXUT1820905b04dbf8b5b", "creation_timestamp": 1658008744.0, "exchange_order_id": "46762060", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2022-07-16 21:59:15,778 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXBAXUT1820905b049bf8b5b. [clock=2022-07-16 21:59:12+00:00]
2022-07-16 21:59:15,792 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04bbf8b5b. [clock=2022-07-16 21:59:12+00:00]
2022-07-16 21:59:15,793 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04cbf8b5b. [clock=2022-07-16 21:59:12+00:00]
2022-07-16 21:59:15,793 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04dbf8b5b. [clock=2022-07-16 21:59:12+00:00]
2022-07-16 21:59:15,793 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04ebf8b5b. [clock=2022-07-16 21:59:12+00:00]
2022-07-16 22:00:25,892 - 1466831 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1658008756.0, "order_id": "x-XEKWYICXBAXUT1820905b049bf8b5b", "exchange_order_id": "46762056", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2022-07-16 22:00:25,897 - 1466831 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAXUT1820905b049bf8b5b.
2022-07-16 22:00:26,775 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04bbf8b5b. [clock=2022-07-16 22:00:26+00:00]
2022-07-16 22:00:26,782 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04cbf8b5b. [clock=2022-07-16 22:00:26+00:00]
2022-07-16 22:00:26,782 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04dbf8b5b. [clock=2022-07-16 22:00:26+00:00]
2022-07-16 22:00:26,782 - 1466831 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ADX-USDT) Canceling the limit order x-XEKWYICXSAXUT1820905b04ebf8b5b. [clock=2022-07-16 22:00:26+00:00]
2022-07-16 22:01:02,671 - 1466831 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - Failed to cancel order x-XEKWYICXSAXUT1820905b04bbf8b5b
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/binance/hummingbot/connector/exchange_py_base.py", line 512, in _execute_order_cancel
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/ubuntu/binance/hummingbot/connector/exchange/binance/binance_exchange.py", line 197, in _place_cancel
    cancel_result = await self._api_delete(
  File "/home/ubuntu/binance/hummingbot/connector/exchange_py_base.py", line 866, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/home/ubuntu/binance/hummingbot/connector/exchange_py_base.py", line 886, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/ubuntu/binance/hummingbot/core/web_assistant/rest_assistant.py", line 67, in execute_request
    response = await self.call(request=request, timeout=timeout)
  File "/home/ubuntu/binance/hummingbot/core/web_assistant/rest_assistant.py", line 84, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/binance/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/pyth [...]

2022-07-18 03:49 UTC, aarmoa commented
@RC-13 thank you for your feedback. It is proving to be difficult removing all issues related with the TimeSynchronizer. Since this issue is related to the stale/hanging orders left in the exchanges I think we should proceed with the fix if there are no more hanging orders and the frequency of TimeSynchronizer problems has been reduced.
Regarding the disconnections that happened during your tests, according to the logs they were generated by the exchange and not because of problems in the client. We can't do anything in those cases but reconnect and retry the actions.
Under the current conditions, do you think this PR can be merged?

2022-07-18 04:02 UTC, RC-13 commented
Hello @aarmoa I agree merging the fix since there has been a a lot of improvement base on the result of the long term test bot.

2022-07-18 04:11 UTC, RC-13 approved these changes
LGTM!

Test summary:
- Install the feature branch without issue
-  Start the client and setup a PMM strategy with multiple order levels using Binance, Bitmart, Gate_io, KuCoin, and OKX connector.
- Desynchronise  local machine time by adjust the time to a later time or advance from the current time.
-  Monitor the strategy creation and cancelation: orders are getting canceled and created without issue
- Run the test bot for several hours - initially a cancelation issue were reported and had been addressed.
- Run a long term test bot ( run for more than 2 days)
-  Review the logs: Binance still get server time error but it was greatly reduce and no hanging orders created.
- Other exchange had a cancelation error but due to an order getting filed which is expected

2022-07-18 14:54 UTC, petioptrv approved these changes
Left a suggestion for code cleanup, but otherwise the changes LGTM

2022-07-18 14:54 UTC, petioptrv commented on hummingbot/connector/exchange_py_base.py
> +        for retry_count in range(1, 3):
```suggestion
        for _ in range(2):
```

2022-07-20 03:42 UTC, aarmoa commented
I have just pushed a change to solve the merging issues with the current development branch. No need to retest or review again.

2022-07-20 03:49 UTC, aarmoa commented
Closing the PR after creating it in the Hummingbot Foundation repository https://github.com/hummingbot/hummingbot/pull/5518

2022-07-20 03:49 UTC, closed without merging