(feat) Update Gateway endpoints & parameter formats
CoinAlpha/hummingbot pull request #2905
Opened 2021-02-01 11:22 UTC by sdgoh

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Add protocols swap pool caching on start
- Refactor Gateway API endpoints
- Update request param data to use token symbol instead of contract address look up

2021-03-16 20:43 UTC, vic-en requested changes
Aside this suggestions, both `initiate_pool_task` and `auto_approve_task` basically do the same thing in a slightly different way. We should agree on one and remove the other.
Aside that, the rest of the changes LGTM.

2021-03-16 20:43 UTC, vic-en commented on hummingbot/strategy/amm_arb/amm_arb.py
> +            mid_price = float((buy_price + sell_price) / 2) if '-' not in [buy_price, sell_price] else '-'
```suggestion
            buy_price = Decimal(str(buy_price)) if buy_price is not None else '-'
            sell_price = Decimal(str(sell_price)) if sell_price is not None else '-'
            mid_price = ((buy_price + sell_price) / 2) if '-' not in [buy_price, sell_price] else '-'
```

2021-03-16 20:43 UTC, vic-en commented on hummingbot/strategy/amm_arb/data_types.py
> +        return profit_percentage
```suggestion
        return ((sell_gained_net - buy_spent_net) / buy_spent_net) if buy_spent_net != s_decimal_0 else s_decimal_0
```

2021-03-17 03:26 UTC, sdgoh commented on hummingbot/connector/connector/balancer/balancer_connector.py
> +
I'll remove this call to update the balance as the Gateway will be updating the on-chain balance.

2021-03-31 08:58 UTC, PtrckM approved these changes
Test and confirmed working by QA Team.

2021-03-31 09:10 UTC, PtrckM commented
@sdgoh @vic-en 
- `ethereum_token_list_url` still configurable on client via `config ethereum_token_list_url` and on `conf_global.yml`, these values are already set on `.env` via source and `gateway.env` via docker from gateway side.
- xdai provider on `./create-gateway.sh` is not configurable.

2021-03-31 10:24 UTC, vic-en commented
>     * ./create-gateway.s

- The ethereum token list on client is there to prevent the client from blocking on startup.
- I pushed a commit to make XDAI rpc provider configurable. Kindly confirm.

2021-03-31 10:31 UTC, PtrckM approved these changes
No more issues encountered during testing. Confirmed working by QA.

2021-03-31 19:53 UTC, vic-en approved these changes
LGTM

2021-03-31 20:43 UTC, vic-en approved these changes
LGTM

2021-03-31 20:43 UTC, merged