Feat/ add CI-EX connector
CoinAlpha/hummingbot pull request #292
Opened 2022-12-20 09:51 UTC by CrimsonJacket

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds CI-EX connector into Foundation

[sc- 35018]

**Tests performed by the developer**:
Modified `ExchangePyBase` to allow for connectors that lacks `UserStreamDataSource`.
Adds all connector components for CI-EX

**Tips for QA testing**:
Ensure that the connector runs as intended.

Note: CI-EX API does not support any private user streams, as such it is expected that order and trade updates are not received immediately.

2022-12-20 11:53 UTC, Deepali6997 commented
testrun : https://hummingbot.testrail.io/index.php?/runs/view/3201

2022-12-21 06:13 UTC, RC-13 approved these changes
LGTM

Test summary:
        * Install feature branch without issue
        * Start the client
        * Add an API key (invalid and valid key): Ok
        * Balance check: Ok
        * Create a PMM strategy and confirmed market list is shown
        * Started the strategy without any issue - close linked GitHub ticket
        * Data integrity: OK
        * Order creation and cancelation: Ok, however we have an expected behavior wherein we can experience delay as we send request using HTTP request.
        * Enable multiple order levels: Ok
        * Enable hanging orders: Ok
        * Setup multiple bot (2 bot on this test due to limited test asset): Ok
        * Create a basic TWAP strategy using CIEX connector and start: Ok
        * Build a docker image and start a docker instance
        * Run a basic PMM strategy using CIEX connector

2022-12-22 21:03 UTC, aarmoa requested changes

2022-12-22 22:22 UTC, CrimsonJacket commented on hummingbot/connector/exchange/ciex/ciex_exchange.py
> +        }
Removed

2022-12-22 22:23 UTC, CrimsonJacket commented on hummingbot/connector/exchange/ciex/ciex_exchange.py
> +        ) and CONSTANTS.ORDER_NOT_EXIST_MESSAGE in str(status_update_exception)
Removed.

2022-12-22 22:24 UTC, CrimsonJacket commented on test/hummingbot/connector/exchange/ciex/test_ciex_exchange.py
> +    # TODO: Add tests that updates the order statuses when a subsequent order status update interval is reached
No, I was implementing it, but realised that it was essentially covered by existing unit tests in `ExchangeConnectorTests`

2022-12-23 13:24 UTC, aarmoa approved these changes

2022-12-26 13:11 UTC, CrimsonJacket commented
Closing this PR. I've created another PR on Foundation [here](https://github.com/hummingbot/hummingbot/pull/5959)

2022-12-26 13:11 UTC, closed without merging