Fix/ Ascend Ex order book mismatched
CoinAlpha/hummingbot pull request #3464
Opened 2021-05-31 09:08 UTC by Nullably

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Sort bids and asks on order book message
- Send pong on web socket when received ping msg

2021-05-31 09:35 UTC, CrimsonJacket commented on hummingbot/connector/exchange/ascend_ex/ascend_ex_order_book_tracker.py
> +                    order_book.apply_diffs(message.bids, message.asks, message.update_id)
`apply_diffs()` expects bids and asks to be `List[OrderBookRow]`. I have yet to test it myself, but I am expecting an error when accessing the `update_id` attribute in the `OrderBookRow`

2021-05-31 09:35 UTC, CrimsonJacket commented on hummingbot/connector/exchange/ascend_ex/ascend_ex_order_book_tracker.py
> +                    order_book.apply_snapshot(message.bids, message.asks, message.update_id)
Similar for `apply_snapshot()` it expects bids and asks to be `List[OrderBookRow]`

2021-05-31 09:37 UTC, CrimsonJacket requested changes
~~`apply_diffs()` and `apply_snapshot()` in `OrderBook` expects the bids and asks parameters to be `List[OrderBookRow]`. I assume this will result in an error when accessing the `update_id` attribute in the `OrderBookRow`~~

2021-05-31 09:42 UTC, CrimsonJacket approved these changes
Ignore my previous review. I did not catch that you've made the changes to `AscendExOrderBookMessage`

2021-06-01 03:09 UTC, rxlxrxsx approved these changes
Tested and confirmed fixed by QA.

2021-06-01 09:31 UTC, merged