Adds size to profit taking logic.
CoinAlpha/hummingbot pull request #3518
Opened 2021-06-05 19:41 UTC by petioptrv

This PR addresses issue #3452.

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Simply adds a size check when considering if an existing profit taking order should be cancelled and re-submitted.

2021-07-08 06:16 UTC, dennisocana commented
Thanks @petioptrv, we'll have our development team review.

2021-08-11 10:04 UTC, rapcmia commented
Tested using Binance testnet, the bot won't create profit-taking orders until it meets the set order_amount. Upon creating initial orders, partially filled buy and the sell order got canceled. The bot then opens a position but did not create for profit-take order. Waited for more than 3mins, then filled the remaining balance and the bot created the profit-take order.

Here is one of the instances recorded for reference: 

https://user-images.githubusercontent.com/73840223/129008989-79beea57-bef0-4bb6-9974-d9cf4fc48e20.mp4

While testing, I've encountered this error but it's a hit and miss (still trying to reproduce and reported in case it happens) when I tried to do a partial fill. The bot created order since it managed to meet the order amount but getting an `unexpected error running clock-tick` with ` object has no attribute 'size'`

![Test-01 - Partially filled with 5 and eventually the rmaining got filled  POS and take-profit created but getting clock-tick error](https://user-images.githubusercontent.com/73840223/129009834-71ead268-caa4-47de-a337-5335b818efc9.PNG)

```
2021-08-11 15:51:59,002 - 11296 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\\core\\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\\strategy\\perpetual_market_making\\perpetual_market_making.pyx", line 603, in hummingbot.strategy.perpetual_market_making.perpetual_market_making.PerpetualMarketMakingStrategy.c_tick
    self.c_manage_positions(session_positions)
  File "hummingbot\\strategy\\perpetual_market_making\\perpetual_market_making.pyx", line 613, in hummingbot.strategy.perpetual_market_making.perpetual_market_making.PerpetualMarketMakingStrategy.c_manage_positions
    proposals = self.c_profit_taking_feature(mode, session_positions)
  File "hummingbot\\strategy\\perpetual_market_making\\perpetual_market_making.pyx", line 661, in hummingbot.strategy.perpetual_market_making.perpetual_market_making.PerpetualMarketMakingStrategy.c_profit_taking_feature
    (o.price != price or o.size != size)
AttributeError: 'hummingbot.core.data_type.limit_order.LimitOrder' object has no attribute 'size'
```

Also, just a query about the unfilled order on partially filled instances, what will happen if the unfilled order did not get the opportunity to be filled? would it just stay hanging? thank you

2021-08-11 12:55 UTC, vic-en requested changes

2021-08-11 12:55 UTC, vic-en commented on hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx
> +                        (o.price != price or o.size != size)
```suggestion
                        (o.price != price or o.quantity != size)
```
Limit orders only has `quantity` property `filled_quantity` to check initial size of order and filled size respectively.
I'll suggest we don't bring in this complexity for several reasons.
I'll get back with more suggestion(s) on how we can solve the problem.

2021-08-14 06:29 UTC, PtrckM commented
- after triggering stop loss order bot no longer creates new set of orders
![image](https://user-images.githubusercontent.com/54516858/129436210-b7efdca3-cbc0-40ce-9a28-a251f18faf9c.png)
![image](https://user-images.githubusercontent.com/54516858/129436405-f8c547d4-c17d-4992-803a-809662d94551.png)

- logs and config
[perpmm.zip](https://github.com/CoinAlpha/hummingbot/files/6986020/perpmm.zip)

2021-08-16 04:28 UTC, petioptrv commented
> * after triggering stop loss order bot no longer creates new set of orders
>   ![image](https://user-images.githubusercontent.com/54516858/129436210-b7efdca3-cbc0-40ce-9a28-a251f18faf9c.png)
>   ![image](https://user-images.githubusercontent.com/54516858/129436405-f8c547d4-c17d-4992-803a-809662d94551.png)
> * logs and config
>   [perpmm.zip](https://github.com/CoinAlpha/hummingbot/files/6986020/perpmm.zip)

Thank you for testing @PtrckM! This bug has already a separate associated issue #3710 that I am currently working on

2021-08-17 04:08 UTC, petioptrv commented
> Also, just a query about the unfilled order on partially filled instances, what will happen if the unfilled order did not get the opportunity to be filled? would it just stay hanging? thank you

@rapcmia just re-read the messages on this thread and saw I missed your question. Yes, the order is a profit-taker and it will remain open until filled. Thank you

2021-08-18 05:51 UTC, RC-13 approved these changes
Confirming that the order amount is adjusted accordingly if partial fills have taken place and the entry price is calculated correctly.

2021-08-19 13:22 UTC, vic-en approved these changes
LGTM

2021-08-19 13:42 UTC, merged