(feat) Adds request rate limit throttling to Injective Perpetual
CoinAlpha/hummingbot pull request #353
Opened 2023-05-03 08:48 UTC by petioptrv

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR introduces rate limiting for Injective perpetual connector SDK calls.

**Tests performed by the developer**:

Manually tested that the connector works after the introduction of the changes.

**Tips for QA testing**:

Please test  the connector's operation for several cycles (at least 5m) with several order levels. The rate limits are on 1s basis, so we really just need to make sure that the rate limits are not impairing the connector's operation during any periods of high requests, like during the status polling loop.

2023-05-03 19:47 UTC, aarmoa requested changes

2023-05-03 19:47 UTC, aarmoa commented on hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_constants.py
> +MINUTE = 60
Please use the globals in hummingbot.connector.constants instead of defining them here

2023-05-04 04:49 UTC, mrhzysbl commented
Test run: https://hummingbot.testrail.io/index.php?/runs/view/4291&group_by=cases:section_id&group_order=asc

2023-05-04 12:52 UTC, aarmoa approved these changes
Changes look good to me

2023-05-05 17:16 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

- Connected API keys and confirmed working as expected
- Confirmed wallet and exchange balances are reflecting correct
- Created a perpetual_mm strategy and went through initial prompts successfully
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Confirmed order book prices is in sync with the exchange
- Confirmed positions are detected whenever it’s opened or closed
- Confirmed funding payment is being received by the bot
- Trade information are correct based on history command output
- Compared trades in client and exchange, no discrepancies found
- Confirmed running on multiple order levels works as expected

2023-05-06 19:04 UTC, petioptrv commented
Closing to re-open towards foundation

2023-05-06 19:04 UTC, closed without merging