Feat/disable profitability trigger
CoinAlpha/hummingbot pull request #3706
Opened 2021-07-09 09:17 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fees in profitability calculation is not done more accurately.
Trigger to remove position is now based on farthest inactive position. i.e Profitability as the basis for removing position is now removed.

2021-07-10 05:21 UTC, PtrckM commented
After creating buy and sell position price range:
- unable to display `status` command
```
2021-07-10 04:50:58,947 - 32519 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/client/command/status_command.py", line 135, in status_check_all
    self._notify(await self.strategy_status())
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/client/command/status_command.py", line 77, in strategy_status
    st_status = await self.strategy.format_status()
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py", line 199, in format_status
    pos_profitability_df = self.profitability_df()
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py", line 165, in profitability_df
    profit_data = self.calculate_profitability(position)
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py", line 146, in calculate_profitability
    tx_fee = sum(position.tx_fees)
```

![image](https://user-images.githubusercontent.com/54516858/125152629-5ef35180-e180-11eb-88cc-a16028855b9b.png)

- the TokenID doesn't display on the right pane
  - even though its a successful creation https://etherscan.io/tx/0x091f5401e9e0ef8ab12e6a84c5012e80ebc9e01f77fb09b7d54adc6d4facd04b https://etherscan.io/tx/0xf6513ca04c5429bcbc556fa373e9f148cea7d434cd9545d8fde46ce9d7a49c6b
![image](https://user-images.githubusercontent.com/54516858/125152536-b04f1100-e17f-11eb-9db1-daadfe9a1649.png)
![image](https://user-images.githubusercontent.com/54516858/125152658-a5e14700-e180-11eb-9b8c-5e0aaacd6423.png)

- operation error started to show as well `/eth/uniswap/v3/remove-position`
```
2021-07-10 04:50:59,957 - 32519 - hummingbot.connector.connector.uniswap.uniswap_connector - NETWORK - Error removing range position, token_id: None, hb_id: DAI-USDC-1625892619873558
Traceback (most recent call last):
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/connector/connector/uniswap_v3/uniswap_v3_connector.py", line 448, in _remove_position
    result = await self._api_request("post",
  File "/home/ubuntu/uni_v3_ite-2/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 591, in _api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}.{err_msg}")
OSError: Error fetching data from https://localhost:5123/eth/uniswap/v3/remove-position. HTTP status is 500. Message: Operation Error
2021-07-10 04:50:59,962 - 32519 - hummingbot.connector.connector.uniswap.uniswap_connector - WARNING - Error fetching data from https://localhost:5123/eth/uniswap/v3/remove-position. HTTP Status is 500. Message: Operation Error
2021-07-10 04:50:59,963 - 32519 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1625892659.0, "hb_id": "DAI-USDC-1625892619873558", "event_name": "RangePositionFailureEvent", "event_source": "uniswap_v3"}
```

When using amm_arb
- uniswap keep initializing for USDC-WETH even though I'm running balancer <-> binance with DAI-USDC <-> USDC-USDT
  - PS: no amm_arb uniswap yet created. Also showing on development/staging branch (does not happen before)

![image](https://user-images.githubusercontent.com/54516858/125151689-90691e80-e17a-11eb-9df3-65fa06f0a723.png)

2021-07-12 02:08 UTC, Nullably requested changes

2021-07-12 02:08 UTC, Nullably commented on hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py
>      def range_position_remover(self):
This should be named with fn naming convention e.g. `remove_farthest_position`.

2021-07-12 02:08 UTC, Nullably commented on hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py
> +                farthest_position = position if farthest_position is None else position
This `if` expression doesn't make sense as it always returns position regardless.

2021-07-12 02:08 UTC, Nullably commented on hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py
> +                farthest_position = position if position.lower_price > farthest_position.lower_price else position
Same with above.

2021-07-12 02:08 UTC, Nullably commented on hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py
> +                farthest_position = position if farthest_position is None else position
same with above.

2021-07-12 02:08 UTC, Nullably commented on hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp.py
> +                farthest_position = position if position.upper_price < farthest_position.upper_price else position
same with above.

2021-07-12 10:43 UTC, vic-en commented on hummingbot/connector/connector/uniswap_v3/uniswap_v3_connector.py
> +    async def _remove_position(self, hb_id: str, token_id: str, reducePercent: Decimal, fee_estimate: bool):
yes. can you suggest a better name?

2021-07-12 15:20 UTC, Nullably commented on hummingbot/connector/connector/uniswap_v3/uniswap_v3_connector.py
> +    async def _remove_position(self, hb_id: str, token_id: str, reducePercent: Decimal, fee_estimate: bool):
This function wraps around `remove-position` end point, the change is probably too much at this stage (as you will need to change Gateway as well). I am ok with the function name, but the parameter `fee_estimate` could be something like `to_estimate_fee_only` and good doc string would help explaining.

2021-07-13 05:56 UTC, PtrckM commented
Test with `use_volatility` = `True` or `False` on mainnet
- no message or confirmation if order is completed or not - due insufficient fund (gas fee)
   - instead throws HTTP status is 500
- incomplete `status` command 
![image](https://user-images.githubusercontent.com/54516858/125389120-4a5ac780-e3d3-11eb-91f6-1b11194e2914.png)

- bot accepts 0 value for `base_token_amount` 
![image](https://user-images.githubusercontent.com/54516858/125389232-77a77580-e3d3-11eb-8a8a-b5e7b7ccd731.png)
![image](https://user-images.githubusercontent.com/54516858/125389431-c523e280-e3d3-11eb-9261-c3303235971f.png)
![image](https://user-images.githubusercontent.com/54516858/125389480-d967df80-e3d3-11eb-90b0-db8070dfc185.png)

- logs and configs
[07132021.zip](https://github.com/CoinAlpha/hummingbot/files/6805966/07132021.zip)

2021-07-13 06:30 UTC, Nullably commented on hummingbot/connector/connector/uniswap_v3/uniswap_v3_connector.py
>          Calls add position end point to create/increase a range position.
```suggestion
        Calls remove position end point to remove/decrease a range position.
```

2021-07-13 08:59 UTC, vic-en commented
@PtrckM I addressed the issue with some configs allowing a value of zero. Kindly confirm.

2021-07-13 10:20 UTC, Nullably approved these changes
LGTM

2021-07-14 01:00 UTC, PtrckM approved these changes
- Fix issue value 0 on `base_token_amount` :white_check_mark: 

- Re-tested and confirmed working by QA.

2021-07-14 10:52 UTC, merged