Fix/Remove Merging orders option (avellaneda strategy) from the code base
CoinAlpha/hummingbot pull request #3924
Opened 2021-08-12 16:04 UTC by mhrvth

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Removed hanging order merging logic, settings, tests and documentation from the Avellaneda-Stoikov strategy. The functionality was already disabled through default settings.

**Tests performed by the developer**:

Ran all unit tests of the Avellaneda-Stoikov strategy and tests in test_hanging_orders_tracker.py . Ran the hummingbot, created and ran the Avellaneda-Stoikov strategy on Huobi exchange.

**Tips for QA testing**:

There's no new functionality, and no new tests. The code and the tests were only removed.

2021-08-12 18:36 UTC, aarmoa requested changes
I added a small comment. Even when the change is small it is required to merge the PR.

2021-08-12 18:36 UTC, aarmoa commented on hummingbot/templates/conf_avellaneda_market_making_strategy_TEMPLATE.yml
> -## Select way of aggregating hanging orders. Whether if leaving them as they are or calculating a resulting hanging order
When changing any TEMPLATE.yml it is important to change the "template_version" value (at the beginning of the file)

2021-08-13 05:47 UTC, RC-13 approved these changes
Tested Avellaneda market-making strategy and didn't encounter any issue. LGTM

2021-08-13 12:24 UTC, aarmoa approved these changes
The changes to remove hanging orders aggregation look good to me

2021-08-13 12:46 UTC, merged