doc / added how to change timezone of Hummingbot
CoinAlpha/hummingbot pull request #4119
Opened 2021-09-08 10:33 UTC by cali-tomas

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- How to change timezone of Hummingbot
- Added 2 images needed
![image](https://user-images.githubusercontent.com/85161223/132494163-25149cbf-6276-4831-ade7-6c3837d353b8.png)

**Tests performed by the developer**:

**Tips for QA testing**:

2021-09-09 03:54 UTC, mifeng submitted a review, later dismissed

2021-09-13 02:06 UTC, dennisocana requested changes
Sent feedback about the comments format for consistency.

2021-09-13 02:27 UTC, cali-tomas commented
Changes made in the latest commit
![image](https://user-images.githubusercontent.com/85161223/133014938-413a413b-55a8-4a06-999a-1bb68f17f034.png)

2021-09-13 06:11 UTC, dennisocana approved these changes

2021-09-13 06:11 UTC, merged