refactor/coinzoom api throttler
CoinAlpha/hummingbot pull request #4125
Opened 2021-09-08 19:14 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Changes in Coinzoom connector to stop using the old throttler and replace it with an instance of the new AsyncThrottler.

**Tests performed by the developer**:
Added unit tests for all the functions that use the throttler to send http requests or websocket requests.

**Tips for QA testing**:
For this PR we require the basic connector validations.

2021-09-10 13:08 UTC, dennisocana commented
We still need to merge the API Throttler integration for KuCoin to easily review this pull request.

2021-09-11 03:59 UTC, aarmoa commented
The PR can now be reviewed (both from development side and from QA side)

2021-09-11 06:02 UTC, PtrckM commented
- keep getting this error frequently after starting the bot,  `rate_limits_share_pct 100` on `order_refresh_time 20` and disabled `order_refresh_tolerance_pct`. No order stuck and does not seems to affect creating and cancelling orders. After sometime the error message disappears.

![orderbook_error](https://user-images.githubusercontent.com/54516858/132936119-c1a49fbd-2824-4c21-9fe7-820b32c89666.png)

```
2021-09-11 04:24:14,729 - 63959 - hummingbot.connector.exchange.coinzoom.coinzoom_order_book_tracker - NETWORK - Unexpected error routing order book messages.
Traceback (most recent call last):
  File "/home/ubuntu/coinzoom_api_throttler/hummingbot/core/data_type/order_book_tracker.py", line 301, in _emit_trade_event_loop
    trade_message.content["trade_type"] == float(TradeType.SELL.value) else TradeType.BUY
KeyError: 'trade_type'
```
- getting random reconnection/disconnection when api rate limit warning shows causing timedout error, no order getting stuck on exchange as well.
![timedout](https://user-images.githubusercontent.com/54516858/132936635-71b78616-c290-44cb-8a40-7465a238c285.png)

```
2021-09-11 04:47:56,004 - 64113 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task:
Traceback (most recent call last):
  File "hummingbot/connector/in_flight_order_base.pyx", line 84, in hummingbot.connector.in_flight_order_base.InFlightOrderBase.get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/coinzoom_api_throttler/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/coinzoom_api_throttler/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 532, in _execute_cancel
    await tracked_order.get_exchange_order_id()
  File "hummingbot/connector/in_flight_order_base.pyx", line 83, in get_exchange_order_id
    async with timeout(10):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

- config and logs:
[cz.zip](https://github.com/CoinAlpha/hummingbot/files/7147220/cz.zip)

2021-09-13 04:22 UTC, petioptrv requested changes
Left a couple comments in the code. There is also an edge-case scenarios that I encountered in the previous adaptations that I think is not yet handled here: the possibility of an order-creation being rate-limited, then calling `_execute_cancel` which can timeout on line 532 (`await tracked_order.get_exchange_order_id()`). The previous adaptations just skip the cancellation request, which I think here would amount to setting `order_was_cancelled = False`. The strategy will request the cancellation again on the next iteration and if the order has been submitted, things will go as planned.

2021-09-13 04:22 UTC, petioptrv commented on test/hummingbot/connector/exchange/coinzoom/test_coinzoom_api_order_book_data_source.py
> +    @patch("time.time")
Shouldn't we, in this case, apply the same treatment as with the `asyncio.sleep` module; i.e. mock a module-specific function instead?

2021-09-13 04:22 UTC, petioptrv commented on test/hummingbot/connector/exchange/coinzoom/test_coinzoom_api_order_book_data_source.py
> +    def _register_sent_request(requests_list, url, **kwargs):
Unused method

2021-09-13 19:08 UTC, aarmoa commented
@PatrickLiPM thank you for the details. The issue should be solved with the last commit.

2021-09-14 03:35 UTC, petioptrv approved these changes
I like the idea to make the order non-local in `update_exchange_order_id`. I'll adopt that for Kraken as well

2021-09-14 06:03 UTC, rxlxrxsx approved these changes
Confirmed fix for issues listed above and no other issues found during testing by QA. Approved.

2021-09-14 17:44 UTC, merged