Fix/gateio inconsistency in balance update
CoinAlpha/hummingbot pull request #4196
Opened 2021-09-15 19:21 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The PR removes the logic that executed a balance update after each order status update. That logic introduced a delay in processing order updates, and caused some order refresh cycles to be execute with an inconsistent balance.

**Tests performed by the developer**:
Tested by running PMM strategy with refresh time = 20 seconds

**Tips for QA testing**:
Test replicating scenario described in the original bug description

Fixes #3686

2021-09-16 04:06 UTC, rxlxrxsx commented
- There are instances that the available balance on status output doesn't update at all and because of that it sometimes shows an incorrect balance output when orders are cancelled (second screenshot)
<img width="691" alt="Screen Shot 2021-09-16 at 9 42 39 AM" src="https://user-images.githubusercontent.com/64377055/133546988-02be27b1-84a5-4943-8b2d-6e6268078caa.png">

<img width="699" alt="Screen Shot 2021-09-16 at 9 43 48 AM" src="https://user-images.githubusercontent.com/64377055/133547057-828897ed-a1ee-4fef-bfd3-f9682e817988.png">

2021-09-16 04:16 UTC, CrimsonJacket commented on hummingbot/connector/exchange/gate_io/gate_io_exchange.py
> +            self.logger().warning(f"Buy order amount {amount} is lower than the minimum order size "
Pretty sure not all orders are "Buy" orders :) Maybe it would be better to use `trade_type.name` instead.

2021-09-16 04:26 UTC, CrimsonJacket requested changes
Minor comments, but the rest LGTM.

2021-09-16 04:26 UTC, CrimsonJacket commented on hummingbot/connector/exchange/gate_io/gate_io_exchange.py
> +            self.logger().warning(f"Buy order amount {amount} is lower than the minimum order size "
Pretty sure not all orders are "Buy" orders :) Maybe it would be better to use `trade_type.name` instead.

2021-09-16 13:08 UTC, aarmoa commented
> * There are instances that the available balance on status output doesn't update at all and because of that it sometimes shows an incorrect balance output when orders are cancelled (second screenshot)
> 
> <img alt="Screen Shot 2021-09-16 at 9 42 39 AM" width="691" src="https://user-images.githubusercontent.com/64377055/133546988-02be27b1-84a5-4943-8b2d-6e6268078caa.png">
> 
> <img alt="Screen Shot 2021-09-16 at 9 43 48 AM" width="699" src="https://user-images.githubusercontent.com/64377055/133547057-828897ed-a1ee-4fef-bfd3-f9682e817988.png">

Hello @rxlxrxsx. I am not sure I understand the issue. In the first screenshot there available balances are:
```
ETH_initial = 0.015
BTC_initial = 0.0008
```
And we have the four orders created.

Then in the second screenshot all the orders are cancelled. If we recalculate manually the available balance after cancellation we get:
```
ETH = ETH_initial + sell_order_amount + sell_order_amount = 0.015 + 0.005 + 0.005 = 0.025
BTC = BTC_initial + (buy_order_price * buy_order_amount) + (buy_order_price * buy_order_amount) = 0.0008 + (0.073339 * 0.005) + (0.072591 * 0.005) = 0.0008 + 0,000366695 + 0,000362955 = 0,0015 (rounded)
```
These values are the same values shown in the second screenshot as available balances.

What is the issue to solve?

2021-09-16 14:23 UTC, aarmoa commented
Clinton provided more information about this already. The problem is that the available balance in the second screenshot (without orders) is different than the Total Balance

2021-09-16 20:12 UTC, aarmoa commented
@rxlxrxsx I have one more question. Do you know if more than one bot was trading using the same account when the error happened?

2021-09-16 20:23 UTC, aarmoa commented
Also, do you happen to have handy the client logs of the moment you took those screenshots? If you do, could you attach them to the PR and also indicate the approximate time of the error? I would like to find out if there is anything odd happening with orders cancellation.

2021-09-17 04:59 UTC, RC-13 approved these changes
I've spoken to @rxlxrxsx and he mentioned that this issue he reported occurred randomly during his first 2hrs test run and after continuous run, he did not see the issue again. Did another test run for 2 hours and 10 min and did not encounter the behavior, same number of order levels are created whenever refreshed.

Approving in behalf of QA

2021-09-23 04:46 UTC, CrimsonJacket submitted a review, later dismissed
Changes LGTM.
Just one thing I have to bring up, would it be wise to include a unit test that checks for the total and available balance for connectors that do not have any/adequate balance updates via websocket? I do understand that this should be part of the unit test for `ConnectorBase` but it is in Cython after all.

2021-09-24 12:34 UTC, CrimsonJacket approved these changes
Re-approving PR.

2021-09-24 12:40 UTC, merged