updates to blocktane trading pair parser
CoinAlpha/hummingbot pull request #4210
Opened 2021-09-17 13:39 UTC by trkoneill18

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2021-09-17 14:14 UTC, dennisocana commented
Thank you for this update @trkoneill18 , please also address the flake8 error reported below.

![image](https://user-images.githubusercontent.com/50150287/133797414-64f690e9-4a60-4409-9254-6a047b68ad82.png)

2021-09-17 14:40 UTC, dennisocana commented
@CoinAlpha/qa-team please test the proposed changes to Blocktane connector.

2021-09-20 02:16 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

2021-09-20 06:31 UTC, petioptrv requested changes
Very nice. Just one comment that I left in the code

2021-09-20 06:31 UTC, petioptrv commented on hummingbot/connector/exchange/blocktane/blocktane_utils.py
> +            pass  # Will fall back to regex splitting
I think this should be a separate private function (e.g. `_populate_lookups`), called from both `split_trading_pair` and `convert_to_exchange_trading_pair`

2021-09-22 02:02 UTC, petioptrv approved these changes
Changes LGTM!

2021-09-22 02:10 UTC, merged