Refactor/gateway connectors
CoinAlpha/hummingbot pull request #4244
Opened 2021-09-22 09:39 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR addresses refactor as stated in https://github.com/CoinAlpha/hummingbot/issues/3306

**Tests performed by the developer**:

**Tips for QA testing**:

2021-09-27 18:24 UTC, martinkou approved these changes

2021-09-28 07:27 UTC, Nullably requested changes
The design was to have gateway and ethereum base classes, so we're not going with this anymore? How does Terra, Avalanche and other protocols fit into this?

2021-09-28 14:27 UTC, mifeng commented
> The design was to have gateway and ethereum base classes, so we're not going with this anymore? How does Terra, Avalanche and other protocols fit into this?

The idea is that we only need a single Gateway class because the endpoints to the existing connectors we support in Gateway are all AMMs, so we can abstract all the endpoints down to a common standard trading interface. If we support other exchange designs in the future, we can add other connectors for them.

2021-09-29 01:14 UTC, Nullably approved these changes

2021-09-29 18:32 UTC, merged