maintenance/bitmart exchange unit tests
CoinAlpha/hummingbot pull request #4356
Opened 2021-10-01 08:29 UTC by petioptrv

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds unit tests for the Bitmart connector. It also refactors parts of the code where issues were discovered along the way.

**Tests performed by the developer**:
The entire PR

**Tips for QA testing**:
- Test that all orders are successfully cancelled when the run is stopped, as the function for this behaviour has been refactored.

2021-10-03 06:14 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

2021-10-04 04:35 UTC, CrimsonJacket requested changes
One minor comment. But other than that, unit tests LGTM.

2021-10-04 12:29 UTC, petioptrv commented on hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py
> +        self._trading_pairs = trading_pairs or []
The problem is that the default value is then an object shared across instances, so technically default values should be immutable. Same goes for having empty dictionaries as default values, etc

2021-10-04 12:43 UTC, aarmoa commented on hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py
> +        self._trading_pairs = trading_pairs or []
I agree with @petioptrv on this one: we should avoid having mutable objects as parameters defaults

2021-10-04 12:49 UTC, CrimsonJacket approved these changes
Changes LGTM

2021-10-04 12:52 UTC, merged