fix/configure bitmart to estimate balances
CoinAlpha/hummingbot pull request #4360
Opened 2021-10-01 20:21 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Changes to make the Bitmart connector estimate balances because the exchange does not provide online balance updates

**Tests performed by the developer**:
All unit tests passing in green

**Tips for QA testing**:
Check balance is kept consistent

Fixes #4115

2021-10-01 20:22 UTC, aarmoa commented
PR marked as draft until #4356 is merged into development branch

2021-10-05 04:06 UTC, CrimsonJacket requested changes
Just a minor comment on the order of imports. Rest LGTM

2021-10-05 04:06 UTC, CrimsonJacket commented on hummingbot/connector/exchange/bitmart/bitmart_exchange.py
> +import json
Minor comment on the import order.

2021-10-05 05:48 UTC, RC-13 approved these changes
Run a test bot for almost an hour and monitor the status and logs, confirmed that there was no inconsistency with the order creation. LGTM!

2021-10-05 13:29 UTC, CrimsonJacket approved these changes
Changes LGTM.

2021-10-05 13:38 UTC, merged