feat/ allow Kraken users to specify Account Tier
CoinAlpha/hummingbot pull request #4369
Opened 2021-10-04 10:54 UTC by CrimsonJacket

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This allows the user to effectively change the Rate Limit according to their Account Tiers.

To find your account tier click [here](https://www.kraken.com/u/verify).

For more info on the Rate Limits for the respective account tiers, refer to the links below:
REST API Rate Limits: https://support.kraken.com/hc/en-us/articles/206548367-What-are-the-API-rate-limits
Trading Engine Limits: https://support.kraken.com/hc/en-us/articles/360045239571

For existing users, please execute the `connect` command and re-insert your API credentials and specify your Account Tier

**Tests performed by the developer**:
Added new `ConfigVar` for in `kraken_utils`
Added necessary function(s) to parse and dynamically initialise Rate Limits
Added Unit Test [WIP]

**Tips for QA testing**:
Ensure that Kraken is working as intended.
Ensure that the API throttler is performing as it should given the different tiers.

2021-10-04 17:44 UTC, aarmoa commented on hummingbot/connector/exchange/kraken/kraken_exchange.pyx
> +                 kraken_api_tier: str = "starter"):
It might be better to use the Enum values here (transform the info to an Enum component right after loading the configuration)

2021-10-04 17:47 UTC, aarmoa commented on hummingbot/connector/exchange/kraken/kraken_utils.py
> +                  ),
It might be confusing for the user that the values provided in the prompt as clarification are in title case, but the default value is all lowercase

2021-10-04 17:49 UTC, aarmoa requested changes
There is a TEMPLATE file that has been changed but the version number has not been updated.
I have also added two more comments to be evaluated bu @CrimsonJacket

2021-10-04 17:49 UTC, aarmoa commented on hummingbot/templates/conf_global_TEMPLATE.yml
> +kraken_api_tier: null
Since we are changing the template file the version number should change too.

2021-10-05 01:34 UTC, RC-13 commented
Getting unhandled error when setting up the account tier which blocks the API connection
```
2021-10-05 08:23:07,466 - 4447 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: _build_async_throttler() takes no keyword arguments
Traceback (most recent call last):
  File "/Users/clintgogoc/Github/kraken-tier/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/clintgogoc/Github/kraken-tier/hummingbot/client/command/connect_command.py", line 67, in connect_exchange
    err_msg = await asyncio.wait_for(
  File "/Users/clintgogoc/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/Users/clintgogoc/Github/kraken-tier/hummingbot/user/user_balances.py", line 53, in add_exchange
    market = UserBalances.connect_market(exchange, **api_details)
  File "/Users/clintgogoc/Github/kraken-tier/hummingbot/user/user_balances.py", line 26, in connect_market
    connector = connector_class(**init_params)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 119, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.__init__
    self._throttler = self._build_async_throttler(api_tier=self._kraken_api_tier)
TypeError: _build_async_throttler() takes no keyword arguments
```
![kraken-tier](https://user-images.githubusercontent.com/57189990/135946595-f31b3574-f3cc-4209-acb3-dc7af788954f.png)
and also minor cosmetic issue on the tier autocomplete list
![kraken-api-tier-options](https://user-images.githubusercontent.com/57189990/135946629-d93ba0c5-de54-4159-8839-4e1604c7a857.png)

2021-10-05 04:08 UTC, CrimsonJacket commented
> Getting unhandled error when setting up the account tier which blocks the API connection

@RC-13 . It seems like you did not re-compile it.

2021-10-06 05:45 UTC, rxlxrxsx commented
There are times that when an order is filled, there are no trade notifications appearing on the left pane. On this instance, 3 out of 3 trades didn't get any notification. These trades aren't partially filled and is showing both on history and at the bottom nav bar. We tried to reproduce this on development but didn't get the same behavior.

<img width="1423" alt="Screen Shot 2021-10-06 at 1 30 48 PM" src="https://user-images.githubusercontent.com/64377055/136146414-795246c2-ad96-498c-8193-5905b41b4c1e.png">

Logs and config: [kraken_tier.zip](https://github.com/CoinAlpha/hummingbot/files/7291079/kraken_tier.zip)

2021-10-06 11:35 UTC, rapcmia approved these changes
Tested and confirm all reported issues are fixed on the latest commit. Approved on behalf of QA team

2021-10-06 12:56 UTC, merged