refactor/ Paper Trade Rework
CoinAlpha/hummingbot pull request #4574
Opened 2021-10-26 10:17 UTC by CrimsonJacket

**Before submitting this PR, please make sure**:

* [x] Your code builds clean without any errors or warnings
* [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

* [x] paper_trade command removed
* [x] paper_trade_mode ticker removed
~~* [ ] New paper_trade_exchanges global config added~~

**Tests performed by the developer**:
Numerous changes throughout Hummingbot Client to include Paper Trade support for selected exchanges.
Changes are mainly on the `commands`, `global_config_map` and the `hummingbot_application.py` files
Added `AllConnectorSettings` class object.
Refactor various components to dynamically call `AllConnectorSettings` to retrieve connector settings.

**Tips for QA testing**:
Any strategy that works with spot exchange (connector) works with the following exchanges

* `binance_paper_trade`
* `kucoin_paper_trade`
* `ascend_ex_paper_trade`
* `gate_io_paper_trade`

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rvw2kh) by [Unito](https://www.unito.io)

2021-11-01 03:10 UTC, Nullably requested changes

2021-11-01 03:10 UTC, Nullably commented on hummingbot/client/settings.py
> +EXAMPLE_PAIRS = {name: cs.example_pair for name, cs in AllConnectorSettings.get_connector_settings().items()}
We don't need to keep these 2 constants (they can be class method like all the others). Let's keep it clean, keep constants for only primitive values.

2021-11-01 13:10 UTC, dennisocana commented
@RC-13 QA can start testing the PR

2021-11-02 03:44 UTC, bluecammut commented
LGTM

2021-11-02 04:47 UTC, RC-13 commented
When using any of the paper trade connector and aroon-oscillator strategy, the following error comes up and preventing the strategy to start:
```python
2021-11-02 04:42:20,387 - 15797 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/ubuntu/paper/hummingbot/strategy/aroon_oscillator/start.py", line 55, in start
    self._initialize_wallet(token_trading_pairs=list(set(maker_assets)))
AttributeError: 'HummingbotApplication' object has no attribute '_initialize_wallet'
2021-11-02 04:42:20,388 - 15797 - hummingbot.client.hummingbot_application - INFO - start command initiated.
```
![image](https://user-images.githubusercontent.com/57189990/139788331-40cc4b55-58ea-4cf4-aa24-9db6c609016e.png)

2021-11-02 05:14 UTC, Nullably approved these changes
LGTM

2021-11-02 07:00 UTC, rapcmia approved these changes
Tested and confirmed ok. Approved on behalf of QA

2021-11-02 10:33 UTC, merged