add new exchange mexc
CoinAlpha/hummingbot pull request #4620
Opened 2021-10-29 08:59 UTC by MXCDev

**Before submitting this PR, please make sure**:

* [x] Your code builds clean without any errors or warnings
* [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1tjhju7) by [Unito](https://www.unito.io)

2021-11-05 01:13 UTC, dennisocana commented
@MXCDev 

![image](https://user-images.githubusercontent.com/50150287/140441823-6b459ef3-55dc-42e6-b96e-ca723d84786d.png)

2021-11-05 01:32 UTC, dennisocana requested changes
@MXCDev please add `mexc_api_key` and `mexc_secret_key` in [conf_global_TEMPLATE.yml](https://github.com/mxcdevelop/hummingbot/blob/feat/add_new_exchange_mexc_global/hummingbot/templates/conf_global_TEMPLATE.yml)

![image](https://user-images.githubusercontent.com/50150287/140441823-6b459ef3-55dc-42e6-b96e-ca723d84786d.png)

2021-11-07 09:16 UTC, MXCDev commented
@dennisocana  hi. we add unit test. pls approval auto test

2021-11-10 05:40 UTC, rxlxrxsx commented
- Inconsistent order creation due to delay (around 1s) in balance update. See clip attached for reference.

https://user-images.githubusercontent.com/64377055/141056244-92e6de13-8c95-46f4-90b1-34ea32514e87.mp4

Logs and config: [mexc_delay.zip](https://github.com/CoinAlpha/hummingbot/files/7510144/mexc_delay.zip)

2021-11-14 07:35 UTC, rxlxrxsx commented
> Inconsistent order creation due to delay (around 1s) in balance update. See clip attached for reference.

This is confirmed fixed.

- Another issue found - When restarting the strategy with hanging orders enabled, the cancelled orders after stopping the strategy are recognized as hanging orders that are cancelled after restart.

<img width="1423" alt="Screen Shot 2021-11-14 at 9 33 47 AM" src="https://user-images.githubusercontent.com/64377055/141672017-45c428fa-e3d5-4afb-a196-8a74a52f2148.png">

<img width="1422" alt="Screen Shot 2021-11-14 at 9 34 22 AM" src="https://user-images.githubusercontent.com/64377055/141672027-02f96032-2b4a-44d4-b78f-9cc36fdd855e.png">

Logs and config: [mexc.zip](https://github.com/CoinAlpha/hummingbot/files/7533349/mexc.zip)

2021-11-15 13:52 UTC, MXCDev commented
@rxlxrxsx  fixed.

2021-11-16 04:42 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA. No other issues found during testing.

2021-11-16 12:27 UTC, dennisocana approved these changes
Awaiting review and approval from engineering team.

2021-11-17 08:16 UTC, CrimsonJacket requested changes
I noticed that some components are implemented in Cython, we're aiming for a Python-only connector architecture so as much as possible please do use Python. 

Also I noticed that you've decided to use fixtures along with `MockWebServer` for testing, I would request the usage of `aioresponses` and our own `NetworkMockingAssistant` class for unit testing. Refer to Ndax connector and its unit tests if needed.

Left some additional comments wrt usage of the same `aiohttp.ClientSession` across the Exchange, APIOrderBookDataSource and UserStreamDataSource components. Again refer to Ndax connector.

Minor issue with updating the `template_version` in `conf_global_TEMPLATE.yml `

2021-11-17 08:16 UTC, CrimsonJacket commented on hummingbot/connector/exchange/mexc/mexc_api_user_stream_data_source.py
> +        super().__init__()
As much as possible, lets use the same `_shared_client: aiohttp.ClientSession` from `MexcExchange`.

2021-11-17 08:16 UTC, CrimsonJacket commented on hummingbot/templates/conf_global_TEMPLATE.yml
> +
Do update the `template_version` to `29` at the top of the TEMPLATE file.

2021-11-18 04:19 UTC, CrimsonJacket commented
@MXCDev After some discussion with the team, I'd like to clarify that a full Python implementation is optional.

2021-11-18 11:10 UTC, CrimsonJacket approved these changes
Changes LGTM.

I will also like to take this chance to include the changes/improvements to expect in v0.47
1. Python-only implementation
2. Improved unit testing
3. Improved handling/utilization of `aiohttp` websocket connections
4. Better management of `aiohttp.ClientSession` across all connector components
5. Integration of `AsyncThrottler` with MEXC spot exchange connector

2021-11-19 01:39 UTC, PtrckM approved these changes
Tested and confirmed working by QA. No issue found during retesting of the changes applied.

2021-11-19 06:40 UTC, merged