fix/crypto com order book tracker default initialization parameter
CoinAlpha/hummingbot pull request #4663
Opened 2021-11-07 19:24 UTC by sisco0

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

A fix was requested at issue https://github.com/CoinAlpha/hummingbot/issues/4659, where the _Crypto Com_ exchange could not be used for price tracking. The reason behind this issue is because an initialization parameter required for the instantiation of the proper _Order Book Tracker_ of the `crypto_com` connector was not had.

The proposed fix sets a default value for the `shared_client` parameter, enabling the connector functionality without inconvenience.

**Tests performed by the developer**:

The configuration file `conf_pure_mm_2.txt` provided by the referenced issue users was used for testing, screenshots of the before and after behaviour are shown in the referenced issue.

**Tips for QA testing**:

A test set should be enabled for checking each connector, including the _crypto com_ one.

2021-11-11 03:40 UTC, rxlxrxsx submitted a review, later dismissed
Tested and confirmed working by QA.

2021-11-16 17:34 UTC, aarmoa requested changes
If the parameter will be assigned with `None` as the default value, it has to be typed as `Optional`

2021-11-16 17:34 UTC, aarmoa commented on hummingbot/connector/exchange/crypto_com/crypto_com_order_book_tracker.py
> +        shared_client: aiohttp.ClientSession = None,
```suggestion
        shared_client: Optional[aiohttp.ClientSession] = None,
```

2021-11-22 17:28 UTC, aarmoa approved these changes
The change looks good to me

2021-11-23 07:44 UTC, rxlxrxsx approved these changes
Re-approving in behalf of QA.

2021-11-25 12:47 UTC, merged