refactor/ Huobi aiohttp websocket
CoinAlpha/hummingbot pull request #4784
Opened 2021-11-22 10:34 UTC by CrimsonJacket

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Update Huobi connector to use `WebAssistantsFactory`.

**Tests performed by the developer**:
Update `HuobiExchange`, `HuobiAPIOrderBookDataSource`, `HuobiUserStreamDataSource`
Add `HuobiWSPostProcessor` to handle gzip compressed Market Data messages
Update `WSConnection` to handle `aiohttp.WSMsgType.BINARY` and `aiohttp.WSMsgType.CLOSE` messages.
Update `WebAssistantsFactory` to include pre_processors and post_processors

**Tips for QA testing**:
Ensure Huobi connector works as usual.

2021-11-23 06:19 UTC, petioptrv requested changes
Left a couple of small comments / suggestions in the code

2021-11-23 06:33 UTC, CrimsonJacket commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
> +    TRADE_CHANNEL_SUFFIX = "trade.detail"
According to Huobi's [docs](https://huobiapi.github.io/docs/spot/v1/en/#trade-detail), it is a suffix.

>
\# Orderbook Depth Response
{
  "id": "id1",
  "status": "ok",
  "subbed": "market.btcusdt.depth.step0",
  "ts": 1489474081631 //system response time
}
>
\# Trade Detail Response
{
  "id": "id1",
  "status": "ok",
  "subbed": "market.btcusdt.trade.detail",
  "ts": 1489474081631 //system response time
}

2021-11-23 06:40 UTC, CrimsonJacket commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
> +                    if self.TRADE_CHANNEL_SUFFIX in channel:
I agree with these changes. I will update em accordingly.

2021-11-23 06:40 UTC, CrimsonJacket commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
> +                    if self.ORDERBOOK_CHANNEL_SUFFIX in channel:
I agree with these changes. I will update em accordingly.

2021-11-23 06:50 UTC, CrimsonJacket commented on hummingbot/connector/exchange/huobi/huobi_exchange.pyx
> +                              data=ujson.dumps(data) if data else "",
Good catch 🎣

2021-11-23 07:33 UTC, petioptrv commented on hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py
> +    TRADE_CHANNEL_SUFFIX = "trade.detail"
My mistake! I think it's time for another coffee

2021-11-23 07:36 UTC, petioptrv approved these changes
Changes LGTM!

2021-11-25 03:51 UTC, rapcmia approved these changes
Tested and working ok, approved on behalf of QA team

2021-11-25 09:28 UTC, merged