Feat/add gateway create command
CoinAlpha/hummingbot pull request #4858
Opened 2021-12-03 16:05 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

2021-12-06 19:31 UTC, martinkou requested changes

2021-12-06 19:31 UTC, martinkou commented on hummingbot/client/command/gateway_command.py
> +            pull_logs = iter(self._docker_client.pull(gateway_docker_name, tag="gateway-v2", stream=True, decode=True))
The iterator here is synchronous, which causes the `prompt-toolkit` UI library to be unresponsive during the image pull.

There are two options here:

 1. Wrap this in a thread via `run_in_executor()`, and then use `call_soon_threadsafe()` from the child thread to schedule the message back to the main thread. You can then wrap this all again into an async iterator, s.t. you can do `async for message in thread_pull_wrapper.pull(...): ...`.
 2. Use `aiokafka` instead. They also have a stream option.

2021-12-06 19:32 UTC, martinkou commented on hummingbot/client/command/gateway_command.py
> +                    self.logger().info(json.dumps(next(pull_logs), indent=4))
Need to think about what kind of log output format makes the most sense for the user - rather than just dumping the JSON to the user.

2021-12-16 08:22 UTC, martinkou commented
Architecture-wise, I think the new patch makes sense - running the docker pull in another thread while logging the lines there. I'd like to see a video of it in action before approving this.

2021-12-16 13:14 UTC, vic-en commented
@martinkou Here ==> https://youtu.be/HbnULDrh8Ag

2021-12-16 18:31 UTC, martinkou approved these changes

2021-12-16 18:31 UTC, merged