add noqa tags
CoinAlpha/hummingbot pull request #53
Opened 2022-01-21 00:27 UTC by vic-en

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

2022-01-21 00:55 UTC, vic-en commented
[ch21177]

2022-01-26 21:58 UTC, martinkou requested changes

2022-01-26 21:58 UTC, martinkou commented on test/connector/connector/uniswap/test_uniswap_connector.py
> +            "0xdc393a78a366ac53ffbd5283e71785fd2097807fef1bc5b73b8ec84da47fb8de",  # noqa: mock
This is an actual private key and not all of the test cases are mocks. Shouldn't this be marked with a TODO and a related task item instead?

2022-01-26 21:58 UTC, martinkou commented on test/connector/connector/balancer/test_balancer_connector.py
> +            "0xdc393a78a366ac53ffbd5283e71785fd2097807fef1bc5b73b8ec84da47fb8de",  # noqa: mock
ditto here

2022-02-01 09:10 UTC, martinkou approved these changes

2022-02-01 09:10 UTC, merged