feat/order age from creation timestamp
CoinAlpha/hummingbot pull request #61
Opened 2022-01-26 03:09 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Change in the implementation of the order age calculation to stop using the timestamp that is part of the order_id and start using the new creation_timestamp field in the orders.

**Tests performed by the developer**:
Added unit tests.
Manually tested using a PMM strategy connected to paper trade Binance spot connector.

**Tips for QA testing**:
- Check status command for the strategies report age correctly.
- Check age in trade events stored in the DB and in CSV files is correct.

[ch21140]

2022-01-27 01:49 UTC, petioptrv requested changes

2022-01-27 01:49 UTC, petioptrv commented on hummingbot/strategy/utils.py
>      Get the age of a limit order in second, not applicable to paper trade orders
```suggestion
    Get the age of a limit order in second.
```

2022-01-27 01:49 UTC, petioptrv commented on hummingbot/strategy/hedge/hedge.pyx
> +            order_age = order_age(0, self._current_timestamp)
```suggestion
            order_age = order_age(o, self._current_timestamp)
```

2022-01-27 02:27 UTC, PtrckM commented
Update: Confirmed debugging messages are now remove, changes are look good and behaving as expected. We will wait for the requested changes to be pushed before approving.

2022-01-27 05:56 UTC, PtrckM approved these changes
Tested and approved by QA team.
Test Summary:
    - Create and start a PMM strategy using AscendEX, Binance, and Binance_paper_trade connector
    - Run status --live and monitor the age of each order created: Confirmed that each order gets cancelled according to the specified order refresh time
    - Filled event: Ok
    - Run history --verbose to check the order_age
    - Compare the timestamp saved in the CSV and sqlite file (filled table): Match
    - Compare the order age of the filled order using the data on history vs order age in the csv file and using the creation timestamp and filled timestamp in the sqlite file: Order age matched
    - Create an Avellaneda MM strategy, Liquidity Mining strategy, Perpetual MM, Aroon Osicillator and Hedge strategy then repeat the steps: Confirm that order age recorded in the history, CSV, and Sqlite file are matched
    - Confirmed that all exchanges that support paper trade working as expected with order age.

2022-01-27 08:17 UTC, petioptrv approved these changes
Changes LGTM!

2022-02-16 08:06 UTC, rxlxrxsx commented
Recent changes still LGTM. I didn't submit an approval as it already has enough. Tests performed were same as above.

2022-02-24 20:35 UTC, aarmoa commented
Closing this PR after creating an equivalent one in the Hummingbot repository: https://github.com/hummingbot/hummingbot/pull/5143

2022-02-24 20:36 UTC, closed without merging