(fix) Fixes the test MEXC test cases that attempt to contact the server.
CoinAlpha/hummingbot pull request #72
Opened 2022-02-02 07:57 UTC by petioptrv

**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR simply fixes the REST mocking performed in the MEXC test cases. Nothing else has been changed in the tests themselves.

**Tests performed by the developer**:
I've monitored the network traffic of a test-case run with Little Snitch and nothing was detected where there used to be multiple connection attempts previously.

**Tips for QA testing**:
N/A

2022-02-02 13:47 UTC, aarmoa requested changes
I just found some issues with import statements

2022-02-02 13:47 UTC, aarmoa commented on test/hummingbot/connector/exchange/mexc/test_mexc_api_order_book_data_source.py
> +from unittest.mock import AsyncMock, patch
Are we keeping this import statements in this order because of import issues?

2022-02-02 13:47 UTC, aarmoa commented on test/hummingbot/connector/exchange/mexc/test_mexc_api_user_stream_data_source.py
> +from test.hummingbot.connector.network_mocking_assistant import NetworkMockingAssistant
This import is in the wrong place. We should correctly sorted unless it has been moved due to import issues.

2022-02-02 13:47 UTC, aarmoa commented on test/hummingbot/connector/exchange/mexc/test_mexc_exchange.py
> +import hummingbot.connector.exchange.mexc.mexc_constants as CONSTANTS
We need to review the import statements order here too

2022-02-02 13:47 UTC, aarmoa commented on test/hummingbot/connector/exchange/mexc/test_mexc_user_stream_tracker.py
> +from test.hummingbot.connector.network_mocking_assistant import NetworkMockingAssistant
This import line seems to be in the wrong section

2022-02-02 13:47 UTC, aarmoa commented on test/hummingbot/connector/exchange/mexc/test_mexc_websocket_adaptor.py
> +from test.hummingbot.connector.network_mocking_assistant import NetworkMockingAssistant
The same happens with this one

2022-02-03 02:04 UTC, petioptrv commented
@aarmoa, looks like `isort` was not enough on this one. All imports should now be correctly sorted

2022-02-03 13:45 UTC, aarmoa approved these changes
Changes look good to me

2022-02-04 03:51 UTC, petioptrv commented
Closing and reopening on foundation side

2022-02-04 03:51 UTC, closed without merging