Fix/numpy array indices
CoinAlpha/hummingbot pull request #76
Opened 2022-02-03 22:37 UTC by mhrvth

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

After adding a sample to the RingBuffer, start and stop indexes are updated. When calling the c_get_as_numpy_array() afterwards, the method doesn't account for the shifted indexes (in case the buffer is already filled). 
As a result it returns an array with wrong data.

**Tests performed by the developer**:

* Printed c_get_as_numpy_array()'s output and compared it to the actual content of the buffer and the start and stop indices
* Ran unit tests

2022-02-03 22:38 UTC, mhrvth commented
[sc-22584]

2022-02-04 05:36 UTC, petioptrv requested changes
You can achieve the same with:
```Python
    cdef np.ndarray[np.double_t, ndim=1] c_get_as_numpy_array(self):
        cdef np.ndarray[np.int16_t, ndim=1] indexes

        if not self._is_full:
            indexes = np.arange(self._start_index, stop=self._stop_index, dtype=np.int16)
        else:
            indexes = np.arange(self._start_index - 1, stop=self._stop_index + self._length,
                                dtype=np.int16) % self._length
        return np.asarray(self._buffer)[indexes]
```
but we can simplify further with:
```Python
cdef class RingBuffer:
    ...

    def __cinit__(self, int length):
        self._length = length
        self._buffer = np.zeros(length, dtype=np.float64)
        self._stop_index = 0
        self._is_full = False

    ...

    cdef void c_increment_index(self):
        self._stop_index = (self._stop_index + 1) % self._length
        if self._stop_index == 0:
            self._is_full = True

    ...

    cdef np.ndarray[np.double_t, ndim=1] c_get_as_numpy_array(self):
        cdef np.ndarray[np.int16_t, ndim=1] indexes

        if not self._is_full:
            indexes = np.arange(0, stop=self._stop_index, dtype=np.int16)
        else:
            indexes = np.arange(self._stop_index, stop=self._stop_index + self._length,
                                dtype=np.int16) % self._length
        return np.asarray(self._buffer)[indexes]

    def __init__(self, length):
        self._length = length
        self._buffer = np.zeros(length, dtype=np.double)
        self._stop_index = 0
        self._is_full = False

    ...
```

Also, we should have a simple test for this:
```Python
def test():
    b = RingBuffer(4)

    for i in range(3):
        b.add_value(i)

    np.testing.assert_equal(b.get_as_numpy_array(), np.array([0, 1, 2]))

    b.add_value(3)

    np.testing.assert_equal(b.get_as_numpy_array(), np.array([0, 1, 2, 3]))

    b.add_value(4)

    np.testing.assert_equal(b.get_as_numpy_array(), np.array([1, 2, 3, 4]))
```

2022-02-04 06:13 UTC, PtrckM approved these changes
LGTM!
Test summary:
- Run unit test on the following:
  - test_instant_volatility.py 1/1 = Passed
  - test_historical_volatility.py 3/3 = All Passed
  - test_trading_intensity.py 1/1 = Passed
- Using nosetests on the said files passed all tests. No error found.

2022-02-04 09:07 UTC, petioptrv approved these changes
I like `_delimiter`. Changes LGTM!

2022-02-04 10:03 UTC, mhrvth commented
Create a PR in the Foundation repo: https://github.com/hummingbot/hummingbot/pull/5092

2022-02-04 10:03 UTC, closed without merging