fix / quickstart with password
CoinAlpha/hummingbot pull request #78
Opened 2022-02-05 13:42 UTC by martinkou

Fixed crash-at-start issue when using hummingbot_quickstart.py with password.

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This patch moves the stdout redirection logic to after the prompt_toolkit UI initiation, which guarantees the stdout redirection wouldn't redirect the UI rendering.

**Tests performed by the developer**:
* Tested with `hummingbot_quickstart.py` with password.
* Tested with `hummingbot.py`.

**Tips for QA testing**:
* Make sure to test `hummingbot_quickstart.py` with an autostart strategy and password as well.

2022-02-06 23:33 UTC, RC-13 commented
Error with quickstart no longer happens however, `start` doesn't seem to get triggered after the strategy is loaded (source and docker)

https://user-images.githubusercontent.com/57189990/152706267-5099fadc-8377-4475-9dbf-cde326a7986f.mov

2022-02-07 01:57 UTC, martinkou commented
Right... that's something I haven't tested in the weekend. I'll fix that tomorrow.

2022-02-07 05:51 UTC, CrimsonJacket requested changes
Minor comment on where the new `START` event should be located. Other than that LGTM

2022-02-07 05:51 UTC, CrimsonJacket commented on hummingbot/client/ui/hummingbot_cli.py
> +        START = 1
I think we should include this new event into `core.event.events.py` instead of having it in `hummingbot_cli.py`

2022-02-07 14:04 UTC, aarmoa commented on bin/hummingbot_quickstart.py
> +                hb.start(global_config_map.get("log_level").value)
@martinkou do we need to have the same class defined in two places? (in bin/hummingbot.py and in bin/hummingbot_quickstart.py)

2022-02-08 06:16 UTC, RC-13 approved these changes
LGTM! Successfully started my test strategy using the autostart script.

Test Summary:
- Clone and install feature branch (latest commit)
- Run autostart script (source)
  - Successfully starts the client without any error
   - Strategy is imported without any error
    - Automatically start the strategy
- Build a docker image
- Create a docker instance and create a new strategy
- Create a new folder directory and copy strategy from the previous instance
-  Create a docker instance using the autostart script for docker
   -  Successfully created an instance without any error
   - Successfully imported the strategy
   - Automatically start the strategy (paper trading)

2022-02-08 23:38 UTC, martinkou commented
I haven't changed any of the exchange connectors but I'm getting test case failures from them - and I can't reproduce the test errors locally. Need some help here.

2022-02-09 00:11 UTC, martinkou commented
@CrimsonJacket I've done the refactoring as requested. See if you're ok with the latest patch.

2022-02-09 06:45 UTC, CrimsonJacket approved these changes
Changes LGTM

2022-02-09 12:48 UTC, merged