Feat/allow fees in different tokens
CoinAlpha/hummingbot pull request #94
Opened 2022-02-17 16:00 UTC by aarmoa

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
In this PR we introduce the required changes for the client to accept having fees for a trade in different tokens (something that happens with Binance connector, that sometimes can charge fees in BNB and sometimes in the trade quote token). The changes include:
- Remove fee_amount and fee_token from the order complete events, since that information was not being used anywhere
- Change PNL calculation logic to convert fees in different tokens to the quote token using the RateOracle as price provider
- Modification of the start command to always start also the RateOracle, for it to regularly update prices

**Tests performed by the developer**:
Added new unit tests.
Tested manually by running a PMM strategy against Binance and verifying that PNL is calculated without issues.

**Tips for QA testing**:
Please check that all connectors can correctly process order complete events.
Verify PNL calculation.

NOTE: It would be a good idea to retest all current issues related to PNL calculation with this PR. Many of them could be solved with this changes.

2022-02-18 05:07 UTC, petioptrv requested changes

2022-02-18 05:08 UTC, petioptrv commented
I've suggested some very minor changes that will not invalidate QA tests

2022-02-18 06:19 UTC, RC-13 commented
QA update: Testing currently in progress

2022-02-18 13:34 UTC, aarmoa commented on hummingbot/core/rate_oracle/rate_oracle.py
> +    @async_ttl_cache(ttl=30, maxsize=1)
Yes, I think that is a good idea.

2022-02-19 10:23 UTC, petioptrv approved these changes
Changes LGTM!

2022-02-21 22:04 UTC, RC-13 commented
Update from yesterday, additional exchange tested:
Coinbase pro
Coinzoom
Crypto.com
will finish the remaining connectors today.

2022-02-22 08:21 UTC, RC-13 commented
Test update for today, finish testing the following connectors:
Digifinex
Dydx_perpetual
FTX
Gate_io
Huobi

2022-02-23 07:11 UTC, RC-13 approved these changes
LGTM
Test Summary:
- Test PR across different connectors except for connectors with a known issue and low volume exchange.
- Wait for both to both get a fill on bid and ask side and check the history performance.
- Check the rate of the fees paid in base asset using rate oracle 
- Manually compute the total PnL after getting the converted value of the fees paid and confirming that it matches or is close enough to the displayed total PnL
- Enable the use of a third-party asset for fee payment, for example, BNB, and wait for orders to get a filling.
- Manually convert the fees paid that are currently not in quote value and get the total fees paid.
- Manually compute for the total PnL again and confirmed that the PnL matches the output in the performance.
- Check AMM connectors as well to make sure that fees and pnl are calculated properly.

2022-02-23 12:04 UTC, aarmoa commented
Waiting for https://github.com/hummingbot/hummingbot/pull/5120 to be merged before creating this PR in the foundation repository

2022-03-02 02:33 UTC, closed without merging